//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.VSResources", typeof(VSResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any active launch profiles configured for this project..
        /// </summary>
        internal static string ActiveLaunchProfileNotFound {
            get {
                return ResourceManager.GetString("ActiveLaunchProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component (Windows Forms) Designer.
        /// </summary>
        internal static string ComponentEditor_DisplayName {
            get {
                return ResourceManager.GetString("ComponentEditor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug executable &apos;{0}&apos; specified in the &apos;{1}&apos; debug profile does not exist..
        /// </summary>
        internal static string DebugExecutableNotFound {
            get {
                return ResourceManager.GetString("DebugExecutableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework ({0}).
        /// </summary>
        internal static string DebugFrameworkMenuText {
            get {
                return ResourceManager.GetString("DebugFrameworkMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile {0}.
        /// </summary>
        internal static string DefaultNewProfileName {
            get {
                return ResourceManager.GetString("DefaultNewProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project doesn&apos;t know how to run the profile with name &apos;{0}&apos; and command &apos;{1}&apos;..
        /// </summary>
        internal static string DontKnowHowToRunProfile_2 {
            get {
                return ResourceManager.GetString("DontKnowHowToRunProfile_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show again.
        /// </summary>
        internal static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error in the launch settings file needs to be corrected before you can run the &apos;{0}&apos; project . Please see the error list for details..
        /// </summary>
        internal static string ErrorInProfilesFile {
            get {
                return ResourceManager.GetString("ErrorInProfilesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error in the launch settings file needs to be corrected before you can run the &apos;{0}&apos; project. {1}. Please see the error list for details..
        /// </summary>
        internal static string ErrorInProfilesFile2 {
            get {
                return ResourceManager.GetString("ErrorInProfilesFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the framework assembly..
        /// </summary>
        internal static string FrameworkAssemblyAssemblyNameDescription {
            get {
                return ResourceManager.GetString("FrameworkAssemblyAssemblyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string FrameworkAssemblyAssemblyNameDisplayName {
            get {
                return ResourceManager.GetString("FrameworkAssemblyAssemblyNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly version of the framework assembly..
        /// </summary>
        internal static string FrameworkAssemblyAssemblyVersionDescription {
            get {
                return ResourceManager.GetString("FrameworkAssemblyAssemblyVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Version.
        /// </summary>
        internal static string FrameworkAssemblyAssemblyVersionDisplayName {
            get {
                return ResourceManager.GetString("FrameworkAssemblyAssemblyVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Assembly.
        /// </summary>
        internal static string FrameworkAssemblyBrowseObjectClassName {
            get {
                return ResourceManager.GetString("FrameworkAssemblyBrowseObjectClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file version of the framework assembly..
        /// </summary>
        internal static string FrameworkAssemblyFileVersionDescription {
            get {
                return ResourceManager.GetString("FrameworkAssemblyFileVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Version.
        /// </summary>
        internal static string FrameworkAssemblyFileVersionDisplayName {
            get {
                return ResourceManager.GetString("FrameworkAssemblyFileVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of the framework assembly..
        /// </summary>
        internal static string FrameworkAssemblyPathDescription {
            get {
                return ResourceManager.GetString("FrameworkAssemblyPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string FrameworkAssemblyPathDisplayName {
            get {
                return ResourceManager.GetString("FrameworkAssemblyPathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying updates failed: {0}.
        /// </summary>
        internal static string HotReloadApplyUpdatesFailure {
            get {
                return ResourceManager.GetString("HotReloadApplyUpdatesFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates applied successfully..
        /// </summary>
        internal static string HotReloadApplyUpdatesSuccessful {
            get {
                return ResourceManager.GetString("HotReloadApplyUpdatesSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors found in application: .
        /// </summary>
        internal static string HotReloadErrorsInApplication {
            get {
                return ResourceManager.GetString("HotReloadErrorsInApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Reload.
        /// </summary>
        internal static string HotReloadOutputWindowPaneName {
            get {
                return ResourceManager.GetString("HotReloadOutputWindowPaneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilding and restarting the application since the edits can&apos;t be applied dynamically..
        /// </summary>
        internal static string HotReloadRestartInProgress {
            get {
                return ResourceManager.GetString("HotReloadRestartInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending updates to running application..
        /// </summary>
        internal static string HotReloadSendingUpdates {
            get {
                return ResourceManager.GetString("HotReloadSendingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Reload session started..
        /// </summary>
        internal static string HotReloadStartSession {
            get {
                return ResourceManager.GetString("HotReloadStartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping application..
        /// </summary>
        internal static string HotReloadStoppingApplication {
            get {
                return ResourceManager.GetString("HotReloadStoppingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Reload session complete..
        /// </summary>
        internal static string HotReloadStopSession {
            get {
                return ResourceManager.GetString("HotReloadStopSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Import comes fom target file. This import cannot be removed..
        /// </summary>
        internal static string ImportsFromTargetCannotBeDeleted {
            get {
                return ResourceManager.GetString("ImportsFromTargetCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Potential build performance issue in &apos;{0}&apos;. The project does not appear up-to-date after a successful build: {1}. See https://aka.ms/incremental-build-failure..
        /// </summary>
        internal static string IncrementalBuildFailureWarningMessage_2 {
            get {
                return ResourceManager.GetString("IncrementalBuildFailureWarningMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A circular dependency A -&gt; B -&gt; A was detected during NuGet Restore which caused NuGet to stop restoring.
        ///Because the NuGet restore didn&apos;t finish correctly, the project might be in a bad state..
        /// </summary>
        internal static string InfoBarMessageNuGetCycleDetected {
            get {
                return ResourceManager.GetString("InfoBarMessageNuGetCycleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing of multiple target framework is not supported..
        /// </summary>
        internal static string MultiTFEditNotSupported {
            get {
                return ResourceManager.GetString("MultiTFEditNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug profile &apos;{0}&apos; is missing the path to the executable to debug..
        /// </summary>
        internal static string NoDebugExecutableSpecified {
            get {
                return ResourceManager.GetString("NoDebugExecutableSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pack.
        /// </summary>
        internal static string PackCommand {
            get {
                return ResourceManager.GetString("PackCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pack {0}.
        /// </summary>
        internal static string PackSelectedProjectCommand {
            get {
                return ResourceManager.GetString("PackSelectedProjectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching to process..
        /// </summary>
        internal static string ProjectHotReloadSessionManager_AttachingToProcess {
            get {
                return ResourceManager.GetString("ProjectHotReloadSessionManager_AttachingToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while stopping the session: {0}
        ///{1}.
        /// </summary>
        internal static string ProjectHotReloadSessionManager_ErrorStoppingTheSession {
            get {
                return ResourceManager.GetString("ProjectHotReloadSessionManager_ErrorStoppingTheSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Hot Reload session: no active process..
        /// </summary>
        internal static string ProjectHotReloadSessionManager_NoActiveProcess {
            get {
                return ResourceManager.GetString("ProjectHotReloadSessionManager_NoActiveProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process has already exited..
        /// </summary>
        internal static string ProjectHotReloadSessionManager_ProcessAlreadyExited {
            get {
                return ResourceManager.GetString("ProjectHotReloadSessionManager_ProcessAlreadyExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process has exited..
        /// </summary>
        internal static string ProjectHotReloadSessionManager_ProcessExited {
            get {
                return ResourceManager.GetString("ProjectHotReloadSessionManager_ProcessExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Reload is not available because startup hooks have been disabled, possibly due to trimming..
        /// </summary>
        internal static string ProjectHotReloadSessionManager_StartupHooksDisabled {
            get {
                return ResourceManager.GetString("ProjectHotReloadSessionManager_StartupHooksDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with an Output Type of Class Library cannot be started directly.
        ///
        ///In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project..
        /// </summary>
        internal static string ProjectNotRunnableDirectly {
            get {
                return ResourceManager.GetString("ProjectNotRunnableDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming the code element &apos;{0}&apos; failed..
        /// </summary>
        internal static string RenameSymbolFailed {
            get {
                return ResourceManager.GetString("RenameSymbolFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are renaming a file. Would you also like to perform a rename in this project of all references to the code element &apos;{0}&apos;?.
        /// </summary>
        internal static string RenameSymbolPrompt {
            get {
                return ResourceManager.GetString("RenameSymbolPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming Type.
        /// </summary>
        internal static string Renaming_Type {
            get {
                return ResourceManager.GetString("Renaming_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming Type from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string Renaming_Type_from_0_to_1 {
            get {
                return ResourceManager.GetString("Renaming_Type_from_0_to_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not set).
        /// </summary>
        internal static string StartupObjectNotSet {
            get {
                return ResourceManager.GetString("StartupObjectNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust namespaces for moved files?.
        /// </summary>
        internal static string UpdateNamespacePromptMessage {
            get {
                return ResourceManager.GetString("UpdateNamespacePromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Control (Windows Forms) Designer.
        /// </summary>
        internal static string UserControlEditor_DisplayName {
            get {
                return ResourceManager.GetString("UserControlEditor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form (Windows Forms) Designer.
        /// </summary>
        internal static string WindowsFormEditor_DisplayName {
            get {
                return ResourceManager.GetString("WindowsFormEditor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The working directory &apos;{0}&apos; specified in the &apos;{1}&apos; debug profile does not exist..
        /// </summary>
        internal static string WorkingDirecotryInvalid {
            get {
                return ResourceManager.GetString("WorkingDirecotryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the expected root element &quot;{0}&quot; in the application definition file..
        /// </summary>
        internal static string WPFApp_Xaml_CouldntFindRootElement_1 {
            get {
                return ResourceManager.GetString("WPFApp_Xaml_CouldntFindRootElement_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .xaml file was in an unexpected format, near line {0} column {1}..
        /// </summary>
        internal static string WPFApp_Xaml_UnexpectedFormat_2 {
            get {
                return ResourceManager.GetString("WPFApp_Xaml_UnexpectedFormat_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xproj project files are no longer supported. For details on migrating to csproj see https://docs.microsoft.com/dotnet/core/migration/..
        /// </summary>
        internal static string XprojNotSupported {
            get {
                return ResourceManager.GetString("XprojNotSupported", resourceCulture);
            }
        }
    }
}
