//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.VSResources", typeof(VSResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any active launch profiles configured for this project..
        /// </summary>
        internal static string ActiveLaunchProfileNotFound {
            get {
                return ResourceManager.GetString("ActiveLaunchProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component (Windows Forms) Designer.
        /// </summary>
        internal static string ComponentEditor_DisplayName {
            get {
                return ResourceManager.GetString("ComponentEditor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug executable &apos;{0}&apos; specified in the &apos;{1}&apos; debug profile does not exist..
        /// </summary>
        internal static string DebugExecutableNotFound {
            get {
                return ResourceManager.GetString("DebugExecutableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework ({0}).
        /// </summary>
        internal static string DebugFrameworkMenuText {
            get {
                return ResourceManager.GetString("DebugFrameworkMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic.
        /// </summary>
        internal static string DiagnosticBrowseObjectClassName {
            get {
                return ResourceManager.GetString("DiagnosticBrowseObjectClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnostic&apos;s identifying code..
        /// </summary>
        internal static string DiagnosticCodeDescription {
            get {
                return ResourceManager.GetString("DiagnosticCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string DiagnosticCodeDisplayName {
            get {
                return ResourceManager.GetString("DiagnosticCodeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnostic&apos;s level..
        /// </summary>
        internal static string DiagnosticLevelDescription {
            get {
                return ResourceManager.GetString("DiagnosticLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string DiagnosticLevelDisplayName {
            get {
                return ResourceManager.GetString("DiagnosticLevelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the package or project this diagnostic applies to..
        /// </summary>
        internal static string DiagnosticLibraryNameDescription {
            get {
                return ResourceManager.GetString("DiagnosticLibraryNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string DiagnosticLibraryNameDisplayName {
            get {
                return ResourceManager.GetString("DiagnosticLibraryNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnostic&apos;s descriptive message..
        /// </summary>
        internal static string DiagnosticMessageDescription {
            get {
                return ResourceManager.GetString("DiagnosticMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string DiagnosticMessageDisplayName {
            get {
                return ResourceManager.GetString("DiagnosticMessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnostic&apos;s warning level. Only applies to warnings..
        /// </summary>
        internal static string DiagnosticWarningLevelDescription {
            get {
                return ResourceManager.GetString("DiagnosticWarningLevelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Level.
        /// </summary>
        internal static string DiagnosticWarningLevelDisplayName {
            get {
                return ResourceManager.GetString("DiagnosticWarningLevelDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project doesn&apos;t know how to run the profile {0}..
        /// </summary>
        internal static string DontKnowHowToRunProfile {
            get {
                return ResourceManager.GetString("DontKnowHowToRunProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show again.
        /// </summary>
        internal static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        internal static string EditProjectFileCommand {
            get {
                return ResourceManager.GetString("EditProjectFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error in the launch settings file needs to be corrected before you can run the &apos;{0}&apos; project . Please see the error list for details..
        /// </summary>
        internal static string ErrorInProfilesFile {
            get {
                return ResourceManager.GetString("ErrorInProfilesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error in the launch settings file needs to be corrected before you can run the &apos;{0}&apos; project. {1}. Please see the error list for details..
        /// </summary>
        internal static string ErrorInProfilesFile2 {
            get {
                return ResourceManager.GetString("ErrorInProfilesFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Import comes fom target file. This import cannot be removed..
        /// </summary>
        internal static string ImportsFromTargetCannotBeDeleted {
            get {
                return ResourceManager.GetString("ImportsFromTargetCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing of multiple target framework is not supported..
        /// </summary>
        internal static string MultiTFEditNotSupported {
            get {
                return ResourceManager.GetString("MultiTFEditNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug profile &apos;{0}&apos; is missing the path to the executable to debug..
        /// </summary>
        internal static string NoDebugExecutableSpecified {
            get {
                return ResourceManager.GetString("NoDebugExecutableSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to find migrated cpsroj in {0}, but did not find any..
        /// </summary>
        internal static string NoMigratedCSProjFound {
            get {
                return ResourceManager.GetString("NoMigratedCSProjFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to run your project. The &quot;RunCommand&quot; property is not defined..
        /// </summary>
        internal static string NoRunCommandSpecifiedInProject {
            get {
                return ResourceManager.GetString("NoRunCommandSpecifiedInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects targeting .NET Core {0}.{1} or newer are not supported by this version of Visual Studio..
        /// </summary>
        internal static string NotSupportedDotNetCoreProject {
            get {
                return ResourceManager.GetString("NotSupportedDotNetCoreProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string OutputWindowPaneTitle {
            get {
                return ResourceManager.GetString("OutputWindowPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string PackageAssemblyBrowseObjectClassName {
            get {
                return ResourceManager.GetString("PackageAssemblyBrowseObjectClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly&apos;s name..
        /// </summary>
        internal static string PackageAssemblyNameDescription {
            get {
                return ResourceManager.GetString("PackageAssemblyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PackageAssemblyNameDisplayName {
            get {
                return ResourceManager.GetString("PackageAssemblyNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly&apos;s path..
        /// </summary>
        internal static string PackageAssemblyPathDescription {
            get {
                return ResourceManager.GetString("PackageAssemblyPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PackageAssemblyPathDisplayName {
            get {
                return ResourceManager.GetString("PackageAssemblyPathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile Time Assemblies.
        /// </summary>
        internal static string PackageCompileTimeAssemblyGroupName {
            get {
                return ResourceManager.GetString("PackageCompileTimeAssemblyGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content File.
        /// </summary>
        internal static string PackageContentFileBrowseObjectClassName {
            get {
                return ResourceManager.GetString("PackageContentFileBrowseObjectClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content file&apos;s build action..
        /// </summary>
        internal static string PackageContentFileBuildActionDescription {
            get {
                return ResourceManager.GetString("PackageContentFileBuildActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Action.
        /// </summary>
        internal static string PackageContentFileBuildActionDisplayName {
            get {
                return ResourceManager.GetString("PackageContentFileBuildActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls whether this file should be included in the referencing project based on that project&apos;s language..
        /// </summary>
        internal static string PackageContentFileCodeLanguageDescription {
            get {
                return ResourceManager.GetString("PackageContentFileCodeLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Language.
        /// </summary>
        internal static string PackageContentFileCodeLanguageDisplayName {
            get {
                return ResourceManager.GetString("PackageContentFileCodeLanguageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the content file is copied to the output directory during build..
        /// </summary>
        internal static string PackageContentFileCopyToOutputDescription {
            get {
                return ResourceManager.GetString("PackageContentFileCopyToOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to Output.
        /// </summary>
        internal static string PackageContentFileCopyToOutputDisplayName {
            get {
                return ResourceManager.GetString("PackageContentFileCopyToOutputDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content file&apos;s output path..
        /// </summary>
        internal static string PackageContentFileOutputPathDescription {
            get {
                return ResourceManager.GetString("PackageContentFileOutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path.
        /// </summary>
        internal static string PackageContentFileOutputPathDisplayName {
            get {
                return ResourceManager.GetString("PackageContentFileOutputPathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content file&apos;s path..
        /// </summary>
        internal static string PackageContentFilePathDescription {
            get {
                return ResourceManager.GetString("PackageContentFilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PackageContentFilePathDisplayName {
            get {
                return ResourceManager.GetString("PackageContentFilePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content file&apos;s preprocessed output path..
        /// </summary>
        internal static string PackageContentFilePPOutputPathDescription {
            get {
                return ResourceManager.GetString("PackageContentFilePPOutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preprocessed Output Path.
        /// </summary>
        internal static string PackageContentFilePPOutputPathDisplayName {
            get {
                return ResourceManager.GetString("PackageContentFilePPOutputPathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Files.
        /// </summary>
        internal static string PackageContentFilesGroupName {
            get {
                return ResourceManager.GetString("PackageContentFilesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Assemblies.
        /// </summary>
        internal static string PackageFrameworkAssemblyGroupName {
            get {
                return ResourceManager.GetString("PackageFrameworkAssemblyGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Reference.
        /// </summary>
        internal static string PackageReferenceBrowseObjectClassName {
            get {
                return ResourceManager.GetString("PackageReferenceBrowseObjectClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package&apos;s name..
        /// </summary>
        internal static string PackageReferenceNameDescription {
            get {
                return ResourceManager.GetString("PackageReferenceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PackageReferenceNameDisplayName {
            get {
                return ResourceManager.GetString("PackageReferenceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package&apos;s resolved full path..
        /// </summary>
        internal static string PackageReferencePathDescription {
            get {
                return ResourceManager.GetString("PackageReferencePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PackageReferencePathDisplayName {
            get {
                return ResourceManager.GetString("PackageReferencePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package&apos;s version..
        /// </summary>
        internal static string PackageReferenceVersionDescription {
            get {
                return ResourceManager.GetString("PackageReferenceVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string PackageReferenceVersionDisplayName {
            get {
                return ResourceManager.GetString("PackageReferenceVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pack.
        /// </summary>
        internal static string PackCommand {
            get {
                return ResourceManager.GetString("PackCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pack {0}.
        /// </summary>
        internal static string PackSelectedProjectCommand {
            get {
                return ResourceManager.GetString("PackSelectedProjectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of Visual Studio is recommended for projects targeting .NET Core {0}.{1}..
        /// </summary>
        internal static string PartialSupportedDotNetCoreProject {
            get {
                return ResourceManager.GetString("PartialSupportedDotNetCoreProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with an Output Type of Class Library cannot be started directly.
        ///
        ///In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project..
        /// </summary>
        internal static string ProjectNotRunnableDirectly {
            get {
                return ResourceManager.GetString("ProjectNotRunnableDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Reference.
        /// </summary>
        internal static string ProjectReferenceBrowseObjectClassName {
            get {
                return ResourceManager.GetString("ProjectReferenceBrowseObjectClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project&apos;s name..
        /// </summary>
        internal static string ProjectReferenceNameDescription {
            get {
                return ResourceManager.GetString("ProjectReferenceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ProjectReferenceNameDisplayName {
            get {
                return ResourceManager.GetString("ProjectReferenceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming the code element &apos;{0}&apos; failed..
        /// </summary>
        internal static string RenameSymbolFailed {
            get {
                return ResourceManager.GetString("RenameSymbolFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are renaming a file. Would you also like to perform a rename in this project of all references to the code element &apos;{0}&apos;?.
        /// </summary>
        internal static string RenameSymbolPrompt {
            get {
                return ResourceManager.GetString("RenameSymbolPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming Type.
        /// </summary>
        internal static string Renaming_Type {
            get {
                return ResourceManager.GetString("Renaming_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming Type from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string Renaming_Type_from_0_to_1 {
            get {
                return ResourceManager.GetString("Renaming_Type_from_0_to_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata on &apos;DotNetCliToolReference&apos; item &apos;{0}&apos; is inconsistent between target frameworks. Only the first one will be restored..
        /// </summary>
        internal static string Restore_DuplicateToolReferenceItems {
            get {
                return ResourceManager.GetString("Restore_DuplicateToolReferenceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;TargetFrameworkMoniker&apos; and &apos;NuGetTargetMoniker&apos; properties in the &apos;{0}&apos; configuration are both empty. This configuration will not contribute to NuGet restore, which may result in restore and build errors..
        /// </summary>
        internal static string Restore_EmptyTargetFrameworkMoniker {
            get {
                return ResourceManager.GetString("Restore_EmptyTargetFrameworkMoniker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the &apos;{0}&apos; property is inconsistent between target frameworks. This property must be identical for NuGet restore to function correctly. The value &apos;{1}&apos; from the &apos;{2}&apos; configuration will be used, other target frameworks may fail to pick NuGet assets..
        /// </summary>
        internal static string Restore_PropertyWithInconsistentValues {
            get {
                return ResourceManager.GetString("Restore_PropertyWithInconsistentValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Control (Windows Forms) Designer.
        /// </summary>
        internal static string UserControlEditor_DisplayName {
            get {
                return ResourceManager.GetString("UserControlEditor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form (Windows Forms) Designer.
        /// </summary>
        internal static string WindowsFormEditor_DisplayName {
            get {
                return ResourceManager.GetString("WindowsFormEditor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The working directory &apos;{0}&apos; specified in the &apos;{1}&apos; debug profile does not exist..
        /// </summary>
        internal static string WorkingDirecotryInvalid {
            get {
                return ResourceManager.GetString("WorkingDirecotryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xproj project files are no longer supported. For details on migrating to csproj see https://docs.microsoft.com/en-us/dotnet/core/migration/..
        /// </summary>
        internal static string XprojNotSupported {
            get {
                return ResourceManager.GetString("XprojNotSupported", resourceCulture);
            }
        }
    }
}
