//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VSResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.VSResources", typeof(VSResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzers.
        /// </summary>
        internal static string AnalyzersNodeName {
            get {
                return ResourceManager.GetString("AnalyzersNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        internal static string AssembliesNodeName {
            get {
                return ResourceManager.GetString("AssembliesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any active launch profiles configured for this project..
        /// </summary>
        internal static string ActiveLaunchProfileNotFound {
            get {
                return ResourceManager.GetString("ActiveLaunchProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string ClassTemplateName {
            get {
                return ResourceManager.GetString("ClassTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM.
        /// </summary>
        internal static string ComNodeName {
            get {
                return ResourceManager.GetString("ComNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project &apos;{0}&apos; has been modified outside the environment, and there are unsaved changes to the project.
        ///
        ///Press Save As to save the unsaved changes and load the updated project from disk.
        ///Press Discard to discard the unsaved changes and load the updated project from disk.
        ///Press Overwrite to overwrite the external changes with your changes.
        ///Press Ignore to ignore the external changes. Your changes may be lost if you close and reopen the project.
        ///    .
        /// </summary>
        internal static string ConflictingModificationsPrompt {
            get {
                return ResourceManager.GetString("ConflictingModificationsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting Project Modification Detected.
        /// </summary>
        internal static string ConflictingProjectModificationTitle {
            get {
                return ResourceManager.GetString("ConflictingProjectModificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Loading...).
        /// </summary>
        internal static string DependenciesLoadingPostfix {
            get {
                return ResourceManager.GetString("DependenciesLoadingPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Errors - see Error List).
        /// </summary>
        internal static string DependenciesNodeErrorsSuffix {
            get {
                return ResourceManager.GetString("DependenciesNodeErrorsSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string DependenciesNodeName {
            get {
                return ResourceManager.GetString("DependenciesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug executable &apos;{0}&apos; specified in the &apos;{1}&apos; debug profile does not exist..
        /// </summary>
        internal static string DebugExecutableNotFound {
            get {
                return ResourceManager.GetString("DebugExecutableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Discard.
        /// </summary>
        internal static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project doesn&apos;t know how to run the profile {0}..
        /// </summary>
        internal static string DontKnowHowToRunProfile {
            get {
                return ResourceManager.GetString("DontKnowHowToRunProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error in the launch settings file needs to be corrected before you can run the &apos;{0}&apos; project . Please see the error list for details..
        /// </summary>
        internal static string ErrorInProfilesFile {
            get {
                return ResourceManager.GetString("ErrorInProfilesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error in the launch settings file needs to be corrected before you can run the &apos;{0}&apos; project. {1}. Please see the error list for details..
        /// </summary>
        internal static string ErrorInProfilesFile2 {
            get {
                return ResourceManager.GetString("ErrorInProfilesFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred attempting to watch project file &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToWatchProject {
            get {
                return ResourceManager.GetString("FailedToWatchProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Assemblies.
        /// </summary>
        internal static string FrameworkAssembliesNodeName {
            get {
                return ResourceManager.GetString("FrameworkAssembliesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency.
        /// </summary>
        internal static string GraphNodeCategoryDependency {
            get {
                return ResourceManager.GetString("GraphNodeCategoryDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ignore.
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore A_ll.
        /// </summary>
        internal static string IgnoreAll {
            get {
                return ResourceManager.GetString("IgnoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to find item type for rule {0}. The rule file is either missing or malformed..
        /// </summary>
        internal static string NoItemTypeForRule {
            get {
                return ResourceManager.GetString("NoItemTypeForRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet.
        /// </summary>
        internal static string NuGetPackagesNodeName {
            get {
                return ResourceManager.GetString("NuGetPackagesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug profile &apos;{0}&apos; has requested a web browser be launched, but the URL specified is not a valid absolute URL.  {1}.
        /// </summary>
        internal static string InvalidAbsoluteUrlSpecified {
            get {
                return ResourceManager.GetString("InvalidAbsoluteUrlSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug profile &apos;{0}&apos; is missing the path to the executable to debug..
        /// </summary>
        internal static string NoDebugExecutableSpecified {
            get {
                return ResourceManager.GetString("NoDebugExecutableSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The debug profile &apos;{0}&apos; has requested a web browser be launched, but a URL was not specified..
        /// </summary>
        internal static string NoUrlSpecified {
            get {
                return ResourceManager.GetString("NoUrlSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Overwrite.
        /// </summary>
        internal static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Modification Detected.
        /// </summary>
        internal static string ProjectModificationDlgTitle {
            get {
                return ResourceManager.GetString("ProjectModificationDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project &apos;{0}&apos; has been modified outside the environment.
        ///
        ///Press Reload to load the updated project from disk.
        ///Press Ignore to ignore the external changes. The changes will be used the next time you open the project.
        ///    .
        /// </summary>
        internal static string ProjectModificationsPrompt {
            get {
                return ResourceManager.GetString("ProjectModificationsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string ProjectsNodeName {
            get {
                return ResourceManager.GetString("ProjectsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with an Output Type of Class Library cannot be started directly.
        ///
        ///In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project..
        /// </summary>
        internal static string ProjectNotRunnableDirectly {
            get {
                return ResourceManager.GetString("ProjectNotRunnableDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload A_ll.
        /// </summary>
        internal static string ReloadAll {
            get {
                return ResourceManager.GetString("ReloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming the code element {0} failed..
        /// </summary>
        internal static string RenameSymbolFailed {
            get {
                return ResourceManager.GetString("RenameSymbolFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are renaming a file. Would you also like to perform a rename in this project of all references to the code element {0}?.
        /// </summary>
        internal static string RenameSymbolPrompt {
            get {
                return ResourceManager.GetString("RenameSymbolPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save As.
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK.
        /// </summary>
        internal static string SdkNodeName {
            get {
                return ResourceManager.GetString("SdkNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The working directory &apos;{0}&apos; specified in the &apos;{1}&apos; debug profile does not exist..
        /// </summary>
        internal static string WorkingDirecotryInvalid {
            get {
                return ResourceManager.GetString("WorkingDirecotryInvalid", resourceCulture);
            }
        }
    }
}
