//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.ProjectSystem.VS.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.ProjectSystem.VS.Web.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the path to the applicationhost.config file..
        /// </summary>
        internal static string CantGetApplcationHostConfigFile {
            get {
                return ResourceManager.GetString("CantGetApplcationHostConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A web browser has not been selected in the Browse With dialog..
        /// </summary>
        internal static string NeedToSelectANonInternalBrowser {
            get {
                return ResourceManager.GetString("NeedToSelectANonInternalBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server URLs have been configured for the project..
        /// </summary>
        internal static string NoServerURLsConfigured {
            get {
                return ResourceManager.GetString("NoServerURLsConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create the Web site &apos;{0}&apos;. You must run Visual Studio in the context of an administrator account to create IIS Express sites with ports less than 1024..
        /// </summary>
        internal static string Project_AdminReqToCreateSiteWithPort {
            get {
                return ResourceManager.GetString("Project_AdminReqToCreateSiteWithPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET {0} has not been registered on the Web server. You need to manually configure your Web server for ASP.NET {0} in order for your site to run correctly..
        /// </summary>
        internal static string Project_AspNetNotRegistered {
            get {
                return ResourceManager.GetString("Project_AspNetNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =The Web project &apos;{1}&apos; is currently configured to use the URL &apos;{0}&apos;. The Web server has this URL mapped to a different folder &apos;{2}&apos;..
        /// </summary>
        internal static string Project_E_VDirAlreadyMapped {
            get {
                return ResourceManager.GetString("Project_E_VDirAlreadyMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL &apos;{0}&apos; is already mapped to a different folder &apos;{1}&apos;..
        /// </summary>
        internal static string Project_ErrAlreadyHostedOnDifferentFolder {
            get {
                return ResourceManager.GetString("Project_ErrAlreadyHostedOnDifferentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the virtual directory {0} failed with the error: {1}. You will need to manually create this virtual directory in IIS before you can open this project.
        ///    .
        /// </summary>
        internal static string Project_ErrCreatingVDIROnOpen {
            get {
                return ResourceManager.GetString("Project_ErrCreatingVDIROnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Web Application Project {0} is configured to use IIS.
        ///
        ///{1}.
        /// </summary>
        internal static string Project_IIS_Required {
            get {
                return ResourceManager.GetString("Project_IIS_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project (&apos;{0}&apos;) is configured to use IIS, but IIS is not installed on this computer. To open this project, you must first install IIS or convert the project to use IIS Express..
        /// </summary>
        internal static string Project_IISNotInstalled {
            get {
                return ResourceManager.GetString("Project_IISNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS Express applicationHost.config file contains invalid entries and must be corrected before you can use it.
        ///    
        ///{0}.
        /// </summary>
        internal static string Project_InvalidAppHost_ConvertToIISX {
            get {
                return ResourceManager.GetString("Project_InvalidAppHost_ConvertToIISX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS configuration data contains invalid entries and must be corrected.
        ///    
        ///{0}.
        /// </summary>
        internal static string Project_InvalidAppHost_IIS {
            get {
                return ResourceManager.GetString("Project_InvalidAppHost_IIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS configuration data contains invalid entries and must be corrected before you can open project {0}.
        /// 
        ///{1}.
        /// </summary>
        internal static string Project_InvalidAppHost_IIS_Open {
            get {
                return ResourceManager.GetString("Project_InvalidAppHost_IIS_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS Express applicationHost.config file contains invalid entries and must be corrected.
        ///    
        ///{0}.
        /// </summary>
        internal static string Project_InvalidAppHost_IISX {
            get {
                return ResourceManager.GetString("Project_InvalidAppHost_IISX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS Express applicationHost.config file contains invalid entries and must be corrected before you can open project {0}.
        ///  
        ///{1}.
        /// </summary>
        internal static string Project_InvalidAppHost_IISX_Open {
            get {
                return ResourceManager.GetString("Project_InvalidAppHost_IISX_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local IIS server URL &apos;{0}&apos; is not a valid URL that includes the protocol (http:// or https://). {1}.
        /// </summary>
        internal static string Project_InvalidIISUrl1 {
            get {
                return ResourceManager.GetString("Project_InvalidIISUrl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create the Web site &apos;{0}&apos;. You must specify &quot;localhost&quot; for the server name.
        /// </summary>
        internal static string Project_LocalUrlRequiredToCreateSite {
            get {
                return ResourceManager.GetString("Project_LocalUrlRequiredToCreateSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components required to work with web servwers are not available. Make sure the Web workload is installed..
        /// </summary>
        internal static string Project_MissingComponents {
            get {
                return ResourceManager.GetString("Project_MissingComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project {0} needs to specify an IIS Express Url..
        /// </summary>
        internal static string Project_MustSpecifyIISExpressUrl {
            get {
                return ResourceManager.GetString("Project_MustSpecifyIISExpressUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASPThe Web {0} is currently configured for use with ASP.NET {1}. Web project {2} is targeting ASP.NET {3}; if not configured some features may make incorrect assumptions, and pages designed with the tool may not render correctly.\n\nWould you like the site to be configured for use with ASP.NET {3}?.
        /// </summary>
        internal static string Project_P_FixScriptMaps {
            get {
                return ResourceManager.GetString("Project_P_FixScriptMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Web project &apos;{1}&apos; is currently configured to use the URL &apos;{0}&apos;. The Web server has this URL mapped to a different folder &apos;{2}&apos;. Would you like to remap this URL to point to this Web project&apos;s folder?.
        /// </summary>
        internal static string Project_P_ReMapVDir_Path {
            get {
                return ResourceManager.GetString("Project_P_ReMapVDir_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL &apos;{0}&apos; is mapped to a different folder &apos;{1}&apos;. Would you like to remap this URL to point to this Web project&apos;s folder?.
        /// </summary>
        internal static string Project_P_ReMapVDir_Path2 {
            get {
                return ResourceManager.GetString("Project_P_ReMapVDir_Path2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project {0} has been configured to run the 64 bit version of IIS Express which is not available on this 32 bit operating system. If the project does not require the 64 bit version of IIS Express, change this option on the project&apos;s &apos;Web&apos; property page..
        /// </summary>
        internal static string Project_Requires64BitOS {
            get {
                return ResourceManager.GetString("Project_Requires64BitOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Web {0} for ASP.NET {1} failed. You must manually configure this site for ASP.NET {1} in order for the site to run correctly. {2}.
        /// </summary>
        internal static string Project_ScriptmapFailure {
            get {
                return ResourceManager.GetString("Project_ScriptmapFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get a web server for the project &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToGetIISExpressWebServer {
            get {
                return ResourceManager.GetString("UnableToGetIISExpressWebServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch the IIS Express Web server.
        ///
        ///{0}.
        /// </summary>
        internal static string UnableToLaunchIISExpress {
            get {
                return ResourceManager.GetString("UnableToLaunchIISExpress", resourceCulture);
            }
        }
    }
}
