' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

' This file is used by Code Analysis to maintain SuppressMessage 
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given 
' a specific target and scoped to a namespace, type, member, etc.

' Baselined for the port, we should revisit these, see: https://github.com/dotnet/roslyn/issues/8183.
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.Common.DTEUtils.ApplyListViewThemeStyles(System.IntPtr)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.Common.DTEUtils.ApplyTreeViewThemeStyles(System.IntPtr)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.Common.Utils.FocusFirstOrLastTabItem(System.IntPtr,System.Boolean)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.DeferrableWindowPaneProviderServiceBase.DesignerWindowPaneBase.OnUndoing(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.DeferrableWindowPaneProviderServiceBase.DesignerWindowPaneBase.OnUndone(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.DesignerToolbarPanel.WndProc(System.Windows.Forms.Message@)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.DesignerTypeDiscoveryService.GetProjectOutputs(System.IServiceProvider,Microsoft.VisualStudio.Shell.Interop.IVsHierarchy)~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.GenericComponentSerializationStore.SerializedObjectData.SerializeObject(System.Object)~System.Byte[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.MyApplication.MyApplicationProperties.FilesToCheckOut(System.Boolean)~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ApplicationPropPageVBWinForms.GetFormEntryPoints(System.Boolean)~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.CompilePropPage2.EnsureNotConflictingSettings(System.Object,System.Windows.Forms.DataGridViewCellCancelEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.CompilePropPage2.RemoveItems(System.Int32[],System.Int32[])~System.Int32[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.CompilePropPage2.UpdatePropertiesFromCurrentState")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.DelayPostingMessage(System.Object)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.GetCurrentImportsList(VSLangProj.Imports)~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.GetReferencedNamespaceList~System.Collections.Generic.IList{System.String}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.ImportList_ItemCheck(System.Object,System.Windows.Forms.ItemCheckEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.PostRefreshImportListMessage")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.PostRefreshReferenceListMessage")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.PostRefreshServiceReferenceListMessage")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.SetReferenceListColumnWidths(System.Windows.Forms.Control@,System.Windows.Forms.ListView@,System.Int32)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.UserPropertyDescriptor.#ctor(System.String,System.Type)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.Category.#ctor(System.String,System.String,Microsoft.VisualStudio.Editors.ResourceEditor.Category.Display,System.ComponentModel.Design.MenuCommand,System.EventHandler,Microsoft.VisualStudio.Editors.ResourceEditor.ResourceTypeEditor[])")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.AddOrUpdateResourcesFromFiles(System.String[],System.Boolean,System.Boolean,System.Boolean,System.Boolean)~Microsoft.VisualStudio.Editors.ResourceEditor.Resource[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.GetSelectedResources~Microsoft.VisualStudio.Editors.ResourceEditor.Resource[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.HandleViewHelperCommandExec(System.Guid,System.UInt32,System.Boolean@)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.PropertyGridUnselectAll")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.PropertyGridUpdate")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceListView.BeginLabelEdit(Microsoft.VisualStudio.Editors.ResourceEditor.Resource)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceListView.ClearColumnSortImage(System.Int32)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceListView.SetColumnSortImage(System.Int32,System.Boolean)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceStringTable.GetSelectedResources~Microsoft.VisualStudio.Editors.ResourceEditor.Resource[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.DesignTimeSettingInstance.DesignTimeSettingInstanceCustomPropertyDescriptorBase.#ctor(Microsoft.VisualStudio.Editors.SettingsDesigner.DesignTimeSettingInstance,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.DesignTimeSettingInstance.GetEvents~System.ComponentModel.EventDescriptorCollection")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGeneratorBase.AddMyModule(System.CodeDom.CodeCompileUnit,System.String,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.TypeEditorHostControl.DropDownControl(System.Windows.Forms.Control)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsGlobalObjects.SettingsFileGlobalObject.BuildType~System.Type")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsGlobalObjects.SettingsFileGlobalObject.CreateInstance~System.Object")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0003:Do not directly await a Task", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.XmlIntellisense.XmlIntellisenseSchemas.CompileCallBack(Microsoft.VisualStudio.Editors.XmlIntellisense.XmlIntellisenseSchemasData)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.DesignerFramework.GenericComponentSerializationStore.Errors")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.ApplicationPropPage.ControlData")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.ApplicationPropPageVBBase.ApplicationTypeInfo.References")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceSerializationService.ResourceSerializationStore.Errors")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0009:Override Object.Equals(object) when implementing IEquatable<T> ", Justification:="<Pending>", Scope:="type", Target:="~T:Microsoft.VisualStudio.Editors.PropertyPages.ImportIdentity")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.Runtime.Hosting.StrongNameHelpers.StrongNameFreeBuffer(System.IntPtr)")>
' BUG: https://github.com/dotnet/roslyn/issues/15343
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.XmlToSchema.InputXmlForm._addAsTextButton_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.XmlToSchema.InputXmlForm._addFromFileButton_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.XmlToSchema.InputXmlForm._addFromWebButton_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.XmlToSchema.InputXmlForm._listViewKeyPress(System.Object,System.Windows.Forms.KeyEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.XmlToSchema.InputXmlForm._okButtonClick(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyApplication.MyApplicationProperties._myAppDocData")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.MyExtensibilityProjectService._projectSettings")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.Package.EditorToolsOptionsPage._dialog")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.ApplicationPropPageVBWinForms._myApplicationPropertiesNotifyPropertyChanged")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage._projectService")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage._projectItemEvents")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.WPF.ApplicationPropPageVBWPF._applicationXamlDocData")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.WPF.ApplicationPropPageVBWPF._pageErrorControl")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.FileWatcher.DirectoryWatcher._fileSystemWatcher")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.FileWatcher.FileWatcherEntry._timer")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorRootDesigner._buildEvents")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorRootDesigner._designerHost")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorRootDesigner._undoEngine")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView._categoryAudio")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView._categoryFiles")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView._categoryIcons")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView._categoryImages")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView._categoryOther")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView._categoryStrings")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView._resourceListView")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceFile._componentChangeService")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerLoader._buildEvents")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.TypeEditorHostControl._previewPanel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.TypeEditorHostControl._showEditorButton")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.TypeEditorHostControl._valueComboBox")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.TypeEditorHostControl._valueTextBox")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.BaseDesignerLoader.m_WindowEvents_WindowActivated(EnvDTE.Window,EnvDTE.Window)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.buttonOK_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.listViewExtensions_ColumnClick(System.Object,System.Windows.Forms.ColumnClickEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.listViewExtensions_DoubleClick(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.listViewExtensions_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.MyExtensibility.AssemblyOptionDialog.buttonYes_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.MyExtensibility.MyExtensibilityProjectService.m_ProjectSettings_ExtensionChanged")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.Package.EditorToolsOptionsPanel.indentSizeTextBox_TextChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.Package.EditorToolsOptionsPanel.tabSizeTextBox_TextChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ApplicationPropPage.iconTableLayoutPanel_Paint(System.Object,System.Windows.Forms.PaintEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.BuildPropPage.chkDefineDebug_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.BuildPropPage.chkDefineTrace_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.BuildPropPage.rbStartAction_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.DebugPropPage.rbStartAction_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.buttonAdd_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.buttonRemove_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.linklabelHelp_LinkClicked(System.Object,System.Windows.Forms.LinkLabelLinkClickedEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.listViewExtensions_AddExtension(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.listViewExtensions_ColumnClick(System.Object,System.Windows.Forms.ColumnClickEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.listViewExtensions_RemoveExtension(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.listViewExtensions_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.m_ProjectService_ExtensionChanged")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.addContextMenuStrip_Opening(System.Object,System.ComponentModel.CancelEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.referenceToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.serviceReferenceToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.webReferenceToolStripMenuItem_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.UnusedReferencePropPage.dialog_Close(System.Object,System.Windows.Forms.FormClosedEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.UnusedReferencePropPage.dialog_Shown(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_CellBeginEdit(System.Object,System.Windows.Forms.DataGridViewCellCancelEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_CellFormatting(System.Object,System.Windows.Forms.DataGridViewCellFormattingEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_CellStateChanged(System.Object,System.Windows.Forms.DataGridViewCellStateChangedEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_CellValidated(System.Object,System.Windows.Forms.DataGridViewCellEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_CellValidating(System.Object,System.Windows.Forms.DataGridViewCellValidatingEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_CurrentCellDirtyStateChanged(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_DefaultValuesNeeded(System.Object,System.Windows.Forms.DataGridViewRowEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_OnCellClickBeginEdit(System.Object,System.ComponentModel.CancelEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_OnDataError(System.Object,System.Windows.Forms.DataGridViewDataErrorEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_OnEditingControlShowing(System.Object,System.Windows.Forms.DataGridViewEditingControlShowingEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_RowStateChanged(System.Object,System.Windows.Forms.DataGridViewRowStateChangedEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_SortCompare(System.Object,System.Windows.Forms.DataGridViewSortCompareEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_UserAddedRow(System.Object,System.Windows.Forms.DataGridViewRowEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_UserDeletedRow(System.Object,System.Windows.Forms.DataGridViewRowEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView_UserDeletingRow(System.Object,System.Windows.Forms.DataGridViewRowCancelEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.TypePickerDialog.m_OkButton_Click(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.DesignerFramework.BaseDesignerLoader.m_DocData")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.DesignerFramework.BaseDesignerLoader.m_WindowEvents")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.buttonCancel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.buttonOK")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.colHeaderExensionDescription")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.colHeaderExtensionName")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.colHeaderExtensionVersion")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.listViewExtensions")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.tableLayoutOKCancelButtons")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AddMyExtensionsDialog.tableLayoutOverarching")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AssemblyOptionDialog.buttonNo")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AssemblyOptionDialog.buttonYes")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AssemblyOptionDialog.checkBoxOption")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AssemblyOptionDialog.labelQuestion")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AssemblyOptionDialog.listBoxItems")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AssemblyOptionDialog.tableLayoutOverarching")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.MyExtensibility.AssemblyOptionDialog.tableLayoutYesNoButtons")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.buttonAdd")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.buttonRemove")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.colHeaderExtensionDescription")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.colHeaderExtensionName")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.colHeaderExtensionVersion")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.labelDescription")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.linkLabelHelp")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.listViewExtensions")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.tableLayoutAddRemoveButtons")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.MyExtensibilityPropPage.tableLayoutOverarching")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.addRemoveButtonsTableLayoutPanel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.addUserImportTableLayoutPanel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.referenceButtonsTableLayoutPanel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.UnusedReferencePropPage.m_HostDialog")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.DialogQueryName.addCancelTableLayoutPanel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.DialogQueryName.overarchingTableLayoutPanel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.OpenFileWarningDialog.alwaysCheckCheckBox")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.OpenFileWarningDialog.buttonCancel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.OpenFileWarningDialog.buttonOK")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.OpenFileWarningDialog.dialogLayoutPanel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.OpenFileWarningDialog.messageLabel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.OpenFileWarningDialog.messageLabel2")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsDesignerView.m_SettingsGridView")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.TypePickerDialog.m_CancelButton")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.TypePickerDialog.m_OkButton")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.TypePickerDialog.okCancelTableLayoutPanel")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.SettingsDesigner.TypePickerDialog.overarchingTableLayoutPanel")>