# Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. See the LICENSE.md file in the project root for more information.

# Name: DotNet-Project-System
# URL: https://dev.azure.com/devdiv/DevDiv/_build?definitionId=9675

# Produces the signed product build for insertion into the Visual Studio.

###################################################################################################################################################################
# PIPELINE METADATA
###################################################################################################################################################################

# Activates the pipeline after a PR is merged.
# See: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines
trigger:
  branches:
    include:
    - main
    - feature/*
  paths:
    exclude:
    - docs/*
    - README.md

schedules:
# Runs the pipelines at 4am and creates a VS insertion PR.
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/schedules-cron?view=azure-pipelines
- cron: '0 4 * * *'
  displayName: Daily 4am Build (with Insertion)
  branches:
    include:
    - main

resources:
  # These DartLab pipelines and repositories are only used by the Optimization stage.
  pipelines:
  # This name is the default value for the 'dartLabBuildResourceName' parameter in single-runsettings.yml.
  - pipeline: DartLab
    project: DevDiv
    source: DartLab
    branch: main
  # This name is the default value for the 'dartLabOptProfBuildResourceName' parameter in single-runsettings.yml.
  - pipeline: DartLab.OptProf
    source: DartLab.OptProf
    branch: main
  repositories:
  # This name is the default value for the 'dartLabTemplatesResourceName 'parameter in single-runsettings.yml.
  - repository: DartLabTemplates
    name: DartLab.Templates
    type: git
    ref: refs/heads/main
  # This name is used to access the single-runsettings.yml template.
  - repository: DartLabOptProfTemplates
    name: DartLab.OptProf
    type: git
    ref: refs/heads/main

variables:
  # The configuration for the build is used throughout the various pipelines as the file paths for output contain the build configuration as a folder name.
  BuildConfiguration: Release
  # https://devdiv.visualstudio.com/DevDiv/_settings/agentqueues?queueId=3123&view=jobs
  DefaultPoolName: VSEngSS-MicroBuild2022-1ES
  # This specific pool is required to access our file share location.
  # https://devdiv.visualstudio.com/DevDiv/_settings/agentqueues?queueId=3316&view=jobs
  SymbolsPoolName: VSEng-ReleasePool-1ES
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#manually-entered-demands
  DefaultDemands: Cmd
  # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_skip_first_time_experience
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_nologo
  DOTNET_NOLOGO: true
  # https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/26284/Enabling-SBOM-For-Your-Component-Insertion-into-VS?anchor=1.-add-the-%27manifest-generator-task%27-to-your-pipeline
  Packaging.EnableSBOMSigning: true
  # Opt out of automatically injecting Codesign Validation into the pipeline. We run Codesign Validation as part of the Compliance pipeline.
  # See: https://aka.ms/gdn-injection
  runCodesignValidationInjection: false

parameters:
- name: CreateInsertion
  displayName: Create VS Insertion PR
  type: boolean
  default: false
- name: InsertionVSBranch
  displayName: Insertion VS Branch Name
  type: string
  default: main
# This should only be enabled when generating optimization data for the first time.
# See details in the Build job for the MicroBuildOptProfPlugin task.
- name: SkipOptimize
  displayName: Do Not Optimize Assemblies
  type: boolean
  default: false

###################################################################################################################################################################
# STAGES
###################################################################################################################################################################

stages:
- stage: Build
  displayName: Build
  variables:
    SkipOptimize: ${{ parameters.SkipOptimize }}
    # Only used for tracking purposes in MicroBuild tasks.
    # See: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/650/MicroBuild-Signing?anchor=high-level-steps-to-enable-signing
    TeamName: DotNet-Project-System
  jobs:
  - template: templates/build-official-release.yml

- stage: Publish
  displayName: Publish
  dependsOn: Build
  jobs:
  - template: templates/publish-assets-and-packages.yml
  - template: templates/publish-symbols.yml
  - template: templates/publish-richnav.yml

- stage: Compliance
  displayName: Compliance
  dependsOn: Build
  jobs:
  - template: templates/analyze-compliance.yml
  # TODO: Temporarily disabling as we're trying to test more things downstream. This takes too much time.
  # - template: templates/analyze-api.yml
  # TODO: Commented out for since I cannot get the build for the analyzer to recognize global namespaces.
  # - template: templates/analyze-vulnerabilities.yml

- stage: Localization
  displayName: Localization
  # [] clears the dependency on the previous stages allowing parallelism.
  dependsOn: []
  variables:
  # Variable group containing the PATs required for running OneLocBuild.
  # See: https://devdiv.visualstudio.com/DevDiv/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=343&path=OneLocBuildVariables
  - group: OneLocBuildVariables
  jobs:
  - template: templates/generate-localization.yml

# This template is provided by the DartLabOptProfTemplates repo, declared in the repositories section (top of this file).
# It is a stage template, defining our entire Optimization stage.
# - template: \templates\stages\visual-studio\single-runsettings.yml@DartLabOptProfTemplates
#   parameters:
#     name: Optimization
#     displayName: Optimization
#     dependsOn:
#     - Publish
#     - Compliance
#     variables:
#     - name: visualStudioBootstrapperURI
#       # If you set this value to the visualStudioBootstrapperURI parameter directly, it does not resolve correctly. Instead, we set it to a variable and pass that variable into the parameter.
#       # For parameter, variable, and expression syntax/usage, see:
#       # - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax
#       # - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops
#       # - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script#how-can-i-use-variables-inside-of-templates
#       # For variables across stages, see:
#       # - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-stage
#       # - https://arunksingh16.medium.com/azure-devops-share-variable-across-stages-9bca85abfe8a
#       # - https://stackoverflow.com/a/57488169/294804
#       # - https://github.com/microsoft/azure-pipelines-tasks/issues/4743
#       value: $[ stageDependencies.Publish.PublishAssetsAndPackages.outputs['UpdateRunSettings.visualStudioBootstrapperURI'] ]
#     runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/RunSettings/$(System.TeamProject)/dotnet/project-system/$(Build.SourceBranchName)/$(Build.BuildId);OptProf.runsettings
#     # This variable is set during the 'Update RunSettings' (UpdateRunSettings.ps1) step in the publish-assets-and-packages.yml.
#     # This variable is expanded when it is used: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#macro-syntax-variables
#     visualStudioBootstrapperURI: $(visualStudioBootstrapperURI)
#     # visualStudioBootstrapperURI: $[ stageDependencies.Publish.PublishAssetsAndPackages.outputs['UpdateRunSettings.visualStudioBootstrapperURI'] ]
#     # visualStudioBootstrapperURI: $[ stageDependencies.Publish.outputs['PublishAssetsAndPackages.UpdateRunSettings.visualStudioBootstrapperURI'] ]
#     # The output of the optimization process. The first half of the path is provided to the DropNamePrefix input in the 'Install OptProf Plugin' (MicroBuildOptProfPlugin) step in build-official-release.yml.
#     optOptimizationInputsDropName: OptimizationInputs/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceVersion)/$(Build.BuildId)/$(System.StageAttempt)
#     testLabPoolName: VS-Platform

- stage: Insertion
  displayName: Insertion
  dependsOn:
  # The Build dependsOn is required for putting that stage's variables into the stageDependencies property bag.
  - Build
  - Publish
  - Compliance
  variables:
    # Gets the PackageVersion variable produced by the Build pipeline.
    # For parameter, variable, and expression syntax/usage, see:
    # - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax
    # - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops
    # - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script#how-can-i-use-variables-inside-of-templates
    # For variables across stages, see:
    # - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#use-outputs-in-a-different-stage
    # - https://arunksingh16.medium.com/azure-devops-share-variable-across-stages-9bca85abfe8a
    # - https://stackoverflow.com/a/57488169/294804
    # - https://github.com/microsoft/azure-pipelines-tasks/issues/4743
    PackageVersion: $[ stageDependencies.Build.BuildOfficialRelease.outputs['SetPackageVersion.PackageVersion'] ]
    CreateInsertion: ${{ parameters.CreateInsertion }}
    InsertionVSBranch: ${{ parameters.InsertionVSBranch }}
  jobs:
  - template: templates/generate-insertion.yml