# Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. See the LICENSE.md file in the project root for more information.

# Name: DotNet-Project-System-PR
# URL: https://dev.azure.com/dnceng-public/public/_build?definitionId=32

# Validates commits as part of GitHub pull requests.

###################################################################################################################################################################
# PIPELINE METADATA
###################################################################################################################################################################

# Activates the pipeline for every commit on a PR.
# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines
pr: ['*']

# Disable CI builds for this pipeline.
# See: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines#examples
trigger: none

pool:
  # The max number of concurrent jobs that can be run in the pool is 820.
  # https://dnceng.visualstudio.com/public/_settings/agentqueues?queueId=396&view=jobs
  name: NetCore-Public
  # Demands Docs: https://docs.microsoft.com/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#manually-entered-demands
  # ImageOverride is used to select the image. See:
  # - https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/510/1ES-Hosted-Pools-Migration
  # - https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/675/1ESManagedPoolsDesign?anchor=1es-managed-images
  # Image List: https://helix.dot.net/#1esPools
  demands: ImageOverride -equals Windows.VS2022Preview.Amd64.Open

variables:
  # https://docs.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_skip_first_time_experience
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # https://docs.microsoft.com/dotnet/core/tools/dotnet-environment-variables#dotnet_nologo
  DOTNET_NOLOGO: true
  # Opt out of automatically injecting Codesign Validation into the pipeline.
  # See: https://aka.ms/gdn-injection
  runCodesignValidationInjection: false
  # Set the minimum visual studio version. This overrides the version in version.json for the build toolset.
  MinVisualStudioVersion: '17.0'

###################################################################################################################################################################
# STAGES
###################################################################################################################################################################

stages:
- stage: Build
  displayName: Build
  jobs:
  - template: templates/build-pull-request.yml
    parameters:
      BuildConfiguration: Debug
      ArtifactName: '$(Build.BuildNumber)-Debug'
      VisualStudioMinimumVersion: $(MinVisualStudioVersion)
  - template: templates/build-pull-request.yml
    parameters:
      BuildConfiguration: Release
      ArtifactName: '$(Build.BuildNumber)'
      VisualStudioMinimumVersion: $(MinVisualStudioVersion)