//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred when reading the launch settings file &apos;{0}&apos;. {1} .
        /// </summary>
        internal static string ErrorReadingLaunchSettings {
            get {
                return ResourceManager.GetString("ErrorReadingLaunchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred when writing to the launch settings file &apos;{0}&apos;. {1} .
        /// </summary>
        internal static string ErrorWritingDebugSettings {
            get {
                return ResourceManager.GetString("ErrorWritingDebugSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors in &apos;{0}&apos; need to be corrected before applying changes..
        /// </summary>
        internal static string JsonErrorNeedToBeCorrected {
            get {
                return ResourceManager.GetString("JsonErrorNeedToBeCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the launch settings file. This error will need to be corrected in order to debug this project. &apos;{0}&apos; .
        /// </summary>
        internal static string JsonErrorReadingLaunchSettings {
            get {
                return ResourceManager.GetString("JsonErrorReadingLaunchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value to remove &apos;{0}&apos; was not present in the property &apos;{1}&apos;.
        /// </summary>
        internal static string MsBuildMissingValueToRemove {
            get {
                return ResourceManager.GetString("MsBuildMissingValueToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value to rename &apos;{0}&apos; was not present in the property &apos;{1}&apos;.
        /// </summary>
        internal static string MsBuildMissingValueToRename {
            get {
                return ResourceManager.GetString("MsBuildMissingValueToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string NoActionProfileName {
            get {
                return ResourceManager.GetString("NoActionProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one launch profile is missing the required name attribute. These profiles will be ignored.
        /// </summary>
        internal static string ProfileMissingName {
            get {
                return ResourceManager.GetString("ProfileMissingName", resourceCulture);
            }
        }
    }
}
