'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://aka.ms/csharp-versions.
        '''</summary>
        Friend Shared ReadOnly Property CantSelectLanguageVersionFWLink() As String
            Get
                Return ResourceManager.GetString("CantSelectLanguageVersionFWLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Visual Studio was unable to determine the Code Access Security (CAS) permissions that are applicable to your project. The most likely cause is that your project references a strongly-named assembly that defines custom permissions, but that is not properly installed in the global assembly cache (GAC). To correct this, try the following:
        ''' 
        '''1. Ensure that any custom permissions defining assemblies referenced by your project have been properly installed to the GAC. If any of these assemblies have been rebuilt [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadingPermissions() As String
            Get
                Return ResourceManager.GetString("ErrorLoadingPermissions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to install the latest Microsoft.CodeAnalysis.FxCopAnalyzers package.
        '''</summary>
        Friend Shared ReadOnly Property FxCopAnalyzersInstallFailedMessage() As String
            Get
                Return ResourceManager.GetString("FxCopAnalyzersInstallFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to uninstall Microsoft.CodeAnalysis.FxCopAnalyzers version &apos;{0}&apos;.
        '''</summary>
        Friend Shared ReadOnly Property FxCopAnalyzersUninstallFailedMessage() As String
            Get
                Return ResourceManager.GetString("FxCopAnalyzersUninstallFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Install other frameworks....
        '''</summary>
        Friend Shared ReadOnly Property InstallOtherFrameworks() As String
            Get
                Return ResourceManager.GetString("InstallOtherFrameworks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://go.microsoft.com/fwlink/?LinkID=287120.
        '''</summary>
        Friend Shared ReadOnly Property InstallOtherFrameworksFWLink() As String
            Get
                Return ResourceManager.GetString("InstallOtherFrameworksFWLink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatically selected based on framework version.
        '''</summary>
        Friend Shared ReadOnly Property LanguageVersionAutomaticallySelected() As String
            Get
                Return ResourceManager.GetString("LanguageVersionAutomaticallySelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to latest.
        '''</summary>
        Friend Shared ReadOnly Property latest() As String
            Get
                Return ResourceManager.GetString("latest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Authentication.
        '''</summary>
        Friend Shared ReadOnly Property NoAuthentication() As String
            Get
                Return ResourceManager.GetString("NoAuthentication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to none.
        '''</summary>
        Friend Shared ReadOnly Property none() As String
            Get
                Return ResourceManager.GetString("none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (not installed).
        '''</summary>
        Friend Shared ReadOnly Property NotInstalledText() As String
            Get
                Return ResourceManager.GetString("NotInstalledText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to preview.
        '''</summary>
        Friend Shared ReadOnly Property preview() As String
            Get
                Return ResourceManager.GetString("preview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restoring Packages....
        '''</summary>
        Friend Shared ReadOnly Property RestoringPackagesMessage() As String
            Get
                Return ResourceManager.GetString("RestoringPackagesMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Windows Authentication.
        '''</summary>
        Friend Shared ReadOnly Property WindowsAuthentication() As String
            Get
                Return ResourceManager.GetString("WindowsAuthentication", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
