//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.ProjectSystem.LogModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.ProjectSystem.LogModel.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad metadata continuation..
        /// </summary>
        internal static string BadMetadataContinuation {
            get {
                return ResourceManager.GetString("BadMetadataContinuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad state..
        /// </summary>
        internal static string BadState {
            get {
                return ResourceManager.GetString("BadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find evaluated project..
        /// </summary>
        internal static string CannotFindEvaluatedProject {
            get {
                return ResourceManager.GetString("CannotFindEvaluatedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find item..
        /// </summary>
        internal static string CannotFindItem {
            get {
                return ResourceManager.GetString("CannotFindItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find project..
        /// </summary>
        internal static string CannotFindProject {
            get {
                return ResourceManager.GetString("CannotFindProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find target..
        /// </summary>
        internal static string CannotFindTarget {
            get {
                return ResourceManager.GetString("CannotFindTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find task..
        /// </summary>
        internal static string CannotFindTask {
            get {
                return ResourceManager.GetString("CannotFindTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double creation of project..
        /// </summary>
        internal static string DoubleCreationOfProject {
            get {
                return ResourceManager.GetString("DoubleCreationOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double evaluation..
        /// </summary>
        internal static string DoubleEvaluation {
            get {
                return ResourceManager.GetString("DoubleEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate target..
        /// </summary>
        internal static string DuplicateTarget {
            get {
                return ResourceManager.GetString("DuplicateTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate task..
        /// </summary>
        internal static string DuplicateTask {
            get {
                return ResourceManager.GetString("DuplicateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected item group name..
        /// </summary>
        internal static string ExpectedItemGroupName {
            get {
                return ResourceManager.GetString("ExpectedItemGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwriting metadata..
        /// </summary>
        internal static string OverwritingMetadata {
            get {
                return ResourceManager.GetString("OverwritingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwriting property..
        /// </summary>
        internal static string OverwritingProperty {
            get {
                return ResourceManager.GetString("OverwritingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected message..
        /// </summary>
        internal static string UnexpectedMessage {
            get {
                return ResourceManager.GetString("UnexpectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected profile format..
        /// </summary>
        internal static string UnexpectedProfile {
            get {
                return ResourceManager.GetString("UnexpectedProfile", resourceCulture);
            }
        }
    }
}
