//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzers.
        /// </summary>
        internal static string AnalyzersNodeName {
            get {
                return ResourceManager.GetString("AnalyzersNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        internal static string AssembliesNodeName {
            get {
                return ResourceManager.GetString("AssembliesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM.
        /// </summary>
        internal static string ComNodeName {
            get {
                return ResourceManager.GetString("ComNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project system data flow &apos;{0}&apos; closed because of an exception: {1}..
        /// </summary>
        internal static string DataFlowFaults {
            get {
                return ResourceManager.GetString("DataFlowFaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string DependenciesNodeName {
            get {
                return ResourceManager.GetString("DependenciesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DiagnosticLevel_Error {
            get {
                return ResourceManager.GetString("DiagnosticLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string DiagnosticLevel_None {
            get {
                return ResourceManager.GetString("DiagnosticLevel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string DiagnosticLevel_Warning {
            get {
                return ResourceManager.GetString("DiagnosticLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Assemblies.
        /// </summary>
        internal static string FrameworkAssembliesNodeName {
            get {
                return ResourceManager.GetString("FrameworkAssembliesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frameworks.
        /// </summary>
        internal static string FrameworkNodeName {
            get {
                return ResourceManager.GetString("FrameworkNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding input reference copy markers:.
        /// </summary>
        internal static string FUTD_AddingInputReferenceCopyMarkers {
            get {
                return ResourceManager.GetString("FUTD_AddingInputReferenceCopyMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding newest import input:.
        /// </summary>
        internal static string FUTD_AddingNewestImportInput {
            get {
                return ResourceManager.GetString("FUTD_AddingNewestImportInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding project file inputs:.
        /// </summary>
        internal static string FUTD_AddingProjectFileInputs {
            get {
                return ResourceManager.GetString("FUTD_AddingProjectFileInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} inputs:.
        /// </summary>
        internal static string FUTD_AddingTypedInputs_1 {
            get {
                return ResourceManager.GetString("FUTD_AddingTypedInputs_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} inputs in Set=&quot;{1}&quot;:.
        /// </summary>
        internal static string FUTD_AddingTypedInputsInSet_2 {
            get {
                return ResourceManager.GetString("FUTD_AddingTypedInputsInSet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} outputs:.
        /// </summary>
        internal static string FUTD_AddingTypedOutputs_1 {
            get {
                return ResourceManager.GetString("FUTD_AddingTypedOutputs_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0} outputs in Set=&quot;{1}&quot;:.
        /// </summary>
        internal static string FUTD_AddingTypedOutputsInSet_2 {
            get {
                return ResourceManager.GetString("FUTD_AddingTypedOutputsInSet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item added &apos;{1}&apos; (CopyToOutputDirectory={2}, TargetPath=&apos;{3}&apos;).
        /// </summary>
        internal static string FUTD_ChangedItemsAddition_4 {
            get {
                return ResourceManager.GetString("FUTD_ChangedItemsAddition_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item removed &apos;{1}&apos; (CopyToOutputDirectory={2}, TargetPath=&apos;{3}&apos;).
        /// </summary>
        internal static string FUTD_ChangedItemsRemoval_4 {
            get {
                return ResourceManager.GetString("FUTD_ChangedItemsRemoval_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking configuration {0}:.
        /// </summary>
        internal static string FUTD_CheckingConfiguration_1 {
            get {
                return ResourceManager.GetString("FUTD_CheckingConfiguration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking copied output (UpToDateCheckBuilt with Original property) file:.
        /// </summary>
        internal static string FUTD_CheckingCopiedOutputFile {
            get {
                return ResourceManager.GetString("FUTD_CheckingCopiedOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination &apos;{0}&apos; does not exist for copy from &apos;{1}&apos;, not up-to-date..
        /// </summary>
        internal static string FUTD_CheckingCopiedOutputFileDestinationNotFound_2 {
            get {
                return ResourceManager.GetString("FUTD_CheckingCopiedOutputFileDestinationNotFound_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source is newer than build output destination, not up-to-date..
        /// </summary>
        internal static string FUTD_CheckingCopiedOutputFileSourceNewer {
            get {
                return ResourceManager.GetString("FUTD_CheckingCopiedOutputFileSourceNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source &apos;{0}&apos; does not exist for copy to &apos;{1}&apos;, not up-to-date..
        /// </summary>
        internal static string FUTD_CheckingCopiedOutputFileSourceNotFound_2 {
            get {
                return ResourceManager.GetString("FUTD_CheckingCopiedOutputFileSourceNotFound_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking {0} item with CopyToOutputDirectory=&quot;{1}&quot; &apos;{2}&apos;:.
        /// </summary>
        internal static string FUTD_CheckingCopyToOutputDirectoryItem_3 {
            get {
                return ResourceManager.GetString("FUTD_CheckingCopyToOutputDirectoryItem_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination &apos;{0}&apos; does not exist, not up-to-date..
        /// </summary>
        internal static string FUTD_CheckingCopyToOutputDirectoryItemDestinationNotFound_1 {
            get {
                return ResourceManager.GetString("FUTD_CheckingCopyToOutputDirectoryItemDestinationNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item with CopyToOutputDirectory=&quot;{1}&quot; source &apos;{2}&apos; is newer than destination &apos;{3}&apos;, not up-to-date..
        /// </summary>
        internal static string FUTD_CheckingCopyToOutputDirectorySourceNewerThanDestination_4 {
            get {
                return ResourceManager.GetString("FUTD_CheckingCopyToOutputDirectorySourceNewerThanDestination_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source &apos;{0}&apos; does not exist, not up-to-date..
        /// </summary>
        internal static string FUTD_CheckingCopyToOutputDirectorySourceNotFound_1 {
            get {
                return ResourceManager.GetString("FUTD_CheckingCopyToOutputDirectorySourceNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing timestamps of inputs and outputs in Set=&quot;{0}&quot;:.
        /// </summary>
        internal static string FUTD_ComparingInputOutputTimestamps_1 {
            get {
                return ResourceManager.GetString("FUTD_ComparingInputOutputTimestamps_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-to-date check completed in {0:N1} ms.
        /// </summary>
        internal static string FUTD_Completed {
            get {
                return ResourceManager.GetString("FUTD_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item &apos;{1}&apos; has CopyToOutputDirectory set to &apos;Always&apos;, and the project has DisableFastUpToDateCopyAlwaysOptimization set to &apos;true&apos;, not up-to-date..
        /// </summary>
        internal static string FUTD_CopyAlwaysItemExists_2 {
            get {
                return ResourceManager.GetString("FUTD_CopyAlwaysItemExists_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item with CopyToOutputDirectory=&quot;Always&quot; source (&apos;{1}&apos; {2}, {3} bytes) differs from destination (&apos;{4}&apos; {5}, {6} bytes), not up-to-date..
        /// </summary>
        internal static string FUTD_CopyAlwaysItemsDiffer_7 {
            get {
                return ResourceManager.GetString("FUTD_CopyAlwaysItemsDiffer_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical build tasks are running, not up-to-date..
        /// </summary>
        internal static string FUTD_CriticalBuildTasksRunning {
            get {
                return ResourceManager.GetString("FUTD_CriticalBuildTasksRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination {0}: &apos;{1}&apos;.
        /// </summary>
        internal static string FUTD_DestinationFileTimeAndPath_2 {
            get {
                return ResourceManager.GetString("FUTD_DestinationFileTimeAndPath_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;DisableFastUpToDateCheck&apos; property is &apos;true&apos;, not up-to-date..
        /// </summary>
        internal static string FUTD_DisableFastUpToDateCheckTrue {
            get {
                return ResourceManager.GetString("FUTD_DisableFastUpToDateCheckTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-to-date check threw an exception. Not up-to-date. {0}.
        /// </summary>
        internal static string FUTD_Exception_1 {
            get {
                return ResourceManager.GetString("FUTD_Exception_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The up-to-date check has not yet run for this project. Not up-to-date..
        /// </summary>
        internal static string FUTD_FirstRun {
            get {
                return ResourceManager.GetString("FUTD_FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring up-to-date check items with Kind=&quot;{0}&quot;.
        /// </summary>
        internal static string FUTD_IgnoringKinds_1 {
            get {
                return ResourceManager.GetString("FUTD_IgnoringKinds_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input marker &apos;{0}&apos; is newer ({1}) than output marker &apos;{2}&apos; ({3}), not up-to-date..
        /// </summary>
        internal static string FUTD_InputMarkerNewerThanOutputMarker_4 {
            get {
                return ResourceManager.GetString("FUTD_InputMarkerNewerThanOutputMarker_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; ({1}) has been modified since the last successful build started ({2}), not up-to-date..
        /// </summary>
        internal static string FUTD_InputModifiedSinceLastSuccessfulBuildStart_3 {
            get {
                return ResourceManager.GetString("FUTD_InputModifiedSinceLastSuccessfulBuildStart_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; is newer ({1}) than earliest output &apos;{2}&apos; ({3}), not up-to-date..
        /// </summary>
        internal static string FUTD_InputNewerThanOutput_4 {
            get {
                return ResourceManager.GetString("FUTD_InputNewerThanOutput_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No build outputs defined..
        /// </summary>
        internal static string FUTD_NoBuildOutputDefined {
            get {
                return ResourceManager.GetString("FUTD_NoBuildOutputDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No build outputs defined in Set=&quot;{0}&quot;..
        /// </summary>
        internal static string FUTD_NoBuildOutputDefinedInSet_1 {
            get {
                return ResourceManager.GetString("FUTD_NoBuildOutputDefinedInSet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input markers exist, skipping marker check..
        /// </summary>
        internal static string FUTD_NoInputMarkersExist {
            get {
                return ResourceManager.GetString("FUTD_NoInputMarkersExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inputs defined..
        /// </summary>
        internal static string FUTD_NoInputsDefined {
            get {
                return ResourceManager.GetString("FUTD_NoInputsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inputs defined in Set=&quot;{0}&quot;..
        /// </summary>
        internal static string FUTD_NoInputsDefinedInSet_1 {
            get {
                return ResourceManager.GetString("FUTD_NoInputsDefinedInSet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No inputs are newer than earliest output &apos;{0}&apos; ({1}). Newest input is &apos;{2}&apos; ({3})..
        /// </summary>
        internal static string FUTD_NoInputsNewerThanEarliestOutput_4 {
            get {
                return ResourceManager.GetString("FUTD_NoInputsNewerThanEarliestOutput_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Set=&quot;{4}&quot;, no inputs are newer than earliest output &apos;{0}&apos; ({1}). Newest input is &apos;{2}&apos; ({3})..
        /// </summary>
        internal static string FUTD_NoInputsNewerThanEarliestOutputInSet_5 {
            get {
                return ResourceManager.GetString("FUTD_NoInputsNewerThanEarliestOutputInSet_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; does not exist, but is not required..
        /// </summary>
        internal static string FUTD_NonRequiredInputNotFound_1 {
            get {
                return ResourceManager.GetString("FUTD_NonRequiredInputNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input {1} item &apos;{0}&apos; does not exist, but is not required..
        /// </summary>
        internal static string FUTD_NonRequiredTypedInputNotFound_2 {
            get {
                return ResourceManager.GetString("FUTD_NonRequiredTypedInputNotFound_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output marker &apos;{0}&apos; does not exist, skipping marker check..
        /// </summary>
        internal static string FUTD_NoOutputMarkerExists_1 {
            get {
                return ResourceManager.GetString("FUTD_NoOutputMarkerExists_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing CopyToOutputDirectory=&quot;Always&quot; item. Disable this by setting DisableFastUpToDateCopyAlwaysOptimization to &quot;true&quot;..
        /// </summary>
        internal static string FUTD_OptimizingCopyAlwaysItem {
            get {
                return ResourceManager.GetString("FUTD_OptimizingCopyAlwaysItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output &apos;{0}&apos; does not exist, not up-to-date..
        /// </summary>
        internal static string FUTD_OutputDoesNotExist_1 {
            get {
                return ResourceManager.GetString("FUTD_OutputDoesNotExist_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input &apos;{0}&apos; does not exist and is required, not up-to-date..
        /// </summary>
        internal static string FUTD_RequiredInputNotFound_1 {
            get {
                return ResourceManager.GetString("FUTD_RequiredInputNotFound_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input {1} item &apos;{0}&apos; does not exist and is required, not up-to-date..
        /// </summary>
        internal static string FUTD_RequiredTypedInputNotFound_2 {
            get {
                return ResourceManager.GetString("FUTD_RequiredTypedInputNotFound_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set of changed items is empty..
        /// </summary>
        internal static string FUTD_SetOfChangedItemsIsEmpty {
            get {
                return ResourceManager.GetString("FUTD_SetOfChangedItemsIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set of project items was changed more recently ({0}) than the last successful build start time ({1}), not up-to-date..
        /// </summary>
        internal static string FUTD_SetOfItemsChangedMoreRecentlyThanOutput_2 {
            get {
                return ResourceManager.GetString("FUTD_SetOfItemsChangedMoreRecentlyThanOutput_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping &apos;{0}&apos; with ignored Kind=&quot;{1}&quot;.
        /// </summary>
        internal static string FUTD_SkippingIgnoredKindItem_2 {
            get {
                return ResourceManager.GetString("FUTD_SkippingIgnoredKindItem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source {0}: &apos;{1}&apos;.
        /// </summary>
        internal static string FUTD_SourceFileTimeAndPath_2 {
            get {
                return ResourceManager.GetString("FUTD_SourceFileTimeAndPath_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input {3} item &apos;{0}&apos; ({1}) has been modified since the last successful build started ({2}), not up-to-date..
        /// </summary>
        internal static string FUTD_TypedInputModifiedSinceLastSuccessfulBuildStart_4 {
            get {
                return ResourceManager.GetString("FUTD_TypedInputModifiedSinceLastSuccessfulBuildStart_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input {4} item &apos;{0}&apos; is newer ({1}) than earliest output &apos;{2}&apos; ({3}), not up-to-date..
        /// </summary>
        internal static string FUTD_TypedInputNewerThanOutput_5 {
            get {
                return ResourceManager.GetString("FUTD_TypedInputNewerThanOutput_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is up-to-date..
        /// </summary>
        internal static string FUTD_UpToDate {
            get {
                return ResourceManager.GetString("FUTD_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write timestamp on output marker is {0} on &apos;{1}&apos;..
        /// </summary>
        internal static string FUTD_WriteTimeOnOutputMarker_2 {
            get {
                return ResourceManager.GetString("FUTD_WriteTimeOnOutputMarker_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports.
        /// </summary>
        internal static string ImportsTreeNodeName {
            get {
                return ResourceManager.GetString("ImportsTreeNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors in &apos;{0}&apos; need to be corrected before applying changes..
        /// </summary>
        internal static string JsonErrorsNeedToBeCorrected_1 {
            get {
                return ResourceManager.GetString("JsonErrorsNeedToBeCorrected_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors in &apos;{0}&apos; need to be corrected before applying changes. Error message:
        ///{1}.
        /// </summary>
        internal static string JsonErrorsNeedToBeCorrected_WithErrorMessage_2 {
            get {
                return ResourceManager.GetString("JsonErrorsNeedToBeCorrected_WithErrorMessage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value to remove &apos;{0}&apos; was not present in the property &apos;{1}&apos;.
        /// </summary>
        internal static string MsBuildMissingValueToRemove {
            get {
                return ResourceManager.GetString("MsBuildMissingValueToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value to rename &apos;{0}&apos; was not present in the property &apos;{1}&apos;.
        /// </summary>
        internal static string MsBuildMissingValueToRename {
            get {
                return ResourceManager.GetString("MsBuildMissingValueToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string NeutralLanguage_DisplayNameFormatString {
            get {
                return ResourceManager.GetString("NeutralLanguage_DisplayNameFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string NoActionProfileName {
            get {
                return ResourceManager.GetString("NoActionProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Authentication.
        /// </summary>
        internal static string NoAuth {
            get {
                return ResourceManager.GetString("NoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains all the assemblies needed when publishing a .NET Core project..
        /// </summary>
        internal static string OutputGroupPublishItemsDescription {
            get {
                return ResourceManager.GetString("OutputGroupPublishItemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Items.
        /// </summary>
        internal static string OutputGroupPublishItemsDisplayName {
            get {
                return ResourceManager.GetString("OutputGroupPublishItemsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        internal static string PackagesNodeName {
            get {
                return ResourceManager.GetString("PackagesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file &apos;{0}&apos; cannot be opened. 
        ///
        ///This project was loaded using the wrong project type, likely as a result of renaming the project extension outside of Visual Studio. Remove and re-add the project to have the solution pick up the right project type..
        /// </summary>
        internal static string ProjectLoadedWithWrongProjectType {
            get {
                return ResourceManager.GetString("ProjectLoadedWithWrongProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string ProjectsNodeName {
            get {
                return ResourceManager.GetString("ProjectsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string Property_NoneValue {
            get {
                return ResourceManager.GetString("Property_NoneValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK.
        /// </summary>
        internal static string SdkNodeName {
            get {
                return ResourceManager.GetString("SdkNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file or folder with the name &apos;{0}&apos; already exists on disk at this location. Please choose another name.
        ///
        ///If this file or folder does not appear in Solution Explorer, then it is not currently part of your project. To view files which exist on disk, but are not in the project, select Show All Files from the Project menu..
        /// </summary>
        internal static string SpecialFileProvider_FileOrFolderAlreadyExists {
            get {
                return ResourceManager.GetString("SpecialFileProvider_FileOrFolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Authentication.
        /// </summary>
        internal static string WindowsAuth {
            get {
                return ResourceManager.GetString("WindowsAuth", resourceCulture);
            }
        }
    }
}
