//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzers.
        /// </summary>
        internal static string AnalyzersNodeName {
            get {
                return ResourceManager.GetString("AnalyzersNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        internal static string AssembliesNodeName {
            get {
                return ResourceManager.GetString("AssembliesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM.
        /// </summary>
        internal static string ComNodeName {
            get {
                return ResourceManager.GetString("ComNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project system data flow &apos;{0}&apos; closed because of an exception: {1}..
        /// </summary>
        internal static string DataFlowFaults {
            get {
                return ResourceManager.GetString("DataFlowFaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string DependenciesNodeName {
            get {
                return ResourceManager.GetString("DependenciesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Assemblies.
        /// </summary>
        internal static string FrameworkAssembliesNodeName {
            get {
                return ResourceManager.GetString("FrameworkAssembliesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frameworks.
        /// </summary>
        internal static string FrameworkNodeName {
            get {
                return ResourceManager.GetString("FrameworkNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports.
        /// </summary>
        internal static string ImportsTreeNodeName {
            get {
                return ResourceManager.GetString("ImportsTreeNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors in &apos;{0}&apos; need to be corrected before applying changes..
        /// </summary>
        internal static string JsonErrorNeedToBeCorrected {
            get {
                return ResourceManager.GetString("JsonErrorNeedToBeCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value to remove &apos;{0}&apos; was not present in the property &apos;{1}&apos;.
        /// </summary>
        internal static string MsBuildMissingValueToRemove {
            get {
                return ResourceManager.GetString("MsBuildMissingValueToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value to rename &apos;{0}&apos; was not present in the property &apos;{1}&apos;.
        /// </summary>
        internal static string MsBuildMissingValueToRename {
            get {
                return ResourceManager.GetString("MsBuildMissingValueToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string NeutralLanguage_DisplayNameFormatString {
            get {
                return ResourceManager.GetString("NeutralLanguage_DisplayNameFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string NoActionProfileName {
            get {
                return ResourceManager.GetString("NoActionProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Authentication.
        /// </summary>
        internal static string NoAuth {
            get {
                return ResourceManager.GetString("NoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains all the assemblies needed when publishing a .NET Core project..
        /// </summary>
        internal static string OutputGroupPublishItemsDescription {
            get {
                return ResourceManager.GetString("OutputGroupPublishItemsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Items.
        /// </summary>
        internal static string OutputGroupPublishItemsDisplayName {
            get {
                return ResourceManager.GetString("OutputGroupPublishItemsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        internal static string PackagesNodeName {
            get {
                return ResourceManager.GetString("PackagesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file &apos;{0}&apos; cannot be opened. 
        ///
        ///This project was loaded using the wrong project type, likely as a result of renaming the project extension outside of Visual Studio. Remove and re-add the project to have the solution pick up the right project type..
        /// </summary>
        internal static string ProjectLoadedWithWrongProjectType {
            get {
                return ResourceManager.GetString("ProjectLoadedWithWrongProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string ProjectsNodeName {
            get {
                return ResourceManager.GetString("ProjectsNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string Property_NoneValue {
            get {
                return ResourceManager.GetString("Property_NoneValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK.
        /// </summary>
        internal static string SdkNodeName {
            get {
                return ResourceManager.GetString("SdkNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file or folder with the name &apos;{0}&apos; already exists on disk at this location. Please choose another name.
        ///
        ///If this file or folder does not appear in Solution Explorer, then it is not currently part of your project. To view files which exist on disk, but are not in the project, select Show All Files from the Project menu..
        /// </summary>
        internal static string SpecialFileProvider_FileOrFolderAlreadyExists {
            get {
                return ResourceManager.GetString("SpecialFileProvider_FileOrFolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Authentication.
        /// </summary>
        internal static string WindowsAuth {
            get {
                return ResourceManager.GetString("WindowsAuth", resourceCulture);
            }
        }
    }
}
