//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.ProjectSystem.VS.PropertyPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PropertyPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.ProjectSystem.VS.PropertyPages.PropertyPageResources", typeof(PropertyPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must run Visual Studio in the context of an administrator account to create IIS Express sites with ports less than 1024..
        /// </summary>
        public static string AdminRequiredForPort {
            get {
                return ResourceManager.GetString("AdminRequiredForPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments to be passed to the application.
        /// </summary>
        public static string ApplicationArgumentsWatermark {
            get {
                return ResourceManager.GetString("ApplicationArgumentsWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the application.
        /// </summary>
        public static string ApplicationUrlWatermark {
            get {
                return ResourceManager.GetString("ApplicationUrlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyHyperlinkText {
            get {
                return ResourceManager.GetString("CopyHyperlinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugPropertyPageTitle {
            get {
                return ResourceManager.GetString("DebugPropertyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Key.
        /// </summary>
        public static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string EnvVariableNameWatermark {
            get {
                return ResourceManager.GetString("EnvVariableNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string EnvVariableValueWatermark {
            get {
                return ResourceManager.GetString("EnvVariableValueWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files.
        /// </summary>
        public static string ExecutableFiles {
            get {
                return ResourceManager.GetString("ExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the executable to run.
        /// </summary>
        public static string ExecutablePathWatermark {
            get {
                return ResourceManager.GetString("ExecutablePathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS settings are missing the App Url property. This is required to configure IIS to run the site..
        /// </summary>
        public static string IISExpressMissingAppUrl {
            get {
                return ResourceManager.GetString("IISExpressMissingAppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS settings are missing the App Url property. This is required to configure IIS to run the site..
        /// </summary>
        public static string IISMissingAppUrl {
            get {
                return ResourceManager.GetString("IISMissingAppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Application Url is invalid. {0}.
        /// </summary>
        public static string InvalidAppUrl {
            get {
                return ResourceManager.GetString("InvalidAppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS Application Url is invalid. {0}.
        /// </summary>
        public static string InvalidIISAppUrl {
            get {
                return ResourceManager.GetString("InvalidIISAppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IIS Express Application Url is invalid. {0}.
        /// </summary>
        public static string InvalidIISExpressAppUrl {
            get {
                return ResourceManager.GetString("InvalidIISExpressAppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute or relative URL.
        /// </summary>
        public static string LaunchUrlWatermark {
            get {
                return ResourceManager.GetString("LaunchUrlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        public static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile.
        /// </summary>
        public static string NewProfileCaption {
            get {
                return ResourceManager.GetString("NewProfileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newProfile.
        /// </summary>
        public static string NewProfileSeedName {
            get {
                return ResourceManager.GetString("NewProfileSeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string ProfileKindCommandName {
            get {
                return ResourceManager.GetString("ProfileKindCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        public static string ProfileKindExecutableName {
            get {
                return ResourceManager.GetString("ProfileKindExecutableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Express.
        /// </summary>
        public static string ProfileKindIISExpressName {
            get {
                return ResourceManager.GetString("ProfileKindIISExpressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ProfileKindNoActionName {
            get {
                return ResourceManager.GetString("ProfileKindNoActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProfileKindProjectName {
            get {
                return ResourceManager.GetString("ProfileKindProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That profile name is invalid or there is an existing profile with the same name..
        /// </summary>
        public static string ProfileNameInvalid {
            get {
                return ResourceManager.GetString("ProfileNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a profile name..
        /// </summary>
        public static string ProfileNameRequired {
            get {
                return ResourceManager.GetString("ProfileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        public static string ValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path to working directory.
        /// </summary>
        public static string WorkingDirectoryWatermark {
            get {
                return ResourceManager.GetString("WorkingDirectoryWatermark", resourceCulture);
            }
        }
    }
}
