//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.ProjectSystem.VS.PropertyPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.ProjectSystem.VS.PropertyPages.PropertyPageResources", typeof(PropertyPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddBtn {
            get {
                return ResourceManager.GetString("AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application arguments:.
        /// </summary>
        internal static string ApplicationArguments {
            get {
                return ResourceManager.GetString("ApplicationArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments to be passed to the application.
        /// </summary>
        internal static string ApplicationArgumentsWatermark {
            get {
                return ResourceManager.GetString("ApplicationArgumentsWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication mode:.
        /// </summary>
        internal static string AuthenticationMode {
            get {
                return ResourceManager.GetString("AuthenticationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseBtn {
            get {
                return ResourceManager.GetString("BrowseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to the debug property page with no changes.
        /// </summary>
        internal static string CancelBtnHelpText {
            get {
                return ResourceManager.GetString("CancelBtnHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking enables a textbox to specify an absolute or relative URl.
        /// </summary>
        internal static string chkLaunchBrowserHelpText {
            get {
                return ResourceManager.GetString("chkLaunchBrowserHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable native code debugging.
        /// </summary>
        internal static string chkNativeCodeDebuggingText {
            get {
                return ResourceManager.GetString("chkNativeCodeDebuggingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable remote debugging.
        /// </summary>
        internal static string chkRemoteDebugEnabledHelpText {
            get {
                return ResourceManager.GetString("chkRemoteDebugEnabledHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SQL Server debugging.
        /// </summary>
        internal static string chkSqlCodeDebuggingText {
            get {
                return ResourceManager.GetString("chkSqlCodeDebuggingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string DebugPropertyPageTitle {
            get {
                return ResourceManager.GetString("DebugPropertyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the current profile and change to the next available profile.
        /// </summary>
        internal static string DeleteBtnHelpText {
            get {
                return ResourceManager.GetString("DeleteBtnHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Key.
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variables:.
        /// </summary>
        internal static string EnvironmentVariables {
            get {
                return ResourceManager.GetString("EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string EnvVariableNameWatermark {
            get {
                return ResourceManager.GetString("EnvVariableNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string EnvVariableValueWatermark {
            get {
                return ResourceManager.GetString("EnvVariableValueWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The errors on the page must be corrected prior to saving your changes..
        /// </summary>
        internal static string ErrorsMustBeCorrectedPriorToSaving {
            get {
                return ResourceManager.GetString("ErrorsMustBeCorrectedPriorToSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable:.
        /// </summary>
        internal static string Executable {
            get {
                return ResourceManager.GetString("Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files.
        /// </summary>
        internal static string ExecutableFiles {
            get {
                return ResourceManager.GetString("ExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the executable to run.
        /// </summary>
        internal static string ExecutablePathWatermark {
            get {
                return ResourceManager.GetString("ExecutablePathWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        internal static string FindBtn {
            get {
                return ResourceManager.GetString("FindBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host name is invalid..
        /// </summary>
        internal static string InvalidHostName {
            get {
                return ResourceManager.GetString("InvalidHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch:.
        /// </summary>
        internal static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch browser:.
        /// </summary>
        internal static string LaunchURL {
            get {
                return ResourceManager.GetString("LaunchURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute or relative URL.
        /// </summary>
        internal static string LaunchUrlWatermark {
            get {
                return ResourceManager.GetString("LaunchUrlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        internal static string NameCannotBeEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameHeader {
            get {
                return ResourceManager.GetString("NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string NewBtn {
            get {
                return ResourceManager.GetString("NewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the new profile dialog.
        /// </summary>
        internal static string NewBtnHelpText {
            get {
                return ResourceManager.GetString("NewBtnHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile.
        /// </summary>
        internal static string NewProfileCaption {
            get {
                return ResourceManager.GetString("NewProfileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newProfile.
        /// </summary>
        internal static string NewProfileSeedName {
            get {
                return ResourceManager.GetString("NewProfileSeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKBtn {
            get {
                return ResourceManager.GetString("OKBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the profile and return to the debug property page with the new profile selected.
        /// </summary>
        internal static string OKBtnHelpText {
            get {
                return ResourceManager.GetString("OKBtnHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        internal static string ProfileKindExecutableName {
            get {
                return ResourceManager.GetString("ProfileKindExecutableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS Express.
        /// </summary>
        internal static string ProfileKindIISExpressName {
            get {
                return ResourceManager.GetString("ProfileKindIISExpressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ProfileKindNoActionName {
            get {
                return ResourceManager.GetString("ProfileKindNoActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string ProfileKindProjectName {
            get {
                return ResourceManager.GetString("ProfileKindProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name:.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That profile name is invalid or there is an existing profile with the same name..
        /// </summary>
        internal static string ProfileNameInvalid {
            get {
                return ResourceManager.GetString("ProfileNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a profile name..
        /// </summary>
        internal static string ProfileNameRequired {
            get {
                return ResourceManager.GetString("ProfileNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use remote m_achine:.
        /// </summary>
        internal static string RemoteDebug {
            get {
                return ResourceManager.GetString("RemoteDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote machine host name.
        /// </summary>
        internal static string RemoteDebugMachineWatermark {
            get {
                return ResourceManager.GetString("RemoteDebugMachineWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a remote machine&apos;s host name..
        /// </summary>
        internal static string RemoteHostNameRequired {
            get {
                return ResourceManager.GetString("RemoteHostNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveBtn {
            get {
                return ResourceManager.GetString("RemoveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        internal static string ValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("ValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueHeader {
            get {
                return ResourceManager.GetString("ValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory:.
        /// </summary>
        internal static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path to working directory.
        /// </summary>
        internal static string WorkingDirectoryWatermark {
            get {
                return ResourceManager.GetString("WorkingDirectoryWatermark", resourceCulture);
            }
        }
    }
}
