# Licensed to the .NET Foundation under one or more agreements. The .NET Foundation licenses this file to you under the MIT license. See the LICENSE.md file in the project root for more information.
jobs:
- job: PublishNpmPackages
  displayName: Publish NPM Packages
  timeoutInMinutes: 20
  steps:
  ###################################################################################################################################################################
  # Download artifacts
  ###################################################################################################################################################################

  # Use a disabled, empty script to display the section header in the pipeline UI.
  - script:
    displayName: === Download artifacts ===
    condition: false
    
  # Download the build artifacts from the Build job.
  - download: current
    displayName: Download Build Artifacts
    artifact: $(Build.BuildNumber)
    # Only download the necessary files for publishing.
    patterns: |
      packages/**
      
  ###################################################################################################################################################################
  # PUBLISH NPM Packages
  ###################################################################################################################################################################

  # Authenticates the .npmrc file for publishing to the internal AzDO feed.
  # See: https://learn.microsoft.com/azure/devops/pipelines/tasks/package/npm-authenticate?view=azure-devops
  - task: npmAuthenticate@0
    displayName: Authenticate NPM Feed
    inputs:
      workingFile: $(Build.SourcesDirectory)/src/Microsoft.VisualStudio.ProjectSystem.Managed/.npmrc

  # Publishes the NPM package to the internal AzDO feed.
  # Feed: https://dev.azure.com/devdiv/DevDiv/_artifacts/feed/vs-green/Npm/@microsoft%2Fmicrosoft.visualstudio.projectsystem.managed/
  # See: https://docs.npmjs.com/cli/v8/commands/npm-publish
  # npmrc doc: https://docs.npmjs.com/cli/v9/using-npm/config#npmrc-files
  - powershell: . '$(Build.SourcesDirectory)/eng/scripts/PublishNPMPackage.ps1' -npmrcPath '$(Build.SourcesDirectory)/src/Microsoft.VisualStudio.ProjectSystem.Managed/.npmrc' -tgzPath ((Get-ChildItem -Path '$(Pipeline.Workspace)/$(Build.BuildNumber)/packages/microsoft-microsoft.visualstudio.projectsystem.managed-*.tgz').FullName)
    displayName: Publish NPM Package