' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

Imports System.Runtime.InteropServices

Namespace Microsoft.VisualStudio.Shell.Interop

    Public Module VsSqmDataPoint
        Public Enum DATAID As UInt32
            Undefined = 0
            SQM_ACTIVATEDOCWINDOW = 1    ' (Stream) 
            SQM_UICONTEXTCHANGED = 2    ' (Stream) 
            SQM_PERFMEMORY = 3
            SQM_STARTUPOS = 4
            SQM_STARTUPOSVERSION = 5
            SQM_STARTUPOSBUILD = 6
            SQM_STARTUPOSSERVICEPACK = 7
            SQM_STARTUPAPPID = 8
            SQM_STARTUPAPPBUILDTYPE = 9
            SQM_STARTUPAPPVERSION = 10
            SQM_STARTUPAPPBUILDNUMBER = 11
            SQM_STARTUPAPPPRODUCTLOCALE = 12
            SQM_STARTUPAPPSYSTEMLOCALE = 13
            SQM_STARTUPAPPUSERLOCALE = 14
            SQM_PERFCPUCOUNT = 15
            SQM_PERFPROCFAMILY = 16
            SQM_PERFPROCMODEL = 17
            SQM_PERFPROCSTEPPING = 18
            SQM_PERFPROCFREQUENCY = 19
            SQM_EVTIDLE = 20   ' (Stream) 
            SQM_SHUTDOWNREASON = 21
            SQM_ACTIVATETOOLWINDOW = 22   ' (Stream) 
            SQM_EVTDEBUG = 23   ' (Stream) 
            SQM_SESSIONDURATION = 24
            SQM_SESSIONIDLE = 25
            SQM_EVTSELECTIONCHANGED = 26
            SQM_WATSONUPLOAD = 27
            SQM_EVTBEFORECOMMANDEXECUTES = 28   ' (Stream) 
            SQM_ASSERT = 29   ' (Stream) 
            SQM_COMPLUSVERSION = 30   ' (Stream) 
            SQM_STRING = 31   ' (Stream) 
            SQM_VSEDITION = 32   ' DELETED FROM MANAGEMENT SITE
            SQM_VSADDINCOUNT = 33
            SQM_DISPLAYCOUNT = 34
            SQM_VSBUILDRCNUMBER = 35
            SQM_USERPRIV = 36
            SQM_USERTYPE = 37
            SQM_VSPROFILE = 38
            SQM_IEVER = 39
            STRM_VB_ERROR = 40   ' (Stream) 
            SQM_DISPLAYRESOLUTION = 41
            SQM_VSSKU = 42
            SQM_VOLUMESIZE = 43
            SQM_FREEDISKSPACE = 44
            SQM_COLORDEPTH = 45
            SQM_MDI = 46
            SQM_VSPROJECTS = 47   ' (Stream) 
            SQM_VSCOMMANDS = 48   ' (Stream) 
            SQM_VSSOLUTIONS = 49   ' (Stream) 
            SQM_VSSCCHANGE = 50   ' (Stream) 
            SQM_HDSIZE = 51
            SQM_VSTOOLWINS = 52   ' (Stream) 
            SQM_PKGLOAD = 53   ' (Stream) 
            STRM_VB_AUTO_OPEN = 54   ' (Stream) 
            STRM_VB_AUTO_APPEAR_ERROR = 55   ' (Stream) 
            STRM_VB_AUTO_PICK = 56   ' (Stream) 
            STRM_VB_AUTO_APPEAR_HOVER = 57   ' (Stream) 
            SQM_PKGINST = 58   ' (Stream) 
            SQM_NUMMACROSINST = 59
            SQM_CSHARP_IDE_UNMANAGED_ERROR = 60   ' (Stream) 
            STRM_VB_DEBUGGER_CONTINUE = 61   ' (Stream) 
            STRM_VB_DEBUGGER_RUNMSGS = 62   ' (Stream) 
            STRM_VB_DEBUGGER_NEWRUN = 63   ' (Stream) 
            STRM_VB_DEBUGGER_COMPILERSTATE = 64   ' (Stream) 
            STRM_VB_DEBUGGER_SETBREAKLINE = 65   ' (Stream) 
            STRM_VB_EDITOR_INTELLISENSETABCHANGE = 66   ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VB_EDITOR_PROJPROPSHOW = 67   ' (Stream) 
            STRM_VB_EDITOR_NUMLOCALIZEDFILES = 68   ' (Stream) 
            STRM_VB_EDITOR_FORMRENAME = 69   ' (Stream) 
            STRM_VB_EXCEPTION_SHOW = 70   ' (Stream) 
            STRM_VB_EXCEPTION_ONLINEHELP = 71   ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VB_SNIPPETUPGRADE_FINISH = 72   ' (Stream) 
            STRM_VB_UPGRADEWIZARD_START = 73   ' (Stream) 
            STRM_VB_UPGRADEWIZARD_FINISH = 74   ' (Stream) 
            STRM_VB_SOLUTION_EMBEDDED = 75   ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VB_SOLUTION_STATS = 76   ' (Stream) 
            STRM_VB_SOLUTION_OPTIONS = 77   ' (Stream) 
            STRM_VB_SOLUTION_NOTIFICATION = 78   ' (Stream) 
            DP_VB_EDITOR_INTELLISENSETABSHOW = 79
            DP_VB_SNIPPETUPGRADE_START = 80
            SQM_OWNINGVSSKU = 81   ' DELETED FROM MANAGEMENT SITE
            SQM_OWNINGVSBUILDNUMBER = 82   ' DELETED FROM MANAGEMENT SITE
            SQM_OWNINGVSPROFILE = 83   ' DELETED FROM MANAGEMENT SITE
            DP_VB_EDITOR_INTELLISENSETABALL = 84
            DP_VB_EDITOR_INTELLISENSETABCOMMON = 85
            DP_VB_SOLUTION_EMBEDDEDTRUE = 86
            DP_VB_SOLUTION_EMBEDDEDFALSE = 87
            SQM_OWNINGVSBUILDRCNUMBER = 88   ' DELETED FROM MANAGEMENT SITE
            SQM_VDT_CM_PROVIDERDATASOURCE = 89
            SQM_VDT_SE_NUMBERTABLESENUM = 90
            DP_VDT_SE_NOCONNECTIONS = 91
            SQM_VDT_SE_DRAGSOURCE = 92   ' DELETED FROM MANAGEMENT SITE
            SQM_NAVTOHELP = 93   ' (Stream) 
            SQM_VSHELPOPTEXTINT = 94
            SQM_VSHELPOPTONLINE = 95
            SQM_VSHELPTOPICONLINE = 96   ' DELETED FROM MANAGEMENT SITE
            SQM_VSHELPTOPICLOCAL = 97   ' DELETED FROM MANAGEMENT SITE
            SQM_VDT_COLPROP_COLPROPUSAGE = 98
            V_VDT_DDIAG_CHANGESCRIPTS = 99
            SQM_VDT_DDIAG_DBOCREATE = 100
            SQM_VDT_DDIAG_DDIAGUSAGE = 101
            SQM_VDT_DDIAG_DIAGDISCARD = 102
            SQM_VDT_DDIAG_NODIAGRAMTABLE = 103
            SQM_VDT_DDIAG_NONDBOCREATE = 104
            SQM_VDT_DDIAG_RELATIONSHIPCREATION = 105
            SQM_VDT_DDIAG_TABLEVIEWOPCHANGE = 106
            SQM_VDT_TD_COLUMNPROPERTIES = 107  ' DELETED FROM MANAGEMENT SITE
            SQM_VDT_TD_DIALOGUSAGE = 108
            SQM_VDT_TD_SCRIPTGEN = 109
            SQM_VDT_TD_TDUSAGE = 110
            SQM_VDT_SE_NUMBERASSEMBLIESENUM = 111
            SQM_VDT_SE_NUMBERDRAGOBJECTS = 112
            SQM_VDT_SE_NUMBERFUNCTIONSENUM = 113
            SQM_VDT_SE_NUMBEROTHERENUM = 114
            SQM_VDT_SE_NUMBERSPROCSENUM = 115
            SQM_VDT_SE_NUMBERSYNONYMSENUM = 116
            V_VDT_SE_NUMBERVIEWSENUM = 117
            SQM_VDT_SQLCLR_USEAGE = 118
            SQM_VDT_QD_UPDATEUSAGE = 119
            SQM_VDT_QD_QUERYSAVED = 120
            SQM_VDT_QD_SELECTUSAGE = 121
            SQM_VDT_QD_SQLUSAGE = 122
            SQM_VDT_QD_QUERYNOTSAVED = 123
            SQM_VDT_QD_NONFROMCLAUSES = 124
            SQM_VDT_QD_MAKETABLEUSAGE = 125
            SQM_VDT_QD_INSERTVALUESUSAGE = 126
            SQM_VDT_QD_INSERTRESULTSUSAGE = 127
            SQM_VDT_QD_FROMVIEWS = 128
            SQM_VDT_QD_FROMTABLES = 129
            SQM_VDT_QD_FROMSUBQUERIES = 130
            SQM_VDT_QD_FROMROWSET = 131
            DP_VDT_QD_DIAGUSAGE = 132
            SQM_VDT_QD_CRITERIAUSAGE = 133
            SQM_VDT_QD_DELETEUSAGE = 134
            SQM_VDT_QD_RUNQUERYUSAGE = 135
            SQM_VDT_VD_VIEWSAVED = 136
            SQM_VDT_VD_VIEWNOTSAVED = 137
            SQM_VDT_VD_VIEWPROVIDERUSAGE = 138
            SQM_VDT_QD_PROVIDERUSAGE = 139
            SQM_VDT_TSQLE_QBUSAGE = 140
            SQM_VDT_DBPROJ_USEOFSC = 141
            SQM_VDT_DBPROJ_NOOFSQLFILES = 142
            SQM_VDT_DBPROJ_NOOFDTQFILES = 143
            SQM_VDT_DBPROJ_SCRIPTING = 144
            SQM_VDT_DBPROJ_DBPROJUSAGE = 145
            SQM_VDT_DBPROJ_PROVIDERUSAGE = 146
            SQM_VDT_DBPROJ_QBUSAGE = 147
            SQM_VDT_DDIAG_DIAGSAVED = 148
            SQM_VDT_QD_SQLFEATUREUSAGE = 149
            SQM_VDT_QD_GENERICFEATUREUSAGE = 150
            SQM_VDT_SQLCLR_FAILUREERROR = 151
            SQM_VDT_QD_MAXFROMCLAUSEUSAGE = 152
            STRM_VB_DATA_REENTRANTWIZARD = 153  ' (Stream) 
            STRM_VB_DATA_GENCOMMANDS = 154  ' (Stream) 
            STRM_VB_DATA_CONNCONSUMPTION = 155  ' (Stream) 
            STRM_VB_DATA_ADDSOURCE = 156  ' (Stream) 
            STRM_VB_DATA_NUMTABLES = 157  ' (Stream) 
            STRM_VB_DATA_ADDQUERY = 158  ' (Stream) 
            STRM_VB_DATA_EVERETTWIZARD = 159  ' (Stream) 
            STRM_VB_DATA_ADDQUERYTOADAPTER = 160  ' (Stream) 
            STRM_VB_DATA_INPUTQUERY = 161  ' (Stream) 
            SQM_HASVSDEVKEY = 162
            SQM_CLEARTYPE = 163
            SQM_EXENAME = 164
            SQM_VDT_QD_VERIFYSQL = 165
            SQM_NUMADDINSINST = 166
            SQM_NUMADDINSLOAD = 167
            SQM_NUMADDINSLOADSUCCESS = 168
            SQM_HIGHCONTRAST = 169
            SQM_CSHARP_IDE_AUTOCOMPLETE_ONOFF = 170
            SQM_CSHARP_IDE_COMPLETIONKEY = 171  ' (Stream) 
            SQM_CSHARP_IDE_COMPLETIONCHARCHANGE = 172  ' (Stream) 
            SQM_CSHARP_IDE_EXTERNALIASCOUNT = 173
            SQM_CSHARP_IDE_FORMATSETTINGS1 = 174
            SQM_CSHARP_IDE_COMPILER_ERROR = 175  ' (Stream) 
            SQM_CSHARP_IDE_COMPILERREFACTORCOUNT = 176
            SQM_CSHARP_IDE_PREVIEWCHANGES = 177  ' DELETED FROM MANAGEMENT SITE
            SQM_CSHARP_IDE_PREVIEWCHANGECANCEL = 178  ' DELETED FROM MANAGEMENT SITE
            SQM_CSHARP_ENC_CONTINUE = 179  ' (Stream) 
            SQM_CSHARP_ENC_APPLY = 180  ' (Stream) 
            SQM_CSHARP_ENC_PROJECTFILESCHANGED = 181  ' (Stream) 
            SQM_CSHARP_ENC_ERRORCOUNT = 182  ' DELETED FROM MANAGEMENT SITE
            SQM_TEXTEDITORFONTNAME = 183
            SQM_VSPROJECTPOLICY = 184  ' (Stream) 
            SQM_CSHARP_IDE_FORMATSETTINGS2 = 185
            SQM_CSHARP_IDE_MANAGED_ERROR = 186  ' (Stream) 
            SQM_VSDPROJECTS = 187  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_VSTOPROJECTS = 188  ' (Stream) 
            STRM_VSD_CONNECTION = 189  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VSD_DEPLOYMENT = 190  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_DEBUGGER_FUNCEVALABORT = 191  ' (Stream) 
            SQM_VSD_CONNECTIONATTEMPTED = 192
            SQM_VSD_CONNECTIONSUCCEEDED = 193
            SQM_VSD_DEPLOYFILESIZE = 194  ' (Stream) 
            SQM_VSD_DEPLOYNUMFILES = 195  ' (Stream) 
            SQM_DEBUGGER_ERRORS = 196  ' (Stream) 
            SQM_DEBUGGER_ENC_ERRORREASON = 197  ' (Stream) 
            SQM_CSHARP_IDE_COMPLETIONCHARCHA_64828_NEW = 198 ' (Stream) 
            SQM_LOCALHELPTOPIC = 199  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_VSD_DEBUGDEVICE = 200  ' (Stream) 
            SQM_VSD_DEBUGWASTON = 201  ' DELETED FROM MANAGEMENT SITE
            SQM_DEBUGCONNECTIONERROR = 202  ' (Stream) 
            SQM_VSEDITORSGETFOCUS = 203  ' (Stream) 
            SQM_VSEDITORSLOSEFOCUS = 204  ' (Stream) 
            SQM_TEST = 205
            SQM_KEYBINDINGSSCHEMENAME = 206
            STRM_VC_COMPILER_SWITCH = 207  ' (Stream) 
            STRM_VC_COMPILER_DIAGNOSTICS = 208  ' (Stream) 
            STRM_VC_IDE_PROJECTSTATISTICS = 209  ' (Stream) 
            STRM_VC_COMPILER_PARENTPROCESS = 210  ' (Stream) 
            STRM_VC_IDE_INTELLISENSE = 211  ' (Stream) 
            STRM_VC_IDE_RESOURCEEDITOR = 212  ' (Stream) 
            STRM_VC_COMPILER_TARGET = 213  ' (Stream) 
            STRM_VC_IDE_WIZARDS = 214  ' (Stream) 
            SQM_VSD_DEVICEINFO = 215  ' (Stream) 
            STRM_VC_COMPILER_MACRO_DEFINITION = 216  ' (Stream) 
            SQM_ENVFONTNAME = 217
            SQM_SCREENDPI = 218
            SQM_ENVFONTSIZE = 219
            SQM_DELAYNOTIFICATION = 220  ' (Stream) 
            SQM_NUMCDDRIVES = 221
            SQM_NUMDVDDRIVES = 222
            SQM_VSD_CHANGEPLATFORM = 223  ' (Stream) 
            SQM_VSD_UPGRADEPROJECT = 224  ' (Stream) 
            SQM_CONNECTIONERROR = 225  ' (Stream) 
            SQM_CSHARP_REFACTOR_COMMANDERROR = 226  ' (Stream) 
            SQM_CSHARP_REFACTOR_WARNINGDIAG = 227  ' (Stream) 
            SQM_CSHARP_IDE_PREVIEWDIAG = 228  ' (Stream) 
            SQM_SCREENREADER = 229
            SQM_VSCORE_TEMPLATE_SELECTION = 230  ' (Stream) 
            SQM_VSCORE_P2P_REFERENCES = 231  ' (Stream) 
            SQM_VSCORE_FILE_REFERENCES = 232  ' (Stream) 
            SQM_NUMBEROFFILESPERBUILDACTION = 233  ' (Stream) 
            SQM_VSD_DATA_GENERATEDATAFORMS = 234
            SQM_VSD_DATA_SQLMOBILEINSERVEREXPLORER = 235
            SQM_VSD_DATA_DRAGDROP = 236  ' (Stream) 
            SQM_VSD_DATA_DATASOURCEGENERATION = 237  ' (Stream) 
            SQM_VSD_DATA_MANAGEMENTUI = 238  ' (Stream) 
            SQM_VENUS_WEBPROJECTLANGTYPE = 239  ' (Stream) 
            STRM_VB_WEBSVC_HOSTTYPE = 240  ' (Stream) 
            DP_JLCA_MIGRATION_START = 241
            DP_JLCA_MIGRATION_SUCCESS = 242
            DP_JLCA_MIGRATION_CANCEL = 243
            DP_JLCA_MIGRATION_FAILURE = 244
            DP_VB_EDITOR_INTELLISENSETABSHOWALL = 245
            SQM_FILESYSTEMTYPE = 246
            STRM_VB_UPGRADEWIZARD_ISSUES = 247  ' (Stream) 
            STRM_VB_UPGRADEWIZARD_COMLIBRARIES = 248  ' (Stream) 
            SQM_SCCPROVIDERFORPROJECT = 249  ' (Stream) 
            SQM_SOLNEXPLORER_PRJUSESSHOWALL = 250
            STRM_VB_DATA_ADDLOCALDATACONNECTION = 251  ' (Stream) 
            STRM_VB_EDITOR_SNIPPETINSERT = 252  ' (Stream) 
            STRM_VB_EDITOR_UNDOINSERTSNIPPET = 253  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VB_EDITOR_SNIPPETNEWOBJECT = 254  ' (Stream) 
            SQM_VSNUMEDITORMARKERS = 255
            SQM_VSD_DE_RAMSIZE = 256
            SQM_VSD_DE_ROMSIZE = 257
            SQM_VSD_DE_HOSTKEY = 258  ' (Stream) 
            SQM_VSD_DE_FLASHFILE = 259
            SQM_VSD_DE_CMNDXTRA = 260
            SQM_VSD_DE_FUNCKEY = 261
            SQM_VSD_DE_CONFIG = 262
            SQM_VSD_DE_SP1 = 263  ' (Stream) 
            SQM_VSD_DE_SP2 = 264  ' (Stream) 
            SQM_VSD_DE_SP3 = 265  ' (Stream) 
            SQM_VSD_DE_RECORDAUDIO = 266
            SQM_VSD_DE_PLAYAUDIO = 267
            SQM_VSD_DE_EXDI = 268
            SQM_VSD_DE_TABLETINK = 269
            SQM_VSD_DE_LAUNCHTYPE = 270
            SQM_VSD_DE_NE2000 = 271  ' (Stream) 
            SQM_VSD_DE_CS8900 = 272
            SQM_VSD_DE_HARDRESET = 273
            SQM_VSD_DE_SOFTRESET = 274
            SQM_VSD_DE_SKINCHANGE = 275
            SQM_VSD_DE_MMTIMER = 276
            SQM_VSD_DE_COMPORTS = 277
            SQM_VSD_DE_TERMINATE = 278
            SQM_VSD_DE_INTLOST = 279
            SQM_VSD_DE_VPCPOWERATTEMPT = 280
            SQM_VSD_DE_VPCPOWERFAILED = 281
            SQM_VSD_DE_DMASENT = 282
            SQM_VSD_DE_DMARCVD = 283
            SQM_VSD_DE_DMALOST = 284
            SQM_VSD_DEM_ACTIONFAILED = 285  ' (Stream) 
            SQM_VSD_DEM_ACTIONLAUNCHED = 286  ' (Stream) 
            SQM_VSD_DEM_LAUNCHED = 287
            SQM_VSD_DEM_FAILED = 288
            SQM_VSD_DEM_NONCORECONEMU = 289
            SQM_VSD_DEM_RUNNINGEMU = 290
            SQM_VSD_DEM_CORECON = 291
            SQM_VSDDE_STARTUPOS = 292
            SQM_VSDDE_STARTUPOSBUILD = 293
            SQM_VSDDE_OSLOCALE = 294
            SQM_VSDDE_OSSERVICEPACK = 295
            SQM_VSDDE_OSVERSION = 296
            SQM_VSD_DE_VERSION = 297
            SQM_VSD_DE_STARTUPAPPID = 298
            SQM_VSD_DE_BUILDRCNUMBER = 299
            SQM_VSD_DE_BUILDNUM = 300
            SQM_VSD_DE_PERFCPUCOUNT = 301
            SQM_VSD_DE_PERFMEMORY = 302
            SQM_VSD_DE_PERFPROCFAMILY = 303
            SQM_VSD_DE_PERFPROCFREQUENCY = 304
            SQM_VSD_DE_PERFPROCMODEL = 305
            SQM_VSD_DEM_ACTION = 306  ' (Stream) 
            SQM_VSD_DE_SERIALPORT = 307  ' (Stream) 
            SQM_LOCALVER_IVSSOLUTIONEVENTS = 308  ' (Stream) 
            SQM_LOCALVER_IVSUPDATESOLUTIONEVENTS = 309  ' (Stream) 
            SQM_LOCALVER_IVSRUNNINGDOCUMENTTABLEEVENTS = 310 ' (Stream) 
            SQM_LOCALVER_IVSTRACKPROJECTDOCUMENTEVENTS2 = 311 ' (Stream) 
            SQM_LOCALVER_STOREOPERATIONS = 312  ' (Stream) 
            SQM_VSD_DE_USERTYPE = 313
            SQM_VSD_DE_STARTUPAPPPRODUCTLOCALE = 314
            SQM_VSD_DE_APPBUILDTYPE = 315
            SQM_VSD_DE_STARTUPAPPVERSION = 316
            SQM_VSD_DE_FOLDERSHARE = 317  ' (Stream) 
            SQM_VSD_DE_RTCADJUST = 318
            SQM_VSD_DE_LAUNCHFAILED = 319
            STRM_TSDATA_COMPAREENCRYPTEDPROCS = 320  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_TSDATA_EDITORRESULTSIZE = 321  ' (Stream) 
            STRM_TSDATA_REFACTORINGPREVIEW = 322  ' (Stream) 
            STRM_TSDATA_COMPAREDATAENCRYPTEDCOLUMN = 323 ' (Stream) 
            STRM_TSDATA_SCHEMACOMPAREERROR = 324  ' (Stream) 
            STRM_TSDATA_SCHEMACOMPAREUPDATE = 325  ' (Stream) 
            STRM_TSDATA_TESTGEN = 326  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_TSDATA_COMPAREENCRYPTEDPROC = 327  ' (Stream) 
            STRM_TSDATA_OBJECTTYPE = 328  ' (Stream) 
            STRM_TSDATA_GENERATETEST = 329  ' (Stream) 
            SQM_CODEANALYSIS_USAGE_ENABLECA = 330  ' (Stream) 
            SQM_CODEANALYSIS_USAGE_NUMBEROFCABUILDS = 331 ' (Stream) 
            SQM_CODEANALYSIS_USAGE_NUMBEROFONETIMEBUILDS = 332 ' (Stream) 
            SQM_CODEANALYSIS_ANALYSIS_NUMBEROFVIOLATIONSINERRORLIST = 333 ' (Stream) 
            SQM_CODEANALYSIS_ANALYSIS_RULESFIRED = 334  ' (Stream) 
            SQM_CODEANALYSIS_ANALYSIS_RULESUPPRESSION = 335 ' (Stream) 
            SQM_CODEANALYSIS_USAGE_NUMBEROFBUILDS = 336 ' (Stream) 
            SQM_CODEANALYSIS_USAGE_RULESELECTION = 337  ' (Stream) 
            SQM_CODEANALYSIS_USAGE_RULESEVERITY = 338  ' (Stream) 
            STRM_AVRFVS_MENU = 339  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_AVRFVS_SETTINGS = 340  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_AVRFVS_STOP = 341  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_AVRFVS_STOP_DIALOG_BUTTON = 342  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_SETUPFAIL = 343
            SQM_SETUPSTART = 344
            SQM_SETUPSUCCEED = 345
            SQM_STRM_VB_EDITOR_STATEMENTCOMPLETIONCOMMIT = 346 ' (Stream) 
            SQM_DEXPLORESTATE = 347
            SQM_DOCUMENTATION_WIN32STATE = 348
            SQM_DOCUMENTATION_FXSTATE = 349
            SQM_SAMPLES_WIN32STATE = 350
            SQM_SAMPLES_WINFX_ZIPSTATE = 351
            SQM_SAMPLES_WINFX_DOCSSTATE = 352
            SQM_DEVTOOLS_VISTAHEADERSLIBSSTATE = 353
            SQM_DEVTOOLS_HEADERFILESSTATE = 354
            SQM_DEVTOOLS_X86LIBSSTATE = 355
            SQM_DEVTOOLS_X64LIBSSTATE = 356
            SQM_DEVTOOLS_IA64LIBSSTATE = 357
            SQM_DEVTOOLS_VCCOMPILERSSTATE = 358
            SQM_DEVTOOLS_X86COMPILERSSTATE = 359
            SQM_DEVTOOLS_X64COMPILERSSTATE = 360
            SQM_DEVTOOLS_IA64COMPILERSSTATE = 361
            SQM_DEVTOOLS_FXCOPSTATE = 362
            SQM__DEVTOOLS_WINDBGSTATE = 363
            SQM_DEVTOOLS_WIN32DESKTOPTOOLSSTATE = 364
            SQM_DEVTOOLS_FXDESKTOPTOOLSSTATE = 365
            SQM_DEVTOOLS_CFSTATE = 366
            SQM_DP_VB_DATA_TYPEDDATASET_ENABLETABLEADAPTERMANAGER = 367 ' DELETED FROM MANAGEMENT SITE
            SQM_DP_VB_DATA_TYPEDDATASET_UPDATEORDER = 368 ' DELETED FROM MANAGEMENT SITE
            SQM_DP_VB_DATA_TYPEDDATASET_BACKUPBEFOREUPDATE = 369 ' DELETED FROM MANAGEMENT SITE
            SQM_STRM_VB_DATA_TYPEDDATASET_BACKUPBEFOREUPDATE = 370 ' (Stream) 
            SQM_STRM_VB_DATA_TYPEDDATASET_ENABLETABLEADAPTERMANAGER = 371 ' (Stream) 
            SQM_STRM_VB_DATA_TYPEDDATASET_UPDATEORDER = 372 ' (Stream) 
            SQM_DESIGN_TIME_ERROR = 373  ' (Stream) 
            SQM_STRM_VB_DATA_NTIER = 374  ' (Stream) 
            SQM_DP_VB_FG_WAIT = 375
            SQM_DP_VB_FG_WAIT_CANCEL = 376
            DP_VSD_DEMAPI_LAUNCH = 377
            DP_VSD_DEMAPI_DECFG_EMU = 378
            DP_VSD_DECFG_EMU_CONNECT = 379
            SQM_PROFILER_NUM_LAUNCHES = 380
            SQM_PROFILER_NUM_SAMPLING_LAUNCHES = 381
            SQM_PROFILER_NUM_INSTR_LAUNCHES = 382
            SQM_PROFILER_NUM_ASPNET_LAUNCHES = 383
            SQM_PROFILER_NUM_WCF_LAUNCHES = 384
            SQM_PROFILER_NUM_VSP_REPORTS = 385
            SQM_PROFILER_NUM_EXECUTE_FILTER = 386
            SQM_PROFILER_NUM_CPP_LAUNCHES = 387
            SQM_PROFILER_NUM_VB_LAUNCHES = 388
            SQM_PROFILER_NUM_CS_LAUNCHES = 389
            STRM_VC_IDE_DIALOGEDITORCONTROLS = 390
            SQM_PLATFORM = 391
            SQM_CFVERSION = 392
            SQM_PROJECTTYPE = 393
            SQM_VSD_LANGUAGE = 394
            SQM_CFVERSION1 = 395  ' (Stream) 
            SQM_VSD_LANGUAGE1 = 396  ' (Stream) 
            SQM_PLATFORM1 = 397  ' (Stream) 
            SQM_PROJECTTYPE1 = 398  ' (Stream) 
            SQM_VSD_DEMAPI_DECFG_EMU = 399
            STRM_VC_IDE_DIALOGEDITORCTRLS = 400  ' (Stream) 
            SQM_VSD_PROJECT = 401  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VSD_PROJECTCREATE = 402  ' (Stream) 
            SQM_DP_VB_XMLTOSCHEMAWIZARD_USEWIZARD = 403
            SQM_DP_VB_XMLTOSCHEMAWIZARD_FROMFILE = 404
            SQM_DP_VB_XMLTOSCHEMAWIZARD_FROMWEB = 405
            SQM_DP_VB_XMLTOSCHEMAWIZARD_FROMXML = 406
            SQM_STRM_VB_XMLTOSCHEMAWIZARD_EXCEPTION = 407 ' (Stream) 
            SQM_XMLEDITOR_FILESIZE = 408  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_FILEEXTENSION1 = 409  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_SCHEMADOWNLOAD = 410  ' DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_GENERATEDSCHEMAEXTENTION1 = 411 ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_ERRORLISTUSED = 412  ' DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_SCHEMADIALOGLAUNCH = 413  ' DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_SCHEMADIALOGCHANGE = 414  ' DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_SCHEMADIALOGITEMS = 415  ' DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_CREATESCHEMA = 416  ' DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_SCHEMACACHE = 417  ' DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_STATICSNIPPETS = 418  ' DELETED FROM MANAGEMENT SITE
            SQM_CSHARP_IDE_LIVEERRORS_ONOFF = 419
            SQM_XMLEDITOR_NAMESPACE = 420  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_ERRORLIST = 421  ' DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_SNIPPETSGENERATED = 422  ' DELETED FROM MANAGEMENT SITE
            DATAID_SP_TIMETOFIRSTWINDOW = 423
            DATAID_SP_SYSTEMFREEDISKSPACE = 424
            DATAID_SP_INSTALLITEM = 425  ' (Stream) DELETED FROM MANAGEMENT SITE
            DATAID_SP_ISINTERNAL = 426
            DATAID_SP_ISADMIN = 427
            DATAID_SP_ISRETAILBUILD = 428
            DATAID_SP_DISPLAYLCID = 429
            DATAID_SP_DOWNLOADSIZE = 430
            DATAID_SP_DOWNLOADTIME = 431
            DATAID_SP_DOWNLOADITEM = 432  ' (Stream) DELETED FROM MANAGEMENT SITE
            DATAID_SP_DOWNLOADRATE = 433
            DATAID_SP_INSTALLTIME = 434
            DATAID_SP_PROCESSBLOCKINGINSTALL = 435  ' (Stream) 
            DATAID_SP_SERVICEBLOCKINGINSTALL = 436  ' (Stream) 
            DATAID_SP_OPERATIONREQUESTED = 437
            DATAID_SP_OPERATIONUI = 438
            DATAID_SP_PACKAGENAME = 439
            DATAID_SP_APPLICATIONVERSION = 440
            DATAID_SP_APPLICABLESKU = 441  ' (Stream) 
            DATAID_SP_CURRENTSTATE = 442
            DATAID_SP_RETURNCODE = 443
            DATAID_SP_MSIMESSAGE = 444  ' DELETED FROM MANAGEMENT SITE
            DATAID_SP_NUMBEROFREFRESH = 445  ' DELETED FROM MANAGEMENT SITE
            DATAID_SP_REPORTMODE = 446
            DATAID_SP_RETURNCODE2 = 447
            DATAID_SP_MSIMESSAGE2 = 448
            DATAID_SP_NUMBEROFREFRESH2 = 449
            DATAID_SP_DISPLAYLCID2 = 450
            DATAID_SP_DOWNLOADITEM2 = 451  ' (Stream) 
            DATAID_SP_INSTALLITEM2 = 452  ' (Stream) 
            DATAID_SP_OSFULLVERSION = 453
            DATAID_SP_APPLICABLEIFTIME = 454
            DATAID_SP_SYSTEMREQUIREMENTCHECKTIME = 455
            SQM_VBTHROWVIADEVGUARD = 456  ' (Stream) 
            DATAID_SP_PACKAGEVERSION = 457
            SQM_HISTORICAL_USAGE = 458  ' (Stream) 
            SQM_HISTORIC_WINDOW_DEBUG_SESSION = 459  ' (Stream) 
            SQM_LIVE_DEBUGGER_USAGE = 460  ' (Stream) 
            DATAID_SP_CURRENTITEM = 461
            DATAID_SP_ERRORPHASE = 462
            SQM_VSTT_CAMANO_SEARCH_COUNT = 463
            SQM_TFS_VC_COMMANDSOURCE = 464
            SQM_TFS_CLIENT_VERSION = 465
            SQM_TFS_VC_COMMANDRESULT = 466  ' (Stream) 
            SQM_XMLEDITOR_FILEEXTENSION2 = 467  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_FILEEXTENSION3 = 468  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_GENERATEDSCHEMAEXTENTION2 = 469 ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_XMLEDITOR_GENERATEDSCHEMAEXTENTION3 = 470 ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_CSHARP_IDE_REFACTORVERIFY_ONOFF = 471
            SQM_PKGLOAD_PKGINFO = 472  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_PKGLOAD_EXTERNAL_PKG_DEPRECATED = 473  ' (Stream) 
            SQM_PKGINST_EXTERNAL_PKG_DEPRECATED = 474  ' (Stream) 
            STRM_VSTT_CU_PROJECTS = 475  ' (Stream) 
            STRM_VSTT_PROJECTCREATE = 476  ' (Stream) 
            DP_VSTT_RNP_PLUGINS = 477
            DP_VSTT_RNP_AGG = 478
            STRM_VSTT_RNP_SESSIONINFO = 479  ' (Stream) 
            DP_VSTT_IEVER = 480
            DP_VSTT_OSVERSION = 481
            DP_VSTT_VSVERSION = 482
            DP_VSTT_OSLOCALE = 483
            DP_VSTT_VSLOCALE = 484
            DP_VSTT_VSSKU = 485
            DP_VSTT_PERFMEMORY = 486
            DP_VSTT_OSARCH = 487
            DP_VSTT_CPUCOUNT = 488
            STRM_VSTT_MTR_TCLOADED = 489  ' (Stream) 
            DP_VSTT_DISPLAYRESOLUTION = 490
            DP_VSTT_VSBUILDNUMBER = 491
            SQM_HISTORIC_LOG_EXPANDO = 492  ' (Stream) 
            DP_SETUP_OS = 493
            DP_SETUP_CHAININGPACKAGE = 494
            DP_SETUP_OSPRERELEASE = 495
            DP_SETUP_CURRENTFLAGS = 496
            DP_SETUP_MPC = 497
            DP_SETUP_ITEMSTREAM = 498  ' (Stream) DELETED FROM MANAGEMENT SITE
            DP_SETUP_BLOCKERSTREAM = 499  ' (Stream) 
            DP_SETUP_REBOOTCOUNT = 500
            DP_SETUP_RESULTDETAIL = 501
            SQM_HISTORIC_LOG_OPEN = 502  ' (Stream) 
            SQM_HISTORIC_NAV_USAGE = 503  ' (Stream) 
            SQM_HISTORIC_OPTIONS = 504  ' (Stream) DELETED FROM MANAGEMENT SITE
            DP_HISTORIC_NP_DISABLED = 505
            SQM_HISTORIC_FLAT_LIST_POPLUATE = 506  ' (Stream) 
            LAB_MTR_ON_VIRTUAL_ENV = 507
            LAB_MTR_CHECKPOINT_COUNT = 508  ' DELETED FROM MANAGEMENT SITE
            STRM_LAB_LE_CONFIG = 509  ' (Stream) 
            STRM_LAB_TWO_TFS = 510  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_LAB_LE_CONNECT_STATUS = 511  ' (Stream) 
            TEAMARCH_MODEL_USAGE = 512  ' (Stream) 
            LAB_CHECKPOINT_COUNT = 513  ' DELETED FROM MANAGEMENT SITE
            DP_SETUP_ITEMSTREAM2 = 514  ' (Stream) 
            DP_SETUP_RESULTCODE = 515
            DP_SETUP_PID_MPC = 516
            DP_SETUP_CURRENTFLAGS2 = 517
            CPUCOUNT = 518  '  DWORD64 DELETED FROM MANAGEMENT SITE
            TFSAO_TOTALWARNINGS = 519
            DEPLOYMENTINFO = 520
            PHYSICALCPUCOUNT = 521  ' DELETED FROM MANAGEMENT SITE
            CPULOGICALCOUNT = 522
            PROCESSORCLOCKSPEED = 523
            PROCESSORFAMILY = 524
            PROCESSORDATAWIDTH = 525
            PHYSICALMEMORY = 526
            CONFIGRESULTSET = 527  ' (Stream) 
            DP_SETUP_PROFILEFEATUREMAP = 528
            DP_SETUP_CUSTOMIZE = 529
            DP_SETUP_CANCELPAGE = 530
            TFSAO_SETUPOPTIONS = 531
            TFSAO_CONFIGURATIONCOMMAND = 532
            SQM_EXTENSIONMANAGEROPENED = 533  '  DWORD64 
            SQM_EXTENSIONMANAGEDACTION_DEPRICATED2 = 534 ' (Stream) 
            SQM_EXTENSIONUPDATED_DEPRICATED2 = 535  ' (Stream) 
            SQM_VSDF_USERNAME = 536
            SQM_VSDF_COMPUTERNAME = 537
            SQM_VSDF_DOMAIN = 538
            SQM_VSDF_BRANCH = 539
            DP_VSDF_EDITORBUFFERPATH = 540  ' (Stream) 
            SQM_PKGLOAD_EXTERNAL_PKG = 541  ' (Stream) 
            SQM_PKGINST_EXTERNAL_PKG = 542  ' (Stream) 
            STRM_VSTT_MTR_TCLOADED2 = 543  ' (Stream) 
            STRM_PCP_TASKS = 544  ' (Stream) 
            STRM_PCP_STACKS = 545  ' (Stream) 
            SQM_HISTORIC_OPTION_DEBUG = 546  ' (Stream) 
            SQM_HISTORIC_NP_STATE = 547  ' (Stream) 
            PROCCLOCKSPEED = 548
            PHYSICALNUMBERCPU = 549
            PROCFAMILY = 550
            PROCDATAWIDTH = 551
            RAM = 552
            FULLCONFIGRESULTSET = 553  ' (Stream) 
            STRM_PCP_ERRORS = 554  ' (Stream) 
            DP_SETUP_FLAGS = 555
            STRM_BIZAPPSSHAREPOINTPROJECTS = 556  ' (Stream) 
            STRM_BIZAPPSSHAREPOINTITEMS = 557  ' (Stream) 
            SQM_EXTENSIONMANAGERTOTALINSTALLEDEXTENSIONS = 558
            DP_SETUP_PID_EDITION = 559
            DP_SETUP_PID_ORIGEDITION = 560
            DP_SETUP_PID_RANGE = 561
            DP_SETUP_PID_ORIGRANGE = 562
            DP_SETP_PID_INSTALLEDSKUS = 563
            DP_ISDOMAINMEMBER = 564
            HLP3_HELPOPTIONS = 565  ' DELETED FROM MANAGEMENT SITE
            SQM_SESSIONFRAGMENT_INFO = 566  ' (Stream) 
            INTERNAL_EXTERNAL_DATA = 567
            HELP3_HELPOPTIONS = 568  ' (Stream) 
            DP_SETUP_PACKAGETYPE = 569
            DP_SETUP_PATCHSTREAM = 570  ' (Stream) 
            DP_SETUP_PATCHTYPE = 571
            DP_SETUP_BUILDTYPE = 572
            DP_SETUP_BUILDBRANCH = 573
            SQM_VSTT_CAMANO_ACTIVITY_LAUNCH_STATS = 574 ' (Stream) 
            STRM_VSTT_CODEDUITESTBUILDERUSAGE = 575  ' (Stream) 
            STRM_LAB_LERIG_STATUS = 576  ' (Stream) DELETED FROM MANAGEMENT SITE
            WINETR_EE_SLN_GEN_EVENT = 577  ' (Stream) 
            WINETR_IDE_DEPLOY_EVENT = 578  ' (Stream) 
            WINETR_SDINT_SRCCTRL_ENABLED = 579
            WINETR_SDINT_SHOWDIFFS = 580  ' (Stream) 
            WINETR_EE_OPENED_TYPE = 581  ' (Stream) 
            WINETR_BUILD_EVENT = 582  ' (Stream) 
            WINETR_SDINT_CHECKIN = 583  ' (Stream) 
            WINETR_SDINT_SHOWHIST = 584  ' (Stream) 
            WINETR_KD_DEBUG = 585  ' (Stream) 
            WINETR_EE_SLN_GEN_ERROR = 586
            WINETR_SA_VIEWER_ICON_LAUNCH = 587
            WINETR_SA_VIEWER_ANALYSIS_EVENT = 588  ' (Stream) 
            WINETR_SA_VIEWER_SELECT_DEFECT_EVENT = 589  ' (Stream) 
            WINETR_SA_VIEWER_SELECT_MOREINFO = 590
            STRM_LAB_LS_CONFIG_EC = 591  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_LAB_LS_TEST_EC = 592  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_LAB_LS_BUILD_EC = 593  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_LAB_LS_FENCE_EC = 594  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VSTT_MTR_S2LOADED = 595  ' (Stream) 
            DP_SETUP_MSIVERSION = 596
            HELP3_ONLINEQUERY = 597  ' (Stream) 
            HELP3_OFFLINEQUERY = 598  ' (Stream) 
            DP_SETUP_SOURCETYPE = 599
            STRM_VSTT_CAMANO_STREAMING_STATS = 600  ' (Stream) 
            HELP3_HLMLAUNCH = 601  ' (Stream) 
            HELP3_HLMACTIONS = 602  ' (Stream) 
            SQM_DP_ACTIVATEDATASET_DEV10 = 603
            SQM_STRM_CLASSDESIGNER_CLOSED_DEV10 = 604  ' (Stream) 
            SQM_DP_CONTROLBROWSER_DEV10 = 605  ' DELETED FROM MANAGEMENT SITE
            SQM_STRM_SYNCDESIGNER_DEV10 = 606  ' (Stream) 
            SQM_STRM_DRAGDROP_DEV10 = 607  ' (Stream) 
            SQM_STRM_DSWIN_DEV10 = 608  ' (Stream) 
            SQM_STRM_VBPOWERPACKS_DEV10 = 609  ' (Stream) 
            SQM_DP_ADONETCOMPONENT_DEV10 = 610
            SQM_DP_PREVIEWDATA_DEV10 = 611
            SQM_DP_ADDNEWDATASET_DEV10 = 612
            SQM_STRM_DATASOURCEWIZARD_DEV10 = 613  ' (Stream) 
            STRM_DP_PROVIDERDATASOURCE_DEV10 = 614
            SQM_DP_DSWIN_REFRESHFREQUENCY_DEV10 = 615
            DP_SETUP_REBOOTPENDING = 616
            SQM_VSTT_CAMANO_ACTION_PERFORM_STATS = 617  ' (Stream) 
            STRM_VSDB_PERMISSIONMAINTAINED = 618  ' (Stream) 
            STRM_VSDB_PROJECT_SWITCH = 619  ' (Stream) 
            STRM_HISTORIC_ACCESS_CALLTREE_VIEW = 620  ' (Stream) 
            STRM_HISTORIC_SEARCH_RESULTS = 621  ' (Stream) 
            STRM_HISTORIC_SEARCH_RESULTS_NAV = 622  ' (Stream) 
            STREAM_HISTORIC_SEARCH_CONTROL_TYPE = 623  ' (Stream) 
            STRM_HISTORIC_NP_DISABLED = 624  ' (Stream) 
            STRM_VSDB_PERFORMANCE = 625  ' (Stream) 
            STRM_VSDB_EXTENSIBILITY = 626  ' (Stream) 
            STRM_VSDB_ADD_REFERENCE = 627  ' (Stream) 
            STRM_VSDB_FEATURES_EXERCISED = 628  ' (Stream) 
            SQM_DEBUGGER_STEP = 629  ' (Stream) 
            STRM_BIZAPPSSHAREPOINTITEMTYPE = 630  ' (Stream) 
            PROFILER_REPORT_STREAM = 631  ' (Stream) DELETED FROM MANAGEMENT SITE
            NUM_CODE_PIVOT_VIEW = 632
            NUM_TEST_PIVOT_VIEW = 633
            NUM_CALLING_PIVOT_VIEW = 634
            NUM_RUN_CLICKS_CODE_PIVOT = 635
            NUM_RUN_CLICKS_TEST_PIVOT = 636
            NUM_RUN_CLICKS_CALLING_PIVOT = 637
            NUM_BUILDS = 638
            TIA_STREAM = 639  ' (Stream) 
            STRM_VSDB_SQLERROR = 640  ' (Stream) 
            SQM_PROFILER_NUM_HPC_LAUNCHES = 641
            DP_SETUP_CURRENTITEMSTEP = 642
            SQM_EXTENSIONUPDATED = 643  ' (Stream) 
            SQM_EXTENSIONMANAGEDACTION = 644  ' (Stream) 
            SQM_OSARCH = 645
            SQM_PROCESSOR_DATAWIDTH = 646
            SQM_VIRTUALMACHINE_INFO = 647  ' (Stream) 
            STRM_ENV_TYPE = 648  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_DEBUGGER_SESSION_PARAMS = 649  ' (Stream) 
            SQM_RENDERCAPABILITYTIER = 650
            INSTALLSHIELDCREATED = 651
            PROFILER_REPORT_STREAM_1 = 652  ' (Stream) 
            WINIDE_PKGING_EVENT1 = 653  ' (Stream) 
            HELP3_OSVERSION = 654
            HELP3_OSSERVICEPACK = 655
            HELP3_HLMVERSION = 656
            HELP3_HLAVERSION = 657
            MACHINEID = 658
            NUM_RUN_ALL_IMPACTED_TESTS = 659
            NUM_RUN_SELECTED_IMPACTED_TESTS = 660
            NUM_DEBUG_ALL_IMPACTED_TESTS = 661
            NUM_DEBUG_SELECTED_IMPACTED_TESTS = 662
            NUM_RUN_CALLING_TESTS = 663
            NUM_BUILDS_WITH_CODE_CHANGES = 664
            SQM_LOCALVER_CMDPROJECTSYNCHTOCHECKPOINT = 665
            SQM_LOCALVER_CMDPROJECTCREATECHECKPOINT = 666
            SQM_ISREMOTEDESKTOP = 667
            SQM_VIRTUALMEMORYUSAGE = 668  ' (Stream) 
            TIA_STREAM_1 = 669  ' (Stream) 
            STRM_EXTENSIONMANAGERACTIONRAW = 670  ' (Stream) 
            SQM_EXTENSIONUPDATEDRAW = 671  ' (Stream) 
            STRM_TOOLBOXCONTROLUSED = 672  ' (Stream) 
            SQM_VSSTARTUPOPTION = 673
            STRM_CMDHISTORY = 674  ' (Stream) 
            DATAID_SQM_DEBUGGER_SESSION_PARAMS_2 = 675  ' (Stream) 
            SQM_VIRTUALMACHINETYPE = 676
            SQM_VIRTUALMACHINEVERSION = 677
            SQM_VIRTUALMACHINEHOST = 678
            SQM_VIRTMEM_ATTHECLIFF = 679
            SQM_VIRTMEM_LARGESTFREEBLOCK = 680
            SQM_VIRTMEM_TOTALFREEMEMORY = 681
            SQM_VIRTMEM_TOTALCOMMITTEDMEMORY = 682
            SQM_VIRTMEM_TOTALRESERVEDMEMORY = 683
            SQM_VIRTMEM_TOTALIMAGEMEMORY = 684
            SQM_VIRTMEM_TOTALMAPPEDMEMORY = 685
            SQM_VIRTMEM_TOTALPRIVATEMEMORY = 686
            SQM_VISUALEFFECTS_AUTODETECT = 687
            SQM_VISUALEFFECTS_USEHARDWAREACCELERATION = 688
            SQM_WPF_HARDWAREACCELERATIONOPTION = 689
            SQM_WPF_MAXMULTISAMPLEVALUE = 690
            SQM_WPF_REQUIREDVIDEODRIVERDATE = 691
            SQM_WPF_USEREFERENCERASTERIZER = 692
            SQM_VIDEOINFO_VIDEOCARD = 693  ' DELETED FROM MANAGEMENT SITE
            SQM_VIDEOINFO_HARDWAREID = 694  ' DELETED FROM MANAGEMENT SITE
            SQM_VIDEOINFO_DRIVERDATE = 695  ' DELETED FROM MANAGEMENT SITE
            SQM_VIDEOINFO_DRIVERVERSION = 696  ' DELETED FROM MANAGEMENT SITE
            SQM_VIDEOINFO_ADAPTERCOUNT = 697  ' DELETED FROM MANAGEMENT SITE
            SQM_VIDEOINFO_ADAPTER = 698  ' (Stream) 
            SQM_VIDEOINFO_MEMORYSIZE = 699  '  DWORD64 DELETED FROM MANAGEMENT SITE
            SQM_STRM_DISPLAYDEVICEINFO = 700  ' (Stream) 
            SQM_DP_DISPLAYDEVICESCOUNT = 701
            SQM_VIDEOINFO_ADAPTER_COUNT = 702
            STRM_LABSVC_GENERALUSAGE = 703  ' (Stream) 
            DP_LABSVC_VSBUILDNUMBER = 704
            DP_LABSVC_INTERNALEXTERNAL = 705
            WINETR_EE_GENERAL_USERTYPE = 706
            SQM_CODEANALYSIS_USAGE_RULESETSELECTION_FROMPROJECTPROPERTY = 707 ' (Stream) 
            WINETR_EE_HELP_USAGE = 708  ' (Stream) 
            WINETR_GENERAL_FEATURE_SEQUENCE = 709
            WINETR_CODE_COVERAGE_BASIC = 710
            SQM_CCT_PACKAGEVERSION = 711
            SQM_CCT_AZURE_TOOLS_ERROR = 712  ' (Stream) 
            SQM_VSUIAVERSION = 713
            SQM_CCT_BUILDNUMBER = 714
            SQM_CCT_BUILDDATE = 715
            SQM_DOCWELLEXTOPTIONS = 716  ' (Stream) 
            WINIDE_RESEARCH_PLATFORM_SEARCHSESSIONINVOKED = 717 ' (Stream) 
            WINIDE_RESEARCH_PLATFORM_WINDOWSTATEONCLOSE = 718
            WINIDE_RESEARCH_CODESEARCH_SEARCHSESSION = 719 ' (Stream) 
            WINIDE_RESEARCH_CODESEARCH_RESULTOPENEDINEDITOR = 720 ' (Stream) 
            WINIDE_RESEARCH_CODESEARCH_PREVIEWLOADTIME = 721 ' (Stream) 
            WINIDE_RESEARCH_PLATFORM_DEFAULTSCOPESET = 722
            WINIDE_RESEARCH_CODESEARCH_REFERENCEBARFILTERTOOLTIPUSED = 723 ' (Stream) 
            WINIDE_RESEARCH_CODESEARCH_REFERENCEBAROPERATORTOOLTIPUSED = 724 ' (Stream) 
            WINIDE_RESEARCH_CODESEARCH_REFERENCEBARFILTERCLICKED = 725 ' (Stream) 
            WINIDE_RESEARCH_CODESEARCH_REFERENCEBAROPERATORCLICKED = 726 ' (Stream) 
            WINIDE_RESEARCH_CODESEARCH_RESULTFILTERCLICKED = 727 ' (Stream) 
            WINIDE_RESEARCH_CODESEARCH_PREVIEWFILTERCLICKED = 728 ' (Stream) 
            DP_WINIDE_RESEARCH_PLATFORM_MAXTABCOUNT = 729
            STRM_WINIDE_RESEARCH_CODESEARCH_PREVIEWFAILED = 730 ' (Stream) 
            WINETR_SA_OACRVIEWER = 731
            WINETR_EE_GENERAL_USERALIAS_HASH = 732
            WINETR_SA_WARNINGSTREAM = 733  ' (Stream) 
            WINETR_SA_GENERATEDRESULT = 734  ' (Stream) 
            WINETR_EE_GENERAL_VERSION = 735
            STRM_HISTORIC_DIAGNOSTIC_EVENTS_CHANGED = 736 ' (Stream) 
            SQM_STRM_DSWIN_SESSION = 737  ' (Stream) DELETED FROM MANAGEMENT SITE
            WINETR_GENERAL_VSSKUS = 738  ' (Stream) 
            STRM_XAMLFILEINFO = 739  ' (Stream) 
            STRM_XAMLFEATURES = 740  ' DELETED FROM MANAGEMENT SITE
            STRM_XAMLPANEUSE = 741  ' (Stream) 
            STRM_XAMLFEATUREUSE = 742  ' (Stream) 
            SQM_VSP_IDE_SOLUTION_NAVIGATOR = 743  ' (Stream) 
            DP_VSP_SNRESCOPEENABLED = 744
            DP_VSP_SNTOOLTIPENABLED = 745
            SQM_VSP_IDE_PROPACK = 746  ' (Stream) 
            DP_VSP_SNEXPANSIONENABLED = 747
            SQM_WORKFLOWDESIGNER_ACTIVITYUSAGECOUNT = 748 ' (Stream) 
            SQM_WORKFLOWDESIGNER_FEATUREUSAGECOUNT = 749 ' (Stream) 
            SQM_DOCWELLEXTPRESET = 750
            SQM_STRM_DSWIN_SESSION2 = 751  ' (Stream) 
            SQM_VSSTARTUPTIME = 752
            SQM_TFS_VC_MANUALMERGE = 753  ' (Stream) 
            SQM_TFS_VC_AUTOMERGE = 754  ' (Stream) 
            SQM_DP_RIASERVICES_QUERYMETHODCOUNT = 755
            SQM_DP_RIASERVICES_DOMAINCONTEXTS_RELOADTIME = 756
            SQM_DP_RIASERVICES_DOMAINCONTEXT_RELOADINTERVAL = 757
            SQM_DP_RIASERVICES_UI_NOBUILD = 758
            SQM_DP_RIASERVICES_UI_PARAMETERCOUNT = 759
            SQM_TFS_VC_SERVERINFORMATION = 760  ' (Stream) 
            STRM_DEPLOYDETAILS = 761  ' (Stream) 
            SQM_WAT_PROJECT_ROLES = 762  ' (Stream) DELETED FROM MANAGEMENT SITE
            ACTIONID = 763  ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_WAT_PROJECT_ROLES_STRM = 764  ' (Stream) 
            STRM_PROGRESSIONGRAPHSTATISTICS = 765  ' (Stream) 
            STRM_STANDARDGRAPHOPERATIONS = 766  ' (Stream) 
            PROGRESSIONGRAPHCLICKS = 767  ' (Stream) 
            STRM_PROGRESSIONBROWSERCLICKS = 768  ' (Stream) 
            STRM_PROGRESSIONACTIONUSAGE = 769  ' (Stream) 
            STRM_VSTT_LOADUSAGE = 770  ' (Stream) 
            SYM_NUMBEROFENTITIESINAPP = 771  '  DWORD64 DELETED FROM MANAGEMENT SITE
            SYM_DEPLOYEDAPPLICATIONTYPE = 772  ' DELETED FROM MANAGEMENT SITE
            SYM_NUMBEROFSCREENSINAPP = 773  '  DWORD64 DELETED FROM MANAGEMENT SITE
            SYM_ISINTRINSICDATABASEUSED = 774  ' DELETED FROM MANAGEMENT SITE
            STRM_DEPLOYMENTSTREAM1 = 775  ' (Stream) 
            STRM_USEDEXTENSIONSSTREAM = 776  ' (Stream) 
            STRM_USEDTHEMESSTREAM = 777  ' (Stream) 
            STRM_USESSCREENTEMPLATESTHEME = 778  ' (Stream) 
            STRM_ATTACHEDSQLDATABASEVERSIONSTREAM = 779 ' (Stream) 
            SQM_STARTUPAPPBUILDNUMBERSTRING = 780
            WINIDE_ATMETRICS_WARNINGSTREAM = 781  ' (Stream) 
            WINIDE_ATMETRICS_PROJECTNAME = 782
            WINIDE_ATMETRICS_BUILDFLAVORANDSESSIONID = 783
            WINIDE_ATMETRICS_BRANCHNAME = 784
            WINIDE_ATMETRICS_LONGESTCOMMONROOT = 785
            WEBPLAT_DP_USAGE_TIME = 786  '  DWORD64 
            WEBPLAT_DP_LOCALE = 787
            WEBPLAT_DP_GENERAL_FEATURE_SEQUENCE = 788  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_TIME_IN_WORKSPACES = 789  ' (Stream) DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_SITE_START_TYPE = 790  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_SITE_FRAMEWORK = 791  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_APP_GALLERY_APP = 792  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_APP_INSTALL_TIME = 793  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_APP_GALLERY_FAILURE = 794  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_WEBPI_INSTALL_TYPE = 795  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_FWH_CLICK = 796  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_IMPORT_PROFILE = 797  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_PUBLISH_PROTOCOL_TYPE = 798  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_PUBLISH = 799  ' DELETED FROM MANAGEMENT SITE
            WEBPLAT_DP_PUBLISH_FAILURE_CODE = 800  ' DELETED FROM MANAGEMENT SITE
            DP_SETUP_RM_LASTUSERRESPONSE = 801
            V_SETUP_RM_LASTDIALOGRESPONSETIME = 802
            DP_SETUP_RM_LASTTIMETOCLOSEAPPS = 803
            DP_SETUP_RM_TOTALATTEMPTSCOUNT = 804
            V_SETUP_REBOOT_IGNORED = 805
            DP_SETUP_RM_INITIAL_APPS_COUNT = 806
            DP_SETUP_RM_CRITICALAPPSCOUNT = 807
            DP_SETUP_RM_EXTERNALUI_VER = 808
            DP_SETUP_RMFILESTREAM = 809  ' (Stream) 
            DP_SETUP_RMAPPLICATIONSTREAM = 810  ' (Stream) 
            WEBPLAT_STRM_CMDHISTORY = 811  ' (Stream) 
            WEBPLAT_STRM_APP_GALLERY_INSTALL = 812  ' (Stream) 
            WEBPLAT_STRM_PUBLISH_INFO = 813  ' (Stream) 
            WEBPLAT_STRM_SITE_INFO = 814  ' (Stream) DELETED FROM MANAGEMENT SITE
            WEBPLAT_STRM_TIME_IN_WORKSPACES = 815  ' (Stream) 
            WEBPLAT_STRM_FILE_OPEN = 816  ' (Stream) 
            WEBPLAT_STRM_DATABASE_CONNECTIONS = 817  ' (Stream) 
            WEBPLAT_STRM_REPORTS_INFO = 818  ' (Stream) 
            WEBPLAT_STRM_IMPORT_PROFILE = 819  ' (Stream) 
            WEBPLAT_DP_OSVERSION = 820
            SETUP_ACQUISITIONSIZE = 821
            SETUP_ACQUISITIONTIME = 822
            SETUP_BUNDLERESULT = 823
            SETUP_CUSTOMPATH = 824
            SETUP_FREEDISKSPACE_APP = 825
            SETUP_MAXDISKSPACE_APP = 826
            SETUP_MAXDISKSPACE_SYS = 827
            SETUP_REQUIREDDISKSPACE_APP = 828
            SETUP_REQUIREDDISKSPACE_SYS = 829
            SETUP_USEDDISKSPACE_APP = 830
            SETUP_USEDDISKSPACE_SYS = 831
            SETUP_FEATUREADMINMAP = 832
            SETUP_FROMADMINFILE = 833
            SETUP_FULL = 834
            SETUP_INITIALFEATUREMAP = 835
            SETUP_INSTALLTIME = 836
            SETUP_INTERRUPTCOUNT = 837
            SETUP_LANGSINSTALLED = 838
            SETUP_LPINSTALL = 839  ' DELETED FROM MANAGEMENT SITE
            SETUP_SOURCEPROMPTS = 840
            SETUP_VMTYPE = 841
            SETUP_ACQUISITIONSTREAM = 842  ' (Stream) 
            SETUP_INTERRUPTSTREAM = 843  ' (Stream) 
            SETUP_PACKAGESTREAM = 844  ' (Stream) 
            STRM_VS_EXTENSIONS_INSTALLED = 845  ' (Stream) 
            STRM_VSTLM_FB_FBTOOLSESSION1 = 846  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VSTLM_FB_FBUSERSTORYSESSION1 = 847  ' (Stream) DELETED FROM MANAGEMENT SITE
            WEBPLAT_STRM_APP_GALLERY_INSTALL2 = 848  ' (Stream) 
            WEBPLAT_STRM_PUBLISH_INFO2 = 849  ' (Stream) 
            SQM_CV_LAUNCHES_ATTACH = 850
            SQM_CV_LAUNCHES_START = 851
            SQM_CV_LAUNCHES_LAUNCH = 852
            SQM_CV_LAUNCHES_OPEN = 853
            SQM_CV_LAUNCHES_SETTINGS = 854
            SQM_CV_LAUNCHES_ADDSDK = 855
            SQM_CV_VIEW_BEHAVIOR = 856  ' (Stream) 
            SQM_CV_TRACE_DATA = 857  ' (Stream) 
            STRM_VSEXTENSIONINSTALLED = 858  ' (Stream) 
            STRM_VSEXTENSIONUSED = 859  ' (Stream) 
            DP_WPPROJECTVERSION = 860
            HELPVIEWER_OSVERSION = 861
            HELPVIEWER_OSSERVICEPACK = 862
            HELPVIEWER_HLPVIEWERVERSION = 863
            STRM_BIZAPPSSHAREPOINTPROJECTS_DEV11 = 864  ' (Stream) 
            STRM_BIZAPPSSHAREPOINTITEMS_DEV11 = 865  ' (Stream) 
            HELPVIEWER_OFFLINEF1 = 866  ' (Stream) 
            HELPVIEWER_TOPICNAVSOURCE = 867  ' (Stream) 
            CAMANO_ISHOSTEDTFS = 868
            VSHELP_FIRSTRUNHELPINSTALLSELECTION = 869
            VSHELP_SETHELPPREFERENCE = 870  ' (Stream) 
            STRM_WPPROJECTUPGRADE = 871  ' (Stream) 
            STRM_DP_VSTT_UT_SESSIONINFO = 872  ' (Stream) 
            STRM_VSTT_XT1 = 873  ' (Stream) 
            VSTLM_WIN8 = 874  ' (Stream) 
            STRM_WPDEVICEUNLOCKTOOL = 875  ' (Stream) 
            STRM_WPPROFILERDATA = 876  ' (Stream) 
            STRM_WPPROFILERANALYZERS = 877  ' (Stream) 
            SETUP_DEFAULTFEATUREMAP = 878
            DP_WINSIM_OSVERSION = 879
            DP_WINSIM_OSSERVICEPACK = 880
            DP_WINSIM_OSSKU = 881
            DP_WINSIM_CPUCOUNT = 882
            DP_WINSIM_PROCFREQ = 883
            DP_WINSIM_MEMORY = 884
            DP_WINSIM_DISPLAYCOUNT = 885
            DP_WINSIM_ISREMOTEDESKTOP = 886
            DP_WINSIM_ISVMHOST = 887
            DP_WINSIM_USERTYPE = 888
            DP_WINSIM_STARTTIME = 889
            DP_WINSIM_SHUTDOWNTIME = 890
            DP_WINSIM_ALREADYRUNNING = 891
            DP_WINSIM_TOUCHDEVICECOUNT = 892
            DP_WINSIM_CMDSTREAM = 893  ' (Stream) 
            DP_WINSIM_LOCSENSORCOUNT = 894
            DP_WINSIM_LOCSENSORENABLED = 895
            DP_WINSIM_OSBUILD = 896
            DP_STREAM_WINSIM_DIMENSIONS = 897  ' (Stream) 
            STRM_WPMARKETPLACETESTKIT = 898  ' (Stream) 
            RTDISTICTUSERS = 899  ' DELETED FROM MANAGEMENT SITE
            DEPLOYMENTINFO11 = 900  ' DELETED FROM MANAGEMENT SITE
            TFSAO_SETUPOPTIONS11 = 901
            PHYSICALNUMBERCPU11 = 902
            PROCCLOCKSPEED11 = 903
            PROCFAMILY11 = 904
            PROCDATAWIDTH11 = 905
            RAM11 = 906
            STRM_VSTLM_FB_FBTOOLSESSION = 907  ' (Stream) 
            STRM_VSTLM_FB_FBUSERSTORYSESSION = 908  ' (Stream) 
            STRM_VSTT_XT_USERSTORYSESSION = 909  ' (Stream) 
            CPULOGICALCOUNT11 = 910
            TFSAO_11_FULLCONFIGRESULTS = 911  ' (Stream) 
            TFSAO_RUNTIME11 = 912  ' (Stream) 
            STRM_DEBUGGER_LAUNCH = 913  ' (Stream) 
            STRM_GETWIN8DEVLICENSE = 914  ' (Stream) 
            STRM_WIN8APPDEPLOYFAILURE = 915  ' (Stream) 
            STRM_WIN8APPDEPLOYPERFORMANCE = 916  ' (Stream) 
            WEBPLAT_DP_LOCALE_2 = 917
            SQM_CODEANALYSIS_USAGE_NOVIOLATIONBUILDS = 918 ' (Stream) 
            SQM_CODEANALYSIS_ANALYSIS_NEWVIOLATIONS = 919 ' (Stream) 
            STRM_VSTLM_MFB_SESSION = 920  ' (Stream) 
            STRM_JAVASCRIPT_COMPLETIONVSFILEIDENTIFIERLIST = 921 ' (Stream) 
            STRM_JAVASCRIPT_GOTODEFINITIONNAVIGATION = 922 ' (Stream) 
            STRM_WAT_PROJECT_CREATION = 923  ' (Stream) 
            STRM_WAT_PROJECT_ROLES = 924  ' (Stream) 
            WEBPLAT_DP_CPU_COUNT = 925
            WEBPLAT_DP_DISPLAYCOUNT = 926
            WEBPLAT_DP_MEMORY = 927
            WEBPLAT_DP_STARTUP_TIME = 928  '  DWORD64 
            WEBPLAT_STRM_OPENED_AFTER_FIRST_LAUNCH = 929 ' (Stream) 
            STRM_WAT_PROJECT_COUNT = 930  ' (Stream) 
            STRM_WAT_ROLE_TEMPLATE = 931  ' (Stream) 
            WEBPLAT_STRM_FILE_ADDED = 932  ' (Stream) 
            WEBPLAT_STRM_NUGET_PACKAGES = 933  ' (Stream) 
            WEBPLAT_STRM_SITE_OPEN_TIME = 934  ' (Stream) 
            STRM_PROJECTMIGRATE = 935  ' (Stream) 
            WEBPLAT_STRM_EXTENSION_GALLERY = 936  ' (Stream) 
            WEBPLAT_DP_REMOTE_TAB = 937
            WEBPLAT_STRM_REMOTE_BUTTONS = 938  ' (Stream) 
            WEBPLAT_STRM_REMOTE_FILE = 939  ' (Stream) 
            WEBPLAT_STRM_LEARN_OPEN = 940  ' (Stream) 
            WEBPLAT_STRM_REPORTS_ADVANCED_SETTINGS = 941 ' (Stream) 
            WEBPLAT_STRM_LEARN_FEED = 942  ' (Stream) 
            WEBPLAT_DP_LEARN_LINKS_CLICK = 943
            WEBPLAT_STRM_DISPLAY_RESOLUTION = 944  ' (Stream) 
            STRM_DEBUGCANVASOPTIONS = 945  ' (Stream) 
            STRM_WAT_PACKAGE_DETAILS = 946  ' (Stream) 
            STRM_ERRORLISTFILTER = 947  ' (Stream) 
            STRM_QUICKLAUNCH_SHOWPREVIOUSRESULTS = 948  ' (Stream) 
            STRM_WINDOWMGMT_PREVIEWTAB = 949  ' (Stream) 
            STRM_WINDOWMGMT_PREVIEWTAB_FINDRESULTS = 950 ' (Stream) 
            STRM_WINDOWMGMT_PINNEDINSEPERATEROW = 951  ' (Stream) 
            STRM_WINDOWMGMT_SHOWPINBUTTONINUNPINNEDTABS = 952 ' (Stream) 
            STRM_WINDOWMGMT_PINSTATUSMAINTAIN = 953  ' (Stream) 
            STRM_WINDOWMGMT_INSERTNEWTABTORIGHT = 954  ' (Stream) 
            STRM_WINDOWMGMT_FLOATINGTABWELLSONTOP = 955 ' (Stream) 
            STRM_WINDOWMGMT_FLOATINGTOOLWINDOWSONTOP = 956 ' (Stream) 
            DP_VSTT_RNP_APPLICATIONTYPE = 957
            STRM_TOOLSOPT_WINDOWMGMT_PREVIEWTAB_SOLEXP = 958 ' (Stream) 
            STRM_QUICKLAUNCH_CATEGORYSELECTED = 959  ' (Stream) 
            STRM_OPTIONSTHEMECHANGES = 960  ' (Stream) 
            STRM_SOLEXP_PIVOTRELATIONSHIPDYNAMICMENU = 961 ' (Stream) 
            STRM_SOLEXP_SEARCHSTARTEDCOUNT = 962  ' (Stream) 
            STRM_TOOLSOPT_QUICKLAUNCH_ENABLEDISABLE = 963 ' (Stream) 
            STRM_SOLUTONLOAD = 964  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_PROJECTTYPE = 965  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_INITIALIZEDTWGUIDS = 966  ' (Stream) DELETED FROM MANAGEMENT SITE
            GPU_THREADS_USAGE = 967  ' (Stream) 
            PARALLEL_WATCH_USAGE = 968  ' (Stream) 
            THREADS_IN_SOURCE_TOOLTIP_USAGE = 969  ' (Stream) 
            SETUP_APPLYTIME = 970
            GPU_DEBUGGING_SESSION = 971  ' (Stream) 
            STRM_QUICKLAUNCH_SEARCHSTARTCOUNT = 972  ' (Stream) 
            STRM_QUICKLAUNCH_FOCUSINPUTTYPE = 973  ' (Stream) 
            VSTLM_WIN8_APP_DEPLOY = 974  ' (Stream) 
            STRM_SOLUTONLOAD2 = 975  ' (Stream) 
            STRM_INITIALIZEDTWGUIDS2 = 976  ' (Stream) 
            STRM_PROJECTTYPE2 = 977  ' (Stream) 
            DP_WINSIM_LOGINPROMPTS = 978
            DP_SETUP_FAILCOUNT = 979
            DP_SETUP_CURRENTPAYLOAD = 980
            DP_SETUP_USINGREDIRECTOR = 981
            DP_APPVVERSION = 982
            DP_STRM_TOOLSTREAM = 983  ' (Stream) 
            DP_SPINSTALLER_APPLICATIONNAME = 984
            STRM_WAT_PACKAGE_DETAILS_17 = 985  ' (Stream) 
            HELPVIEWER_USERTYPE = 986
            STRM_WINDOWMGMT_PREVIEWTABCOUNT = 987  ' (Stream) 
            STRM_WAT_ROLE_TEMPLATE_WITH_GUID = 988  ' (Stream) 
            DP_ISXRAYENABLED = 989
            STRM_XRAYEXTENSIONSIGNORED = 990  ' (Stream) 
            STRM_XRAYEXTENSIONLOADTIME = 991  ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_WAT_ROLE_CACHE = 992  ' (Stream) 
            STRM_WAT_PROJECT_CACHE = 993  ' (Stream) 
            DP_WPPRODUCTID = 994
            STRM_XRAYLOADTIMES = 995  ' (Stream) 
            DP_SETUP_TOOLRESULT = 996
            STRM_WPSIMULATIONDATA = 997  ' (Stream) 
            STRM_TB_ITEMUSED = 998  ' (Stream) 
            STRM_TB_REFRESH = 999  ' (Stream) 
            DP_TB_CHOOSTBBROWSECOUNT = 1000
            STRM_TB_CACHEREBUILDTIME = 1001 ' (Stream) 
            DP_TB_OPERATIONFLAGS = 1002 ' (Stream) 
            DP_TB_OPERATION_ADDTABCOUNT = 1003
            DP_TB_OPERATION_REMOVETABCOUNT = 1004
            DP_TB_OPERATION_RENAMETABCOUNT = 1005
            DP_TB_OPERATION_REORDERTABCOUNT = 1006
            DP_TB_OPERATION_MOVEITEMWITHINTABCOUNT = 1007
            DP_TB_OPERATION_MOVEITEMBETWEENTABSCOUNT = 1008
            STRM_WPADDPROJECTREFERENCE = 1009 ' (Stream) 
            STRM_PROGRESSIONGRAPHUSERACTIONS = 1010 ' (Stream) 
            DP_WPMACHINESLATSTATE = 1011
            SQM_OSUSERLOCALE = 1012
            SQM_USEROSUILOCALE = 1013
            STRM_WPPROFILERWARNINGS = 1014 ' (Stream) 
            SQM_PROFILER_LAUNCH_TARGET = 1015 ' DELETED FROM MANAGEMENT SITE
            SQM_PROFILER_NUM_LOCAL_LAUNCHES = 1016
            SQM_PROFILER_NUM_SIMULATOR_LAUNCHES = 1017
            SQM_PROFILER_NUM_REMOTE_LAUNCHES = 1018
            SQM_PROFILER_NUM_METRO_LAUNCHES = 1019
            SQM_PROFILER_NUM_CLASSIC_LAUNCHES = 1020
            STRM_VSWEBPUBLISH_PUBLISHMETHOD = 1021 ' (Stream) 
            STRM_ERRORLIST_TOGGLESTATE = 1022 ' (Stream) 
            STRM_EXPSQM = 1023 ' (Stream) 
            STRM_LAUNCHELAPSEDTIME = 1024 ' (Stream) 
            STRM_WPDEPLOYDEBUGDATA = 1025 ' (Stream) 
            DP_WPSAVEDSTATECREATION = 1026
            STRM_WPAPPMONLINKCLICKED = 1027 ' (Stream) 
            STRM_WPAPPMONALERTCOUNT = 1028 ' (Stream) 
            STRM_WPAPPMONDETAILEDVIEWNAVIGATION = 1029 ' (Stream) 
            STRM_WPPROJECTCREATE = 1030 ' (Stream) 
            STRM_PROJECTFILEDETAILS = 1031 ' (Stream) 
            STRM_PROJECTLIBRARIES = 1032 ' (Stream) 
            STRM_PROJECTPROPERTIES = 1033 ' (Stream) 
            STRM_PROJECTREFERENCES = 1034 ' (Stream) 
            STRM_SOLUTIONFILEDETAILS = 1035 ' (Stream) 
            DP_VC_BUILDTIMETEST = 1036
            DP_WAT_SUBSCRIPTIONS_ALL = 1037
            DP_WAT_SUBSCRIPTIONS_DEFAULT_ENDPOINT = 1038
            STRM_APPPACKAGEWIZARD = 1039 ' (Stream) 
            STRM_APPPACKAGEBUILDERRORS = 1040 ' (Stream) 
            DP_APPPACKAGEBUILDSUCCESSWITHGENERATEDMANIFEST = 1041
            APPPACKAGEBUILDSUCCESSWITHCUSTOMMANIFEST = 1042
            DP_APPPACKAGEBUILDFAILWITHGENERATEDMANIFEST = 1043
            DP_APPPACKAGEBUILDFAILWITHCUSTOMMANIFEST = 1044
            DP_MANIFESTDESIGNERINTERACTION = 1045 ' (Stream) 
            DP_MANIFESTDESIGNERCAPABILITYAPI = 1046 ' (Stream) 
            STRM_DEBUGGER_NOSOURCEWINDOWREASON = 1047 ' (Stream) 
            STRM_DEBUGGER_DUMPSUMMARY = 1048 ' (Stream) 
            STRM_MULTISCALEIMAGEINSTANCE = 1049 ' (Stream) 
            STRM_MANIFESTMULTISCALEIMAGEINSTANCE = 1050 ' (Stream) 
            JSSNAPSHOTINFO = 1051 ' (Stream) 
            ZEPHYRSNAPSHOTVIEWS = 1052 ' (Stream) 
            JSSNAPSHOTDIFFINFO = 1053 ' (Stream) 
            DP_VSTT_RNP_BROWSERTYPE = 1054
            DP_STARTUPASSETTYPE = 1055
            DP_STARTUPTYPE = 1056
            SCENARIOPART = 1057 ' (Stream) 
            DP_SETUP_FIXESSTATUS = 1058
            DP_SETUP_FIXESSUCCESSFUL = 1059
            STRM_LINKERTHROUGHPUT = 1060 ' (Stream) 
            DP_TOOLFIXSTATUS = 1061
            STRM_VC_LINKER_SWITCH = 1062 ' (Stream) DELETED FROM MANAGEMENT SITE
            DP_SETUP_VSONLINE = 1063
            STRM_VC_LINKER_SWITCHES = 1064 ' (Stream) 
            STRM_XAMLDESIGNERCOMMAND = 1065 ' (Stream) 
            EXTENSIONMANAGERAUTOCHECKUPDATES = 1066
            STRM_XAMLDESIGNERDESIGNERSTARTTIME = 1067 ' (Stream) 
            STRM_DESIGNER_VIEW_TIME = 1068 ' (Stream) 
            EDITOR_VIEW_TIME = 1069 ' (Stream) 
            SPLIT_VIEW_TIME = 1070 ' (Stream) 
            STRM_INTELLISENSE_STARTTIME = 1071 ' (Stream) 
            STRM_VC_LINKER_PARENTPROCESS = 1072 ' (Stream) 
            STRM_VC_LINKER_HOST_TARGET = 1073 ' (Stream) 
            STRM_DESIGNER_VIEWTIME = 1074 ' (Stream) 
            STRM_SPLIT_VIEWTIME = 1075 ' (Stream) 
            STRM_EDITOR_VIEWTIME = 1076 ' (Stream) 
            STRM_VC_LINKER_DIAGNOSTICS = 1077 ' (Stream) 
            STRM_LINKER_THROUGHPUT = 1078 ' (Stream) 
            WEBPLAT_STRM_GIT_OPEN = 1079 ' (Stream) DELETED FROM MANAGEMENT SITE
            STREAM_TEXTEDITOROPTIONS = 1080 ' (Stream) 
            STRM_XAML_DESIGNER_LOADTIME = 1081 ' (Stream) 
            STRM_XAML_DOC_VIEWTIME = 1082 ' (Stream) 
            STRM_ROAMINGSETTINGS_PERFORMANCE = 1083 ' (Stream) 
            WEBPLAT_STRM_CMD = 1084 ' (Stream) 
            WEBPLAT_STRM_GIT_ADD_BRANCH = 1085 ' (Stream) 
            WEBPLAT_STRM_GIT_ADD_REMOTE = 1086 ' (Stream) 
            WEBPLAT_STRM_GIT_INIT = 1087 ' (Stream) 
            WEBPLAT_STRM_MY_SITES = 1088 ' (Stream) 
            WEBPLAT_STRM_OPEN_FROM_FOLDER = 1089 ' (Stream) 
            WEBPLAT_STRM_OPEN_FROM_MY_SITES = 1090 ' (Stream) 
            WEBPLAT_STRM_OPEN_FROM_PORTAL = 1091 ' (Stream) 
            WEBPLAT_STRM_OPEN_FROM_REMOTE = 1092 ' (Stream) 
            WEBPLAT_STRM_PROVISION_SKIP = 1093 ' (Stream) 
            WEBPLAT_STRM_SIGN_IN = 1094 ' (Stream) 
            WEBPLAT_STRM_SIGN_IN_RESULT = 1095 ' (Stream) 
            WEBPLAT_STRM_SIGN_OUT = 1096 ' (Stream) 
            WEBPLAT_STRM_SKIP_SIGN_IN = 1097 ' (Stream) 
            WEBPLAT_STRM_TFS_ADD_TO_PROJECT = 1098 ' (Stream) 
            WEBPLAT_STRM_TFS_OPEN = 1099 ' (Stream) 
            STREAM_NAVTO2_USAGEPATTERNS = 1100 ' (Stream) 
            WEBPLAT_STRM_PROVISION = 1101 ' (Stream) 
            WEBPLAT_STRM_IMPORT_CERT = 1102 ' (Stream) 
            STRM_DEPLOYMENTSTREAM2 = 1103 ' (Stream) 
            DP_VSIINSTALLCOUNT = 1104
            STRM_VSIINSTALLCONTENTS = 1105 ' (Stream) 
            WEBPLAT_STRM_SUBSCRIBE = 1106 ' (Stream) 
            MVC = 1107 ' (Stream) 
            STRM_HISTORIC_LOG_OPEN3 = 1108 ' (Stream) 
            STRM_SPTOOLSPROJECTCONTENTS = 1109 ' (Stream) 
            WEBPLAT_STRM_GIT_OPEN_2 = 1110 ' (Stream) 
            STRM_SPTOOLSERRORS = 1111 ' (Stream) 
            STRM_VC_CASABLANCA_HEADERS = 1112 ' (Stream) 
            STRM_ASQM1 = 1113 ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_ASQM2 = 1114 ' (Stream) 
            SQM_DISPLAYXY = 1115
            SQM_DISPLAYVIRTUALXY = 1116
            STRM_VSONLINEOPERATION = 1117 ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VSONLINEOPERATIONRESULT = 1118 ' (Stream) 
            STRM_ASQM_1 = 1119 ' (Stream) 
            STRM_USERNOTIFICATIONS_NOTIFICATIONS = 1120 ' (Stream) 
            STRM_ASQM3 = 1121 ' (Stream) 
            STRM_VC_COMPILER_THROUGHPUT = 1122 ' (Stream) 
            STRM_TOOLSOPT_ROAMINGOPT = 1123 ' (Stream) 
            STRM_SETTINGSIMPORTEXPORTRESET = 1124 ' (Stream) 
            STRM_PROFILESELECTIONDIALOG = 1125 ' (Stream) 
            STRM_ROAMINGCONFLICTCHOICES = 1126 ' (Stream) 
            DP_XDE_CPUCOUNT = 1127
            DP_XDE_DISPLAYCOUNT = 1128
            DP_XDE_MEMORY = 1129
            DP_XDE_OSVERSION = 1130
            DP_XDE_OSSKU = 1131
            DP_XDE_PROCFREQ = 1132
            DP_XDE_TOUCHDEVICECOUNT = 1133
            DP_XDE_USERTYPE = 1134
            STRM_XDE_MONITORRES = 1135 ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_XDE_VIDEOADAPTERS = 1136 ' (Stream) 
            STRM_XDE_NETWORKPROTOCOLS = 1137 ' (Stream) 
            DP_XDE_SDKLANGUAGE = 1138
            DP_XDE_SNAPSHOTBOOTTIME2 = 1139
            DP_XDE_NOSNAPSHOTBOOTTIME2 = 1140
            DP_XDE_SHOWUITIME2 = 1141
            DP_XDE_INPUTUSED = 1142
            STRM_XDE_ZOOMVALUE = 1143 ' DELETED FROM MANAGEMENT SITE
            DP_XDE_ERRORDISPLAYED = 1144
            DP_XDE_SNAPSHOTINVALID = 1145
            STRM_XDE_CMDHISTORY = 1146 ' (Stream) 
            DP_SHELLDOCUMENTCREATEINIT = 1147 ' (Stream) 
            DP_EDITORINITIALIZEVIEW = 1148 ' (Stream) 
            SQM_WORKMEM_TOTALWORKINGSETMEMORY = 1149
            SQM_VIRTMEM_VSUPTIMEATPEAK = 1150
            STRM_XDE_ZOOMPERCENT = 1151 ' (Stream) 
            STRM_XDE_MONITORRESOLUTION = 1152 ' (Stream) 
            SQM_WORKMEM_AVAILPAGEFILE = 1153
            SQM_WORKMEM_VSUPTIMEATPEAK = 1154
            SQM_WORKINGMEMORYUSAGE = 1155 ' (Stream) 
            PEEK_DOT_MOUSE = 1156 ' DELETED FROM MANAGEMENT SITE
            PEEK_DOT_KEYBOARD = 1157 ' DELETED FROM MANAGEMENT SITE
            SQM_WORKMEM_PAGEFAULTCOUNT = 1158
            SQM_WORKMEM_PAGEFILEUSAGE = 1159
            SQM_WORKMEM_TOTALPAGEFILE = 1160
            SQM_WORKMEM_AVAILPHYSICAL = 1161
            SQM_LICENSEFAMILYTYPE = 1162
            SQM_LICENSESTATUSSOURCE = 1163
            SQM_LICENSENOTIFICATIONNUMBER = 1164
            SQM_LICENSEREFRESH = 1165
            STRM_TRACKPROJECTRETARGETING = 1166 ' (Stream) 
            SQM_LICENSESERIAL = 1167
            SETUP_LATESTUPDATEVERSION = 1168
            SQM_STARTPAGE_STARTUPOPTIONS = 1169
            SQM_STARTPAGE_RSSCONTENTDOWNLOAD = 1170 ' (Stream) 
            SQM_STARTPAGE_DOWNLOADUSERCONSENT = 1171
            SQM_STARTPAGE_PANELID = 1172 ' (Stream) 
            VS_INSTANCEID = 1173
            STRM_CODESENSE_TOOLSOPTIONS = 1174 ' (Stream) 
            STRM_CODESENSE_INDICATORUSAGE = 1175 ' (Stream) 
            STRM_PEEK_NAVIGATION = 1176 ' (Stream) 
            STRM_PEEK_OBRESULTCOUNT = 1177 ' (Stream) 
            STRM_PEEK_RECURSIONLEVEL = 1178 ' (Stream) 
            STRM_PEEK_REULTCOUNT = 1179 ' (Stream) 
            STRM_APPPACKAGEWIZARD_V2 = 1180 ' (Stream) 
            SERVICEPROVIDERDETAIL = 1181 ' DELETED FROM MANAGEMENT SITE
            STRM_PUSHNOTIFICATIONWIZARD_V1 = 1182 ' (Stream) 
            STRM_SERVICEMANAGER = 1183 ' (Stream) 
            STRM_PROVIDERCOUNT = 1184 ' (Stream) 
            STRM_SERVICEHANDLER = 1185 ' (Stream) 
            DP_SOURCECODEVIEWTIME = 1186
            STREAM_XAMLVSPANEUSAGE = 1187 ' (Stream) 
            STREAM_MTTFXDESPROC = 1188 ' (Stream) 
            SQM_PROCDESCRIPTION = 1189
            STRM_VSWEBPUBLISHSELECTIVE = 1190 ' (Stream) 
            PERF_CPUARCHITECTURE = 1191
            STRM_RM_RELEASESUSAGE = 1192 ' (Stream) 
            PERF_L2CACHE = 1193
            PERF_L3CACHE = 1194
            DP_RM_USAGEPERTFS = 1195 ' (Stream) 
            DP_NAVTO2_PREVIEW = 1196
            STRM_DIAGNOSTICS_HUB_TOOL_STREAM = 1197 ' (Stream) 
            STRM_DIAGNOSTICS_HUB_TOOL_SESSION = 1198 ' (Stream) 
            STRM_WEB_MTM_COMPARE_SESSION = 1199 ' (Stream) 
            PHYSICALCPU12 = 1200
            CPULOGICALCOUNT12 = 1201
            TFSAO_12_FULLCONFIGRESULTS = 1202 ' (Stream) 
            RAM12 = 1203
            PROCCLOCKSPEED12 = 1204
            PROCDATAWIDTH12 = 1205
            PROCFAMILY12 = 1206
            TFSAO_SETUPOPTIONS12 = 1207
            TFSAO_RUNTIME12 = 1208 ' (Stream) 
            STRM_VSWEBNEWPROJECT = 1209 ' (Stream) 
            STRM_VSWEBCONFIGUREAUTH = 1210 ' (Stream) 
            SQM_STARTPAGELAYOUT = 1211
            SQM_STARTPAGEFLAGS = 1212
            SQM_RESPONSIVENESS_BUCKET1 = 1213
            SQM_RESPONSIVENESS_BUCKET2 = 1214
            SQM_RESPONSIVENESS_BUCKET3 = 1215
            SQM_RESPONSIVENESS_BUCKET4 = 1216
            SQM_RESPONSIVENESS_BUCKET5 = 1217
            SQM_RESPONSIVENESS_BUCKET6 = 1218
            SQM_RESPONSIVENESS_BUCKET7 = 1219
            SQM_RESPONSIVENESS_BUCKET8 = 1220
            SQM_RESPONSIVENESS_BUCKET9 = 1221
            SQM_RESPONSIVENESS_BUCKET10 = 1222
            SQM_RESPONSIVENESS_BUCKET11 = 1223
            SQM_RESPONSIVENESS_BUCKET30 = 1224
            SQM_RESPONSIVENESS_TOTALDELAYCOUNT = 1225
            SQM_RESPONSIVENESS_TOTALDELAYTIME = 1226
            SQM_RESPONSIVENESS_COLLECTIONMODE = 1227 ' DELETED FROM MANAGEMENT SITE
            TOOLSOPTIONS = 1228 ' (Stream) 
            STRM_SPTOOLSOFFICEAPPPROJECTCONTENTS = 1229 ' (Stream) 
            SQM_CODESENSE_REFERENCES_NAVIGATED = 1230 ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_CODESENSE_REFERENCES_DATA = 1231 ' (Stream) 
            STRM_TOITEMNAME2 = 1232 ' (Stream) 
            DP_SID = 1233 '  DWORD64 
            VSPIX_DEBUG_SESSION = 1234
            DP_SIENANEWDOC = 1235
            DP_SIENACONTROLSATPREVIEW = 1236 ' (Stream) 
            DP_SIENABUILDNUMBER = 1237
            DP_SIENACONTROLSATPUBLISH = 1238 ' (Stream) 
            DP_SIENAERRORSATPREVIEW = 1239 ' (Stream) 
            DP_SIENAERRORSATPUBLISH = 1240 ' (Stream) 
            DP_SIENAFUNCTIONSATPREVIEW = 1241 ' (Stream) 
            DP_SIENAFUNCTIONSATPUBLISH = 1242 ' (Stream) 
            DP_SIENAOPENDOC = 1243
            DP_SIENASCREENSATPREVIEW = 1244 ' (Stream) 
            DP_SIENASCREENSATPUBLISH_2 = 1245 ' (Stream) 
            DP_SIENATOTALSESSIONTIME = 1246
            DP_SIENA_SESSIONGUID = 1247
            DP_SIENAUSERID = 1248
            DP_SIENAMACHINEID = 1249
            SQM_WATSON_P1 = 1250
            SQM_WATSON_P2 = 1251
            SQM_WATSON_P3 = 1252
            SQM_WATSON_P4 = 1253
            SQM_WATSON_P5 = 1254
            SQM_WATSON_P6 = 1255
            SQM_WATSON_P7 = 1256
            SQM_WATSON_P8 = 1257
            SQM_WATSON_P9 = 1258
            SQM_WATSON_P10 = 1259
            SQM_WATSON_BUCKETID_OLD = 1260 ' DELETED FROM MANAGEMENT SITE
            SQM_WATSON_TYPE = 1261
            SQM_FSC_BUILDVERSION = 1262
            SQM_FSC_CONFIG = 1263
            SQM_FSC_SOURCES = 1264
            SQM_FSC_COMPILETIME = 1265
            SQM_FSC_FXVERSION = 1266
            SQM_FSC_FSLIBVERSION = 1267
            SQM_FSC_REFERENCES = 1268
            SQM_FSC_ERRORS = 1269 ' (Stream) 
            STRM_TRACKPROJECTACQUISITION = 1270 ' (Stream) 
            SQM_WINSTOREAPPDEBUGGERACTION = 1271 ' DELETED FROM MANAGEMENT SITE
            DP_ISROSLYNENABLED = 1272
            VSWEBSQMFLAGS = 1273
            STRM_PROJECTTARGETS = 1274 ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_PROJECTREFSLIBS = 1275 ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_PROJECTREFSLIBSDF = 1276 ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_WATSON_BUCKETID_OLD2 = 1277 '  DWORD64 DELETED FROM MANAGEMENT SITE
            DATAID_SQM_WINSTORE_APP_DEBUGGER_ACTION = 1278 ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_WINSTORE_APP_DEBUGGER_ACTION = 1279 ' (Stream) 
            DP_PROJECTID = 1280
            DP_PROJECTID_HASH = 1281
            STRM_VS_PROJECT_DEV12 = 1282 ' (Stream) 
            STRM_PROJECTFILEDETAILS_DEV12 = 1283 ' (Stream) 
            STRM_PROJECT_REF_LIB_DEV12 = 1284 ' (Stream) 
            SQM_WATSON_BUCKETID = 1285
            DP_DEV12_VS_PROJECT_NUMTOTALFILES = 1286
            DP_DEV12_VS_PROJECT_NUMREFERENCES = 1287
            DP_DEV12_VS_PROJECT_OUTPUTTYPE = 1288
            DP_DEV12_VS_PROJECT_OUTPUTTYPEV2 = 1289
            DP_DEV12_VS_PROJECT_TARGETRUNTIME = 1290
            DP_DEV12_VS_PROJECT_PROJECTFLAGS = 1291
            DP_DEV12_VS_PROJECT_HASHKINDGUID = 1292
            DP_DEV12_VS_PROJECT_RAWKINDGUID = 1293
            DP_DEV12_VS_PROJECT_HASHFLAVORGUID = 1294
            DP_DEV12_VS_PROJECT_RAWFLAVORGUID = 1295
            DP_DEV12_VS_PROJECT_HASHTARGETFRAMEWORK = 1296
            DP_DEV12_VS_PROJECT_RAWTARGETFRAMEWORK = 1297
            DP_DEV12_VS_PROJECT_HASHCONFIGPLATFORM = 1298
            DP_DEV12_VS_PROJECT_RAWCONFIGPLATFORM = 1299
            DP_DEV12_VS_PROJECT_HASHTARGETPLATFORM = 1300
            DP_DEV12_VS_PROJECT_RAWTARGETPLATFORM = 1301
            DP_DEV12_VS_PROJECT_HASHPLATFORMVERSION = 1302
            DP_DEV12_VS_PROJECT_RAWPLATFORMVERSION = 1303
            DP_DEV12_VS_PROJECT_WEBSERVERTYPE = 1304
            FWLINKRESOLUTIONRETRYINFO = 1305 ' (Stream) 
            DP_XDE_INTERNALADAPTERREPAIRATTEMPTED = 1306
            DP_XDE_BOOTLANGUAGE = 1307
            STRM_VSONLINELONGIDLE = 1308 ' (Stream) 
            STRM_PEEK_EDITFREQUENCY = 1309 ' (Stream) 
            TFSAO_12_COLLECTIONSERVICINGINFO_DEPLOYMENT_START = 1310 ' (Stream) 
            TFSAO_12_COLLECTIONSERVICINGINFO_INDIVIDUAL = 1311 ' (Stream) 
            TFSAO_12_COLLECTIONSERVICINGINFO_DEPLOYMENT_END = 1312 ' (Stream) 
            PEEKCMDHISTORY_CONTEXT = 1313 ' (Stream) 
            SQM_WATSON_EVENTNAME = 1314
            STRM_JAVASCRIPT_NAVBARUSAGE = 1315 ' (Stream) 
            FIRSTLAUNCHSIGNIN = 1316
            DATAID_STRM_PYTHON_LAUNCH = 1317 ' (Stream) 
            DATAID_DP_PYTHON_INSTALLED_INTERPRETERS = 1318
            DATAID_DP_PYTHON_CONFIGURED_INTERPRETERS = 1319
            STRM_USERCONFIGTOUCH = 1320 ' (Stream) 
            TFS_VC_COMMAND_ENTRY_POINT = 1321
            STRM_VSWEBARTERY = 1322 ' (Stream) 
            STRM_VSWEBCREATENEWWEBSITE = 1323 ' (Stream) 
            STRM_VSWEBPROJECTNUGET = 1324 ' (Stream) 
            STRM_VSWEBSCAFFOLDINGCORE = 1325 ' (Stream) 
            STRM_VSWEBPUBLISHNUGET = 1326 ' (Stream) 
            STRM_VSUSAGEONTOUCHDEVICE_OLD = 1327 ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_COMPILETYPESCRIPTPROJECT = 1328 ' (Stream) 
            TS_STRM_PROJECTSUPPORT = 1329 ' (Stream) 
            STRM_TYPESCRIPTLANGUAGESERVICEFEATURES = 1330 ' (Stream) 
            STRM_DEV12COLLECTIONSERVICING_DEPLOYMENT_END = 1331 ' (Stream) 
            STRM_DEV12COLLECTIONSERVICING_DEPLOYMENT_START = 1332 ' (Stream) 
            STRM_DEV12COLLECTIONSERVICING_INDIVIDUAL = 1333 ' (Stream) 
            SQM_DEBUGGER_STEP_2 = 1334 ' (Stream) 
            STRM_MULTIMONCONFIGANDUSAGE = 1335 ' (Stream) 
            STRM_VSWEBSCAFFOLDING = 1336 ' (Stream) 
            CODEINDEX_CATCHUP_PROCESSED_CHANGESETS = 1337 ' (Stream) 
            STRM_VSUSAGEONTOUCH = 1338 ' (Stream) 
            STRM_VSWEBWAWSCREATION = 1339 ' (Stream) 
            STRM_VSUSAGEONTOUCHDEVICE = 1340 ' (Stream) 
            DP_DEV12_DISCRETE_MAPPINGS = 1341
            SQM_FSC_ERRORNUMBERS = 1342 ' (Stream) 
            SQM_FSC_WARNINGNUMBERS = 1343 ' (Stream) 
            SQM_FSC_WARNINGLEVEL = 1344
            SQM_FSC_WARNINGASERRORS = 1345
            SQM_FSC_SUPRESSWARNINGNUMBERS = 1346 ' (Stream) 
            SQM_FSC_WARNASERRORS_NUMBERS = 1347 ' (Stream) 
            SQM_FSC_WARNASWARNINGS_NUMBERS = 1348 ' (Stream) 
            FSC_WARNING_ON_NUMBERS = 1349 ' (Stream) 
            SQM_VS_OPTEDIN = 1350
            DP_SOLUTIONID = 1351
            DP_SOLUTIONID_PREVIOUS = 1352
            DATAID_SQM_BUILDVERSION = 1353
            DATAID_SQM_ROSLYN_COMPILERTYPE = 1354
            DATAID_SQM_ROSLYN_EMBEDVBCORE = 1355
            DATAID_SQM_ROSLYN_ERRORNUMBERS = 1356 ' (Stream) 
            DATAID_SQM_ROSLYN_LANGUAGEVERSION = 1357
            DATAID_SQM_ROSLYN_OUTPUTKIND = 1358
            DATAID_SQM_ROSLYN_REFERENCES = 1359
            DATAID_SQM_ROSLYN_SOURCES = 1360
            DATAID_SQM_ROSLYN_SUPPRESSWARNINGNUMBERS = 1361 ' (Stream) 
            DATAID_SQM_ROSLYN_WARNASERRORS_NUMBERS = 1362 ' (Stream) 
            DATAID_SQM_ROSLYN_WARNASWARNINGS_NUMBERS = 1363 ' (Stream) 
            DATAID_SQM_ROSLYN_WARNINGASERRORS = 1364
            DATAID_SQM_ROSLYN_WARNINGLEVEL = 1365
            DATAID_SQM_ROSLYN_WARNINGNUMBERS = 1366 ' (Stream) 
            DP_TOGGLEDOCKHEADER_MAXIMIZE = 1367
            DP_TOGGLEDOCKHEADER_RESTORE = 1368
            STRM_INTELLITRACE_ACTIONPROVIDER = 1369 ' (Stream) 
            DP_WEBPI_STARTUPTYPE = 1370
            DP_WEBPI_OPTIONSLINK = 1371
            DP_WEBPI_PRIMARYFEED = 1372
            DP_WEBPI_CARTLINK = 1373
            DP_WEBPI_ACCEPTEULA = 1374
            DP_WEBPI_DECLINEEULA = 1375
            DP_WEBPI_FINISHED = 1376
            SQM_RESPONSIVENESS_COLLECTIONMODE2 = 1377 ' DELETED FROM MANAGEMENT SITE
            SQM_COLLECTIONMODE_TEST = 1378
            STRM_WEBPICMD_PRODUCTS = 1379 ' (Stream) DELETED FROM MANAGEMENT SITE
            DP_WEBPICMD_FINISHED = 1380 ' DELETED FROM MANAGEMENT SITE
            STRM_WEBPI_INCOMPATPROCESS = 1381 ' (Stream) 
            DP_WEBPI_WEBSERVER = 1382
            DP_WEBPI_VIEWPRIVACYTERMS = 1383
            RENAMESESSIONINFO = 1384 ' (Stream) 
            LIGHTBULBSESSIONINFO = 1385 ' (Stream) DELETED FROM MANAGEMENT SITE
            DP_WEBPI_ADDTOCART_WEBPICMD = 1386
            DP_WEBPI_OS_LANG = 1387
            DP_WEBPI_OS_ARCH = 1388
            STRM_WEBPICMD_OFFLINEPRODUCTS = 1389 ' (Stream) 
            DP_WEBPI_UXORCMDLINE = 1390
            DP_WEBPI_INSTALLCANCEL = 1391
            DP_WEBPI_MAJOROS = 1392
            DP_WEBPI_MINOROS = 1393
            DP_WEBPI_SPMAJOR = 1394
            DP_WEBPI_SPMINOR = 1395
            DP_WEBPI_OS_SKU = 1396
            STRM_WEBPI_PRODUCTS = 1397 ' (Stream) 
            DP_WEBPI_REMOVEFROMCART = 1398
            DP_WEBPI_VIEWLICENSETERMS = 1399
            DP_WEBPI_DIRECTDOWNLOADLINK = 1400
            DP_WEBPI_PRIMARYFEEDOVERRIDE = 1401
            DP_WEBPI_CUSTOMFEEDCOUNT = 1402
            DP_WEBPI_ADVWEBSUPPORT = 1403
            DP_WEBPI_REMOTEDB = 1404
            DP_WEBPI_PREFLANGUAGE = 1405
            DP_WEBPI_INCOMPATPRODUCT = 1406
            DP_WEBPI_EXTERNAL = 1407
            STRM_WEBPI_SQMSTATE = 1408 ' (Stream) 
            DP_WEBPI_SAVEDBPASSWORD = 1409
            DP_WEBPI_MOREDETAILS = 1410
            DP_WEBPI_FEEDLOAD = 1411
            DP_WEBPI_ADDTOCART_CONTEXTUAL = 1412
            DP_WEBPI_ADDTOCART_UX = 1413
            DP_WEBPI_ADDTOCART_UNSPECIFIED = 1414
            DP_WEBPI_ADDTOCART_SEARCH = 1415
            DP_WEBPI_ADDTOCART_CONTEXTUALMINI = 1416
            STRM_MERCURY_CONTEXT_SWITCHER = 1417 ' (Stream) 
            STRM_INTELLITRACE_SUMMARY_DATAGRID_EVENT = 1418 ' (Stream) 
            DP_PERFMON_PROCESSCHANGED = 1419
            DP_APPDEPLOY_ENTRYPOINT = 1420
            DP_APPDEPLOY_FORCESD = 1421
            DP_UPDATEPACK_REFRESHCOUNT = 1422
            DP_ISETOOL_COMMAND = 1423
            DP_ISETOOL_HRESULT = 1424
            STRM_APPDEPLOY_DEPLOYMENT = 1425 ' (Stream) 
            STRM_UPDATEPACK_EXIT = 1426 ' (Stream) 
            STRM_PHONEREG_ERRORS = 1427 ' (Stream) 
            STRM_PERFRECORDER_SELECTED = 1428 ' (Stream) 
            STRM_PERFRECORDER_FILESSAVED = 1429 ' (Stream) 
            STRM_PERFMON_COUNTERSELECTED = 1430 ' (Stream) 
            STRM_APPVERIF_TESTSSELECTED = 1431 ' (Stream) 
            STRM_PWTOOLS_COMMANDHISTORY = 1432 ' (Stream) 
            STRM_PHONEREG_COMMANDHISTORY = 1433 ' (Stream) 
            LIGHTBULBSESSIONINFO2 = 1434 ' (Stream) 
            RENAMESESSIONINFO2 = 1435 ' (Stream) 
            DP_WEBPI_VIEWALLDEPENDENCIES = 1436
            DP_PRIVATEDOGFOODBUILDNUMBER = 1437
            DP_PRIVATEBUILDNUMBER = 1438
            STRM_DEBUGGER_MMA_HEAPWALK = 1439 ' (Stream) 
            STRM_MEMORYPROFILERTOOL_COMMANDS = 1440 ' (Stream) 
            STRM_MEMORYPROFILERTOOL_PERFORMANCE = 1441 ' (Stream) 
            STRM_MEMORYPROFILERTOOL_SETTINGS = 1442 ' (Stream) 
            DP_XDE_INSERTSDCARDCANCELLED = 1443
            DP_XDE_EJECTSDCARDCANCELLED = 1444
            DP_XDE_DIAGONALSCREENSIZE = 1445
            STRM_XDE_GUESTRESOLUTION = 1446 ' (Stream) 
            DP_XDE_CHECKPOINTDELETED = 1447
            DP_XDE_CHECKPOINTNAMECHANGED = 1448
            DP_XDE_CHECKPOINTDEFAULTCHANGED = 1449
            STRM_XDE_USERRESTORECHECKPOINTTIME = 1450 ' (Stream) 
            STRM_XDE_NOTIFICATIONSIMULATIONGETURILIST = 1451 ' (Stream) 
            DP_XDE_NOTIFICATIONSIMULATIONLOADPAYLOAD = 1452
            STRM_XDE_USERTAKECHECKPOINTTIME = 1453 ' (Stream) 
            STRM_XDE_NOTIFICATIONPAYLOADERROR = 1454 ' (Stream) 
            DP_XDE_NOTIFICATIONSIMULATIONSAVEPAYLOAD = 1455
            DP_XDE_NOTIFICATIONSIMULATIONPOSTPAYLOAD = 1456
            STRM_XDE_NOTIFICATIONSIMULATIONAPPSRETRIEVED = 1457 ' (Stream) 
            DP_XDE_NOTIFICATIONSIMULATIONSTATEENABLED = 1458
            STRM_XDE_LOWCOSTSENSORSAPPLIED = 1459 ' (Stream) 
            STRM_DEBUGGER_MMA_HEAPVIEWPERF = 1460 ' (Stream) 
            DP_XDE_CHECKPOINTWITHLCT = 1461
            AZUREINVITIATIONSTARTPAGEWORKFLOW = 1462 ' (Stream) 
            AZURESIGNINSUCCESSFULAFTERSTARTPAGECONNECT = 1463 ' (Stream) 
            DATAID_STRM_SAP_IMPORTS = 1464 ' (Stream) 
            STRM_INTELLITRACE_CALLVIEW = 1465 ' (Stream) 
            STRM_INTELLITRACE_FLATLIST = 1466 ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_CODESENSE_COLLAB_DATA = 1467 ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_AUTOHISTORYSESSION = 1468 ' (Stream) 
            DP_VB_EDITOR_XML_COMMIT_COUNT = 1469
            STRM_INTELLITRACE_WEBREQUEST_DETAILSPAGE = 1470 ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VSGRAPHICS_CAPTURETRACKING = 1471 ' (Stream) 
            STRM_DEV12RUNTIMESQM_BROWSERUSAGE = 1472 ' (Stream) 
            STRM_INTELLITRACE_DEBUG = 1473 ' (Stream) 
            STRM_DEBUGGER_SEQUENCE_EVENTS = 1474 ' (Stream) 
            DATAID_STRM_ADD_APP_PLATFORM = 1475 ' (Stream) 
            STRM_VSOAUTOUSERSERVERSQUERIED = 1476 ' (Stream) 
            AZURESDK = 1477 ' DELETED FROM MANAGEMENT SITE
            STRM_XAML_DESIGNER_ROBUSTNESS = 1478 ' (Stream) 
            STRM_CCT_COMMON_AZURE_TOOLS_ERROR = 1479 ' (Stream) 
            STRM_INTELLITRACE_EVENTLIST = 1480 ' (Stream) 
            STRM_INTELLITRACE_REQUESTEVENTLIST = 1481 ' (Stream) 
            STARTPAGEFAILURELOG = 1482 ' (Stream) 
            SQM_WEBPI_INSTANCEID = 1483
            SQM_CODELENS_ACTIVITY = 1484 ' (Stream) 
            SQM_CODELENS_PAYLOAD = 1485 ' (Stream) 
            STRM_VSGRAPHICS_ANALYSIS = 1486 ' (Stream) 
            SQM_CODELENS_COLLAB_DATA = 1487 ' (Stream) 
            STRM_DIAGNOSTICS_HUB_DOCUMENT_ANALYSIS = 1488 ' (Stream) 
            STRM_DIAGNOSTICS_HUB_GLOBAL = 1489 ' (Stream) 
            STRM_CCT_QUICK_CREATE_VM = 1490 ' (Stream) 
            STRM_CCT_ADD_ENVIRONMENT_FILES_TO_PROJECT = 1491 ' (Stream) 
            STRM_DEPLOYMENTSTREAM3 = 1492 ' (Stream) 
            STRM_WAT_REMOTEDEBUG = 1493 ' (Stream) 
            SQM_SYSTEM_DEFAULTLOCALENAME = 1494
            SQM_USER_DEFAULTLOCALENAME = 1495
            SQM_USER_GEOID = 1496
            STRM_WAT_UPGRADE_AZURE_TOOLS = 1497 ' (Stream) 
            STRM_EDITORZOOMLEVEL = 1498 ' (Stream) 
            DP_EDITORZOOMCOUNT = 1499
            DP_EDITORTOUCHSOOMCOUNT = 1500
            DP_EDITORSCROLLCOUNT = 1501
            DP_EDITORTOUCHSCROLLCOUNT = 1502
            SQM_CODELENS_GIT_COLLAB_DATA = 1503 ' (Stream) 
            PLATFORMLIGHTBULBSESSION = 1504 ' (Stream) 
            STRM_ROAMINGSETTINGSSUMMARY = 1505 ' (Stream) 
            STRM_KEYTIPS_USAGE = 1506 ' (Stream) 
            STRM_KEYTIPS_CONFLICT = 1507 ' (Stream) 
            STRM_MDD_SERVICE_ADDED = 1508 ' (Stream) 
            STRM_MDD_PROJECTS = 1509 ' (Stream) 
            STRM_MDD_BUILD = 1510 ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_MDD_LAUNCH = 1511 ' (Stream) 
            STRM_MDD_CORDOVA_PLUGINS = 1512 ' (Stream) 
            DP_WEBPI_OSBUILDNUMBER = 1513
            STRM_MDD_BUILDS = 1514 ' (Stream) 
            STRM_ROAMINGSETTINGSDETAIL = 1515 ' (Stream) 
            DP_INTELLITRACE_LOGOPEN_NONULTIMATESKU = 1516
            STRM_MANAGEDLANGUAGESRUDEEDITS = 1517 ' (Stream) 
            STRM_MANAGEDLANGUAGESRUDEEDITS_BLOCKING = 1518 ' (Stream) 
            STRM_ENCEDITSESSION = 1519 ' (Stream) 
            STRM_ENCDEBUGSESSION = 1520 ' (Stream) 
            STRM_ENCEMITDELTAERRORS = 1521 ' (Stream) 
            STRM_CCT_CSM_DEPLOYMENTPROJECTCREATED = 1522 ' (Stream) 
            SQM_ROSLYN_BUILDVERSION = 1523
            SQM_NETFX_VERSION = 1524
            STRM_CCT_CSM_DEPLOYTEMPLATEDIALOGCOMPLETION = 1525 ' (Stream) 
            STRM_CUSTOMLAYOUTS_LAYOUTSAVED = 1526 ' (Stream) 
            STRM_CUSTOMLAYOUTS_LAYOUTAPPLIED = 1527 ' (Stream) 
            STRM_CUSTOMLAYOUTS_LAYOUTMANAGED = 1528 ' (Stream) 
            STRM_CUSTOMLAYOUTS_TOOLWINPERLAYOUT = 1529 ' (Stream) 
            STRM_CCT_CSM_GALLERYTEMPLATESELECTED = 1530 ' (Stream) 
            STRM_VSGRAPHICS_SESSION = 1531 ' (Stream) 
            STRM_VSGRAPHICS_STARTSHADERDEBUGGING = 1532 ' (Stream) 
            STRM_CPLUSPLUS_FEATUREUSAGE = 1533 ' (Stream) 
            MANAGEDAPIADDEDFROMINTELLISENSE = 1534 ' (Stream) 
            DP_JSLS_REQUIREJSUSAGECOUNT = 1535
            STRM_CUSTOMLAYOUTS_FAULTS = 1536 ' (Stream) 
            AZUREQUICKSTARTCREATE = 1537
            STRM_WJ_PUBLISH = 1538 ' (Stream) 
            STRM_WJ_TEMPLATE = 1539 ' (Stream) 
            GALILEODEVBOARDMACHASH = 1540
            PLATFORMLIGHTBULBSESSION1 = 1541 ' (Stream) 
            DP_PYTHON_SURVEYNEWS_FREQUENCY = 1542
            DP_NODEJS_SURVEYNEWS_FREQUENCY = 1543
            STRM_MANAGEDAPISNIFFER = 1544 ' (Stream) 
            STRM_LIGHTSWITCH_UPGRADEVERSION = 1545 ' (Stream) 
            STRM_LIGHTSWITCH_PROJECTMETADATA = 1546 ' (Stream) 
            STRM_VSWEBPUBLISHDETAILS = 1547 ' (Stream) 
            DP_VSTT_LOADTEST_AUTCOUNTERUSAGE = 1548
            STRM_NPDSEARCHRESULTS = 1549 ' (Stream) 
            STRM_NPDUSAGEPATTERNS = 1550 ' (Stream) 
            STRM_DEBUGGER_PERFORMANCETIPS2 = 1551 ' (Stream) 
            STRM_WAT_DEBUG_DETAILS = 1552 ' (Stream) 
            STRM_NOTIFICATIONHUBEXTENSION = 1553 ' (Stream) 
            DP_JSLS_ASYNCREQUESTSMADE = 1554 ' (Stream) 
            STRM_MDD_DEBUGTARGETSESSION = 1555 ' (Stream) 
            STRM_DEBUGGER_CHILDPROCESSATTACH = 1556 ' (Stream) 
            STRM_MDD_OPTIONS_DLG = 1557 ' (Stream) 
            STRM_MDD_COMPAT_CHECK = 1558 ' (Stream) 
            STRM_NODEJS_ANALYSIS_LEVEL = 1559 ' (Stream) 
            PLATFORMLIGHTBULB = 1560 ' (Stream) 
            DATAID_STRM_MSBUILD_CUSTOMIZATIONS = 1561 ' (Stream) 
            DATAID_STRM_MSBUILD_IMPORT_ = 1562 ' (Stream) 
            DATAID_STRM_MSBUILD_ITEMTYPES_ = 1563 ' (Stream) 
            SQM_SYSTEM_VMIMAGE = 1564
            STRM_VSTAPROJECTLOADDETAILS = 1565 ' (Stream) 
            STRM_VSTAPROJECTDEBUGDETAILS = 1566 ' (Stream) 
            STRM_CCT_CSM_DEPLOYTEMPLATEDIALOG_SAVEMRUSETTINGS = 1567 ' (Stream) 
            STRM_PLATFORMTABLECONTROL = 1568 ' (Stream) 
            IMAGESERVICEFAULT_MESSAGE = 1569
            IMAGESERVICEFAULT_TYPE = 1570
            IMAGESERVICE_CACHESIZE = 1571
            IMAGESERVICE_CACHESIZEONDISK = 1572
            IMAGESERVICE_ROOTEXP = 1573
            IMAGESERVICE_CACHECOUNT = 1574
            IMAGESERVICECACHERESETSTATE = 1575
            IMAGESERVICE_CACHETELEMETRY = 1576 ' (Stream) 
            IMAGESERVICE_FAULTTELEMETRY = 1577 ' (Stream) 
            DP_TASKLIST_USERTASKCREATION = 1578
            STRM_IOT_DEVELOPERACTIONS = 1579 ' (Stream) 
            DP_TASKLIST_USERTASKLOADEDFROMPROJECTS = 1580
            STRM_MDD_BUILDS_IOS = 1581 ' (Stream) 
            IOTDEVKITOSVERSION = 1582
            IOTDEVKITDEVBOARDREVISION = 1583
            IOTDEVKITBIOSVERSION = 1584
            STRM_XAML_DESIGNER_UC_STATS = 1585 ' (Stream) 
            STRM_XAML_DESIGNER_TYPEUSAGE = 1586 ' (Stream) 
            STRM_XAML_DESIGNER_PROPERTY = 1587 ' (Stream) 
            STRM_PYTHON_PACKAGEINSTALL = 1588 ' (Stream) 
            STRM_OPTOUTVSONLINEOPERATIONRESULT = 1589 ' (Stream) 
            SETUP_DEFAULTSELECTIONSTREAM = 1590 ' (Stream) 
            SETUP_INITIALSELECTIONSTREAM = 1591 ' (Stream) 
            SETUP_FINALSELECTIONSTREAM = 1592 ' (Stream) 
            STRM_TASKLIST_USERTASK = 1593 ' (Stream) 
            DATAID_DP_DEV12_VS_PROJECT_HASHCPPPLATFORMTOOLSET = 1594
            DATAID_DP_DEV12_VS_PROJECT_RAWCPPPLATFORMTOOLSET = 1595
            STRM_WAT_DIAGNOSTIC_CONFIGURATION = 1596 ' (Stream) DELETED FROM MANAGEMENT SITE
            SQM_TELAPI_CLONEDSESSION = 1597
            SETUP_SECONDARYINSTALLERLAUNCHED = 1598
            SETUP_SESSIONGUID = 1599
            STRM_WJ_SERVEREXPLORER_FUNCTIONS = 1600 ' (Stream) 
            DP_CCT_TOTALCERTIFICATES = 1601
            STRM_CCT_DURATIONSINCELASTSIGNINPROMPTED = 1602 ' (Stream) 
            STRM_CCT_AUTHENTICATIONINFO = 1603 ' (Stream) 
            STRM_CCT_SUBSCRIPTIONCOUNTPERAZUREMANAGMENTENDPOINT = 1604 ' (Stream) 
            STRM_CCT_ADDNEWAZUREACCOUNT = 1605 ' (Stream) 
            STRM_WAT_DIAGNOSTICCONFIGURATION = 1606 ' (Stream) 
            STRM_VC_MDD_LAUNCH = 1607 ' (Stream) 
            STRM_VSTU_PROJECTINFO = 1608 ' (Stream) 
            STRM_VSTU_DEBUGGERSESSIONINFO = 1609 ' (Stream) 
            STRM_WAT_DIAGNOSTIC_VIEWDATARELOAD = 1610 ' (Stream) 
            STRM_WAT_DIAGNOSTIC_VIEWDATAEXECUTECOMMAND = 1611 ' (Stream) 
            TFSAO_12_DEPLOYMENTINFO = 1612
            TFSAO_12_NOOPTCONFIGURATIONRESULTS = 1613 ' (Stream) 
            DP_STRM_NEWPROJECTDETAILS = 1614 ' (Stream) 
            SETUP_PREVIOUSTHIRDPARTYSTREAM = 1615 ' (Stream) 
            DP_VSTU_VERSION = 1616
            STRM_C2CODEGEN = 1617 ' (Stream) DELETED FROM MANAGEMENT SITE
            STRM_VC_C2CODEGEN = 1618 ' (Stream) 
            STRM_CCT_DURATIONSINCELASTSIGNINPROMPTED2 = 1619 ' (Stream) 
            FUSION_LOGGING_ENABLED = 1620
            STRM_WAT_ETWCONFIGURATION = 1621 ' (Stream) 
            DP_VSTT_LOADTESTMENUUSED = 1622
            STRM_MDD_CONFIG_FILE_EDIT = 1623 ' (Stream) 
            DP_DEV12_VS_PROJECT_HASHCPPKEYWORD = 1624 ' DELETED FROM MANAGEMENT SITE
            DP_DEV12_VS_PROJECT_RAWCPPKEYWORD = 1625 ' DELETED FROM MANAGEMENT SITE
            STRM_VC_COMPILER_OS_MACRO = 1626 ' (Stream) 
            DP_DEV14_VS_PROJECT_HASH_CPPKEYWORD = 1627
            DP_DEV14_VS_PROJECT_RAW_CPPKEYWORD = 1628
            STRM_VC_COMPILER_TOOLSET = 1629 ' (Stream) 
            SETUP_SETUPREFRESHCONSENT = 1630
            SETUP_SETUPREFRESHCHECKTIME = 1631
            SETUP_SETUPREFRESHCHECKSUCCEEDED = 1632
            SETUP_SETUPREFRESHEXISTS = 1633
            SETUP_SETUPREFRESHDOWNLOADTIME = 1634
            SETUP_SETUPREFRESHDOWNLOADSUCCEEDED = 1635
            SETUP_SETUPREFRESHLAUNCHSUCCEEDED = 1636
            SETUP_SETUPREFRESHPROCESSTIME = 1637
            SETUP_SETUPREFRESHFAILURESTATE = 1638
            SETUP_SETUPREFRESHFAILURECODE = 1639 ' DELETED FROM MANAGEMENT SITE
            SETUP_SETUPREFRESHFAILURERETURNCODE = 1640
            SQM_CODEANALYSIS_SUPPRESS_ACTIVE_ISSUES = 1641
            MAX = 1642
        End Enum
    End Module

    <ComImport>
    <ComVisible(False)>
    <Guid("C1F63D0C-4CAE-4907-BE74-EEB75D386ECB")>
    <InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)>
    Friend Interface IVsSqm

        Sub GetSessionStartTime(<Out> ByRef time As ComTypes.FILETIME)

        Sub GetFlags(<Out, MarshalAs(UnmanagedType.U4)> ByRef flags As UInt32)

        Sub SetFlags(<[In], MarshalAs(UnmanagedType.U4)> flags As UInt32)

        Sub ClearFlags(<[In], MarshalAs(UnmanagedType.U4)> flags As UInt32)

        Sub AddItemToStream(<[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                            <[In], MarshalAs(UnmanagedType.U4)> value As UInt32)

        Sub SetDatapoint(<[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                         <[In], MarshalAs(UnmanagedType.U4)> value As UInt32)

        ' OBSOLETE IN SQMAPI.DLL. DO Not CALL.
        Sub GetDatapoint(<[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                         <Out, MarshalAs(UnmanagedType.U4)> ByRef value As UInt32)


        Sub EnterTaggedAssert(
            <[In], MarshalAs(UnmanagedType.U4)> dwTag As UInteger,
            <[In], MarshalAs(UnmanagedType.U4)> dwPossibleBuild As UInteger,
            <[In], MarshalAs(UnmanagedType.U4)> dwActualBuild As UInteger
            )

        Sub RecordCmdData(
            <[In]> ByRef pguidCmdGroup As Guid,
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
            )

        Sub GetHashOfGuid(
            <[In]> ByRef hashGuid As Guid,
            <Out, MarshalAs(UnmanagedType.U4)> ByRef resultantHash As UInteger
            )

        Sub GetHashOfString(
            <[In], MarshalAs(UnmanagedType.BStr)> hashString As String,
            <Out, MarshalAs(UnmanagedType.U4)> ByRef resultantHash As UInteger
            )

        Sub IncrementDatapoint(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
            )

        Sub SetDatapointBits(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
            )

        Sub SetDatapointIfMax(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
            )

        Sub SetDatapointIfMin(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
            )

        Sub AddToDatapointAverage(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
            )

        Sub StartDatapointTimer(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32
            )

        Sub RecordDatapointTimer(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32
            )

        Sub AccumulateDatapointTimer(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32
            )

        Sub AddTimerToDatapointAverage(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32
            )

        Sub AddArrayToStream(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.LPArray, ArraySubType:=UnmanagedType.U4, SizeParamIndex:=2)> data As UInteger(),
            <[In], MarshalAs(UnmanagedType.I4)> count As Integer
        )

    End Interface

    <ComImport>
    <ComVisible(False)>
    <Guid("BE5F55EB-F02D-4217-BCB6-A290800AF6C4")>
    <InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)>
    Friend Interface IVsSqm2

        Sub SetBoolDatapoint(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.U4)> fValue As UInteger
            )

        Sub SetStringDatapoint(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.BStr)> strValue As String
        )

        Sub AddToStreamDWord(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.U4)> cTuple As UInteger,
            <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )

        Sub AddToStreamString(
            <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
            <[In], MarshalAs(UnmanagedType.U4)> cTuple As UInteger,
            <[In], MarshalAs(UnmanagedType.BStr)> strValue As String
        )

        Sub GetObfuscatedString(
            <[In], MarshalAs(UnmanagedType.BStr)> input As String,
            <Out, MarshalAs(UnmanagedType.BStr)> ByRef output As String
        )

    End Interface


    <ComImport>
    <ComVisible(False)>
    <Guid("B17A7D4A-C1A3-45A2-B916-826C3ABA067E")>
    <InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)>
    Friend Interface IVsSqmMulti


        Function GetOptInStatus() As <MarshalAs(UnmanagedType.VariantBool)> Boolean

        Sub UnloadSessions()

        Sub EndAllSessionsAndAbortUploads(
                )

        Sub BeginSession(
                <[In], MarshalAs(UnmanagedType.U4)> sessionType As UInt32,
                <[In], MarshalAs(UnmanagedType.VariantBool)> alwaysSend As System.Boolean,
                <Out, MarshalAs(UnmanagedType.U4)> ByRef sessionHandle As UInt32
            )

        Sub EndSession(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32
            )

        Sub RegisterSessionHandle(
                <[In]> ByRef sessionIdentifier As Guid,
                <[In], MarshalAs(UnmanagedType.U4)> dwSessionHandle As UInteger
        )

        Function GetSessionHandleByIdentifier(
                <[In]> ByRef sessionIdentifier As Guid
             ) As <MarshalAs(UnmanagedType.U4)> Integer


        Sub GetSessionStartTime(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <Out> ByRef time As System.Runtime.InteropServices.ComTypes.FILETIME
            )

        Function GetGlobalSessionGuid() As Guid

        Function GetGlobalSessionHandle() As <MarshalAs(UnmanagedType.U4)> Integer

        Sub SetGlobalSessionGuid(
                <[In]> ByRef pguidSessionGuid As Guid
            )

        Sub GetFlags(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <Out, MarshalAs(UnmanagedType.U4)> ByRef flags As UInt32
        )
        Sub SetFlags(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> flags As UInt32
        )
        Sub ClearFlags(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> flags As UInt32
        )
        Sub SetDatapoint(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )
        Sub SetBoolDatapoint(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> fValue As UInt32
            )
        Sub SetStringDatapoint(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.BStr)> strValue As String
        )
        Sub SetDatapointBits(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )
        Sub IncrementDatapoint(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )

        Sub SetDatapointIfMax(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )
        Sub SetDatapointIfMin(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )
        Sub AddToDatapointAverage(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )
        Sub StartDatapointTimer(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32
        )
        Sub RecordDatapointTimer(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32
        )
        Sub AccumulateDatapointTimer(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32
        )
        Sub AddTimerToDatapointAverage(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32
        )
        Sub AddItemToStream(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )
        Sub AddArrayToStream(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.LPArray, ArraySubType:=UnmanagedType.U4, SizeParamIndex:=2)> data As UInteger(),
                <[In], MarshalAs(UnmanagedType.I4)> count As Integer
        )
        Sub AddToStreamDWord(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> cTuple As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )
        Sub AddToStreamString(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> cTuple As UInteger,
                <[In], MarshalAs(UnmanagedType.BStr)> strValue As String
        )
        Sub RecordCmdData(
                <[In], MarshalAs(UnmanagedType.U4)> sessionHandle As UInt32,
                <[In]> ByRef pguidCmdGroup As Guid,
                <[In], MarshalAs(UnmanagedType.U4)> dataPointID As UInt32,
                <[In], MarshalAs(UnmanagedType.U4)> value As UInt32
        )
        Sub GetHashOfGuid(
                <[In]> ByRef hashGuid As Guid,
                <Out, MarshalAs(UnmanagedType.U4)> ByRef resultantHash As UInteger
            )
        Sub GetHashOfString(
                <[In], MarshalAs(UnmanagedType.BStr)> hashString As String,
                <Out, MarshalAs(UnmanagedType.U4)> ByRef resultantHash As UInteger
            )
        Sub SetProperty(
                 <[In], MarshalAs(UnmanagedType.U4)> propid As UInt32,
                 <[In]> ByRef varKey As Guid,
                 <[In]> varValue As Object
            )
        Sub Get64BitHashOfString(
                <[In], MarshalAs(UnmanagedType.BStr)> hashString As String,
                <Out, MarshalAs(UnmanagedType.U8)> ByRef resultantHash As UInt64
            )
    End Interface



    <ComImport>
    <ComVisible(False)>
    <Guid("16be4288-950b-4265-b0dc-280b89ca9979")>
    <InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)>
    Friend Interface IVsSqmOptinManager

        Sub GetOptinStatus(
            <Out, MarshalAs(UnmanagedType.U4)> ByRef optinStatus As UInteger,
            <Out, MarshalAs(UnmanagedType.U4)> ByRef preferences As UInteger
            )

        Sub SetOptinStatus(
                    <[In], MarshalAs(UnmanagedType.U4)> optinStatus As UInteger
            )

    End Interface


    <ComImport>
    <ComVisible(False)>
    <Guid("2508FDF0-EF80-4366-878E-C9F024B8D981")>
    Friend Interface SVsLog
    End Interface
End Namespace




