//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.ProjectSystem.Rules.PropertyPages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.ProjectSystem.Rules.PropertyPages.PropertyPageResources", typeof(PropertyPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the project&apos;s application settings and properties..
        /// </summary>
        internal static string ApplicationPage_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ApplicationPage_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings for the application..
        /// </summary>
        internal static string ApplicationPage_GeneralCategory_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_GeneralCategory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ApplicationPage_GeneralCategory_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_GeneralCategory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install other frameworks.
        /// </summary>
        internal static string ApplicationPage_InstallOtherFrameworksProperty_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_InstallOtherFrameworksProperty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the version of .NET that the application targets. This option can have different values depending on which versions of .NET are installed on your computer..
        /// </summary>
        internal static string ApplicationPage_InterceptedTargetFrameworkProperty_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_InterceptedTargetFrameworkProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target framework.
        /// </summary>
        internal static string ApplicationPage_InterceptedTargetFrameworkProperty_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_InterceptedTargetFrameworkProperty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFM.
        /// </summary>
        internal static string ApplicationPage_InterceptedTargetFrameworkProperty_SearchTerms {
            get {
                return ResourceManager.GetString("ApplicationPage_InterceptedTargetFrameworkProperty_SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of application to build..
        /// </summary>
        internal static string ApplicationPage_OutputTypeProperty_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_OutputTypeProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output type.
        /// </summary>
        internal static string ApplicationPage_OutputTypeProperty_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_OutputTypeProperty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConsoleApplication.
        /// </summary>
        internal static string ApplicationPage_OutputTypeProperty_ExeValue_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_OutputTypeProperty_ExeValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Library.
        /// </summary>
        internal static string ApplicationPage_OutputTypeProperty_LibraryValue_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_OutputTypeProperty_LibraryValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsApplication.
        /// </summary>
        internal static string ApplicationPage_OutputTypeProperty_WinExeValue_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_OutputTypeProperty_WinExeValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging settings for the application..
        /// </summary>
        internal static string ApplicationPage_PackagingCategory_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_PackagingCategory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        internal static string ApplicationPage_PackagingCategory_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_PackagingCategory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource settings for the application..
        /// </summary>
        internal static string ApplicationPage_ResourcesCategory_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_ResourcesCategory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32 Resources.
        /// </summary>
        internal static string ApplicationPage_ResourcesCategory_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_ResourcesCategory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the semicolon-delimited list of frameworks that this project will target..
        /// </summary>
        internal static string ApplicationPage_TargetFrameworksProperty_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetFrameworksProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target frameworks.
        /// </summary>
        internal static string ApplicationPage_TargetFrameworksProperty_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetFrameworksProperty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFM.
        /// </summary>
        internal static string ApplicationPage_TargetFrameworksProperty_SearchTerms {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetFrameworksProperty_SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build this project for multiple target frameworks..
        /// </summary>
        internal static string ApplicationPage_TargetMultipleFrameworksProperty_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetMultipleFrameworksProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target multiple frameworks.
        /// </summary>
        internal static string ApplicationPage_TargetMultipleFrameworksProperty_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetMultipleFrameworksProperty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the operating system that this project will target..
        /// </summary>
        internal static string ApplicationPage_TargetPlatformIdentifierProperty_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetPlatformIdentifierProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target OS.
        /// </summary>
        internal static string ApplicationPage_TargetPlatformIdentifierProperty_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetPlatformIdentifierProperty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform.
        /// </summary>
        internal static string ApplicationPage_TargetPlatformIdentifierProperty_SearchTerms {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetPlatformIdentifierProperty_SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the version of the operating system this project will target..
        /// </summary>
        internal static string ApplicationPage_TargetPlatformVersionProperty_Description {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetPlatformVersionProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target OS version.
        /// </summary>
        internal static string ApplicationPage_TargetPlatformVersionProperty_DisplayName {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetPlatformVersionProperty_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform.
        /// </summary>
        internal static string ApplicationPage_TargetPlatformVersionProperty_SearchTerms {
            get {
                return ResourceManager.GetString("ApplicationPage_TargetPlatformVersionProperty_SearchTerms", resourceCulture);
            }
        }
    }
}
