name: Backport PR to branch
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  backport:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@main
    with:
        pr_description_template: |
          Backport of #%source_pr_number% to %target_branch%
          
          Requested in: %source_pr_url%#issuecomment-%trigger_comment_id%

          /cc %cc_users%
